### ISSUE TITLE
Spectrum style Stripes is missing from Dopamine Preview 10 and 11

### ISSUE THREAD

**Issue by jed-development** [digimezzo/dopamine-windows#1009]
## I'm submitting a...

<pre><code>
[X] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro 64x 1903 - 18362.239
* Dopamine version: Dopamine 2.0 (Preview 10 & 11)

## Reproduction steps

* Step 1 Open Dopamine
* Step 2 Go to Settings and navigate to Playback
* Step 3 Under Spectrum Analyser, look at the Spectrum style

## Observed behavior

The Spectrum style Stripes is missing from both Preview 10 and 11, whereas it is in Preview 9 and below.

## Desired behavior

The Spectrum style Stripes should be there.

**Comment by digimezzo** [comment]
@jed-development That's correct. It was removed intentionally. It didn't behave as I wished. If I can get it to work correctly, I'll add it again.
