### ISSUE TITLE
Shuffle playing deleted artist

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#101]
I've removed several Artists / Albums / Songs from my collection (right click -> remove; not as a file), but shuffle will play the the items no matter what :)

![capture](https://cloud.githubusercontent.com/assets/4146263/17559692/74a25500-5f1f-11e6-8a15-25f400639450.JPG)

**Comment by digimezzo** [comment]
That's looks like a bug. I'll look into it.

**Comment by digimezzo** [comment]
Dopamine keeps a list of last played songs in table QueuedTracks. When pressing play the next time Dopamine is started, it enqueues that list and plays those songs. It seems that deleting songs, doesn't remove them from that list.

Additional problem: PlaybackService also has a Queue which is filled from QueuedTracks when PlaybackService is created.
