### ISSUE TITLE
Playlist Resets When Starting from the Middle

### ISSUE THREAD

**Issue by Alexander12444** [digimezzo/dopamine-windows#1014]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro 1903 Build 18362.267
* Dopamine version: 2.0 Preview 12

## Reproduction steps

* With shuffle off, start playing a song from a list such as the left side menu or the songs tab. Doing this in the now playing menu does not produce this bug, nor does double clicking an album cover.
* Either hit next or wait for the song to end.
* The next song to play will be the first song in the now playing list, regardless of the song order, even if the first song was selected. (the first song will play twice)

## Observed behavior

The playlist resets to the first song after the end of the selected song, then plays normally in order from the beginning. Re-selecting a song from the middle of the playlist in now playing will work normally, but selecting a song from the regular tabs will reproduce the behavior and reset to the beginning again.

## Desired behavior

The song after the selected song should play next instead of resetting to the beginning of the playlist.

## Log file

Nothing of note.

**Comment by digimezzo** [comment]
This is probably related to 72a262af9d43fc9d555fbfaa81d1a345bdb5d8f6
