### ISSUE TITLE
Taskbar quick play buttons have default color

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#102]
I've changed the Theme color to orange, but the taskbar's buttons remain the default blue

![task-buttons](https://cloud.githubusercontent.com/assets/4146263/17559853/fa358f70-5f1f-11e6-93bb-4b034a2c050c.JPG)

**Comment by digimezzo** [comment]
I can, unfortunately, do nothing about this. These buttons are icons that cannot be dynamically changed. The only thing I could do, is give them a neutral color so they'd match all themes.

**Comment by kbalint** [comment]
yeah I thought, however alpha-gray icons would be nice :)

**Comment by digimezzo** [comment]
I changed the status of this issue again. It makes sense to make the color more neutral. Thanks for the suggestion.
