### ISSUE TITLE
Remove from disk option in playlist

### ISSUE THREAD

**Issue by timea-techgirl** [digimezzo/dopamine-windows#1022]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[X] Feature request
</code></pre>

## Feature
**I really really need the option "Remove from disk" from the playlist. I use cover player or micro player mode. I sort songs and delete the ones I don't need. I can't search it in the folders and delete. I want to delete it directly from the playlist. I can only see "Remove from Now playing". I also need "Remove from disk"**

**Comment by digimezzo** [comment]
@timeakesmarky this option has now been added. It will be available in the next preview.
