### ISSUE TITLE
Naming Scheme Changes View/Play Order in Folders View

### ISSUE THREAD

**Issue by njayp** [digimezzo/dopamine-windows#1024]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10
* Dopamine version: preview 13

## Reproduction steps

* Naming scheme like this:
![image](https://user-images.githubusercontent.com/35627686/63389342-4a292d00-c360-11e9-9ac4-e3ed23d85975.png)

* Open using folder view

* Songs are out of order:

![image](https://user-images.githubusercontent.com/35627686/63388500-7f804b80-c35d-11e9-9cf8-f9aae8845412.png)

## Observed behavior

songs are displayed and play out of order

## Desired behavior

songs are sorted album->disc->track, which is already accurately collected by dopamine:

![image](https://user-images.githubusercontent.com/35627686/63389114-93c54800-c35f-11e9-9963-d72f736337ac.png)

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3522864/Dopamine.log)

**Comment by digimezzo** [comment]
@arc-tec That is the same order as the files are displayed in Windows Explorer right? Currently, the folders view should display files in the same order as they are in the folder. If that's not the case, then it's a bug.

**Comment by njayp** [comment]
As you can see from the first screenshot, windows displays this album in the correct order. The second screenshot shows that dopamine has a different ordering than windows.

**Comment by digimezzo** [comment]
@arc-tec oops, sorry, I missed that. Thanks for pointing it out again. That's a bug then. I'll fix it in the next preview.

**Comment by njayp** [comment]
tyvm for fix!
