### ISSUE TITLE
Dopamine won't open

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#1033]
This was reported by @BaturaET
A while ago, within 2 months or so, I was using Music Player and you and it is just amazing, currently it has updated to version 2.0 (Preview 13) and it just doesn't open anymore. I tried to reinstall it by downloading straight from the site and not even the old version works now. it appears in the task manager but soon closes

**Comment by digimezzo** [comment]
@BaturaET Could you send me the log file? You'll find it in directory: %appdata%\Dopamine\Log
Please note that using an old version after installing a more recent version is only possible after deleting the directory that contains the Dopamine settings and database. The directory is located here: %appdata%\Dopamine
If you delete the Dopamine folder, or all its contents, you shoudl be able to run an older version again.

**Comment by BaturaET** [comment]
I tried today to install the latest version on the site again (*This:*
*Dopamine
2.0 (Preview 13).msi - MSI File - 45 MB - Aug 13 2019 7:17 PM* (
*https://www.digimezzo.com/content/software/dopamine/Dopamine%202.0%20(Preview%2013).msi
<https://www.digimezzo.com/content/software/dopamine/Dopamine%202.0%20(Preview%2013).msi>*
)

I had already searched my entire computer and deleted any folders for
Dopamine.
As soon as I installed it a small window appeared that was preparing the
program, it was even open in the task manager, but closed by itself

Em seg, 23 de set de 2019 às 03:00, Digimezzo <notifications@github.com>
escreveu:

**Comment by BaturaET** [comment]
Em ter, 24 de set de 2019 às 16:26, Phelipe Breno <brenofpp1@gmail.com>
escreveu:

**Comment by digimezzo** [comment]
@BaturaET Could you check if your issue is related to this: https://github.com/digimezzo/Dopamine/issues/984

**Comment by BaturaET** [comment]
Hey, problem already solved, in the end the problem was really on my PC.
Your program was running in perfect condition.  but thanks for your
attention.

Em qui, 26 de set de 2019 06:59, Digimezzo <notifications@github.com>
escreveu:

**Comment by madmax2** [comment]
@BaturaET what was the solution?

same problem here...
