### ISSUE TITLE
Problems with reordering songs in playlist

### ISSUE THREAD

**Issue by Spirialis** [digimezzo/dopamine-windows#1034]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10.0.17763
* Dopamine version: preview 13

## Reproduction steps

* Step 1 - Open any playlist
* Step 2 - Click and drag a song above/below any other song to change the order of the songs in the playlist

## Observed behavior

The songs appear in the interface to be reordered but the new order is not saved.  Leaving the playlist screen and coming back will result in the songs listed in the original order.

## Desired behavior

New order of songs should be saved for non-smart playlists

## Log file

When attempting to re-order a static (.m3u) playlist:  
2019-09-25 21:45:17.272|Error|PlaylistService.SetStaticPlaylistOrderAsync|792|Cannot set playlist order. This is not a static playlist.

When attempting to re-order a smart (.dspl) playlist:  
2019-09-25 21:46:20.325|Error|PlaylistService.SetStaticPlaylistOrderAsync|829|Could not set the playlist order. Exception: Could not find a part of the path '[playlist file path/name]**.m3u**'.

Seems like something's probably backwards between static and smart playlists here.

**Comment by digimezzo** [comment]
@Spirialis thanks for reporting this. I'll investigate.

**Comment by radonnachie** [comment]
Is #1037 not related?

**Comment by digimezzo** [comment]
@Spirialis This is now fixed. The check was indeed inversed.
