### ISSUE TITLE
Album Playthrough Ordering Not Reset

### ISSUE THREAD

**Issue by radonnachie** [digimezzo/dopamine-windows#1037]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10.0.18362 Build 18362
* Dopamine version: 2.0 (Preview 13)

## Reproduction steps

* Step 1:  In album view, select an album.
* Step 2: Double-click a track noting which is next.
* Step 3: Change the order by clicking on the button in the top-right of the track listing.
* Step 4: Double-click on the a track to start playing the album anew, then click 'Next'.

## Observed behavior

The album's track order is as per the ordering when the tracks are first played. The changing of the album's order does not update the play list, even when starting the track again.

## Desired behavior

Updates to the album's track order should change the track order, at least when the album is started anew.

**Comment by radonnachie** [comment]
Related to #1034?

**Comment by digimezzo** [comment]
@RocketRoss it is not related to #1034.
