### ISSUE TITLE
Discord Rich Presence 

### ISSUE THREAD

**Issue by din-dawn** [digimezzo/dopamine-windows#1039]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Please add discord status support(rich presence) as many of music player is supporting it by plugins.
## Example
![Untitled](https://user-images.githubusercontent.com/56496024/66710597-89975700-edae-11e9-8646-02b30b33c3ac.png)

**Comment by radonnachie** [comment]
Already requested in #1027?

**Comment by digimezzo** [comment]
@RocketRoss Indeed, it's a duplicate of #1027.
@EdgeChan I'll try to add this for version 2.0. I've tried this out a few days ago, but it wasn't working. I'll have another look at it.

**Comment by Mglbthirshe** [comment]
Waiting

**Comment by digimezzo** [comment]
> Waiting

@Mglbthirshe I invite you to submit a pull request if development is too slow. All help is welcome. Thanks!

**Comment by innocenzi** [comment]
Hey, I would have contributed myself but I unfortunately have no experience with C#, and I couldn't build the project locally when I tried to. 

As arguments to make you work on this, I'd say:

- It would make great advertising (eg. "Playing with Dopamine", or using the logo and name on the image part of the Rich Presence)
- I think that would be fairly easy to implement. There are a few C# libs that make it a breeze to add, the most well-known probably being [Leeche's](https://github.com/Lachee/discord-rpc-csharp)

I'd have asked a contribution guide so I can PR this myself, but I'm pretty sure that'd be more work than to actually implement it. 😄 

Anyway, thanks for your work even if you decide to not implement it before v3!

Related: https://github.com/digimezzo/dopamine-windows/issues/966

**Comment by innocenzi** [comment]
Nevermind, I managed to fix my issues and I have a working prototype that I may PR soon. :)
