### ISSUE TITLE
Design suggestions (for Dopamine 3.0?)

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#1043]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Hey again 😉

I really like the design of Dopamine but I can't stop comparing it with the Deezer UI (desktop version). I think bringing some UI elements from there could enhance the design of Dopamine.

- bolder font
- midnight theme
- an option to disable the album background in Now Playing mode
- larger cover in Now Playing mode + current song w/ accent color

Dopamine
![Now Playing 2 Dopamine](https://user-images.githubusercontent.com/56157596/66931937-21a77180-f037-11e9-819f-962158db5b84.png)
Deezer
![Now Playing 2 Deezer](https://user-images.githubusercontent.com/56157596/66931936-21a77180-f037-11e9-86ae-e54715b42329.png)

- when you click on the artist's name it brings you to the 'artist page' (where you can see all his/her songs/albums
![Deezer_artist](https://user-images.githubusercontent.com/56157596/66941273-d7c68780-f046-11e9-84b4-e169ef9c3b32.png)

**Comment by lushuyu** [comment]
It looks wonderful!

**Comment by digimezzo** [comment]
These are good suggestions. Thanks! I'll consider them for Dopamine 3.0
