### ISSUE TITLE
Dopamine crashes when all songs in the current playlist are deleted

### ISSUE THREAD

**Issue by lushuyu** [digimezzo/dopamine-windows#1044]
## I'm submitting a...

<pre><code>
[   ] Regression 
[ x ] Bug report  
[   ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 1903
* Dopamine version: 2.0 Preview 15

## Reproduction steps

Del all song in now-playing list

## Observed behavior

Dopamine exited right away.

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3735256/Dopamine.log)

**Comment by lushuyu** [comment]
Don't mind my poor English.

**Comment by digimezzo** [comment]
Thanks for reporting this. I fixed it.
