### ISSUE TITLE
External Control API CommunicationException with GetCurrenTrack()

### ISSUE THREAD

**Issue by SiskSjet** [digimezzo/dopamine-windows#1045]
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 1903 Build 18362.418
* Dopamine version: 2.0 Preview 15

## Reproduction steps

* Step 1 Implement External Control API with [this ](https://github.com/Magentaize/Dopamine-ExternalControl-Support) example
* Step 2 Create a connected service in project
* Step 3 Create a test project and call the `GetCurrenTrack()` or `GetCurrenTrackAsync()` method from an `IExternalControlServerCallback` instance.

## Observed behavior

It throws an `System.ServiceModel.CommunicationException` exception.
```
System.ServiceModel.CommunicationException: Der Server hat keine sinnvolle Antwort gegeben; dies kann durch einen nicht übereinstimmenden Vertrag, ein vorzeitiges Herunterfahren der Sitzung oder durch einen internen Serverfehler verursacht sein.
   bei System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   bei System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   bei System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   bei System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei DopamineHistory.History.<GetPlayedTrack>d__7.MoveNext() in D:\Projekte\c#\DopamineHistory\DopamineHistory\Program.cs:Zeile 104.
```

## Desired behavior

It should retrieve an `ExternalTrack` object.

## Additional Notes
It is working with version 1.5.14 but I belive never in one of the 2.0 Previews.

**Comment by digimezzo** [comment]
The example is indeed out of date. I'll have a look at it.

**Comment by SiskSjet** [comment]
Yea it's old but most of it still works with the preview builds besides the IFftDataServer and the GetCurrenTrack method.

**Comment by digimezzo** [comment]
I'm still looking into this issue. I'm not sure yet what broke it. I'll keep investigating.

**Comment by digimezzo** [comment]
@SiskSjet The issue is fixed.
