### ISSUE TITLE
Not saving lyrics in audio file

### ISSUE THREAD

**Issue by DeusArcana** [digimezzo/dopamine-windows#1049]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version:  Windows 10 Home Single Language 10.0.18362.418
* Dopamine version: 2.0 (Preview 15)

## Reproduction steps

* Search lyrics from Xiami Lyrics usually
* Right click - Save in audio file
* Or Right click - Edit - Save in audio file
* Next song
* Playing song again

## Observed behavior
Doesn't save lyrics, it loads the lyrics again

## Desired behavior
I should see the lyrics on the audio file

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3806921/Dopamine.log)

**Comment by lushuyu** [comment]
I met this bug too.
At first I think lyrics can not be saved in FLAC music.
But just now I found I can't do that in MP3 music too.
Lyrics disappeared after matching lyrics.

**Comment by lushuyu** [comment]
I can't Choose lyrics matched...
And CTRL+T seems unavailable.
Oh I want to open a new issue.

**Comment by DeusArcana** [comment]
@lushuyu in my case it didn't save the lyrics at all, it didn't matter how I tried to save them or from which source I tried to get the lyrics from...

**Comment by digimezzo** [comment]
@DeusArcana This bug is now fixed. I'll be available in preview 17.
