### ISSUE TITLE
on RDP disconnect: player skips to next track

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#105]
As strange as it sounds: disconnecting from a Remote Desktop session (Android MS Remote Desktop client 8.1.37.135) makes the player skip to the next track (in standard playlist / album / shuffle mode), even if the player is not in the foreground. Possibly reading some global keys?

**Comment by digimezzo** [comment]
This bug should not happen anymore in the latest 1.2 preview (build 820). Before build 820, a dirty hack was used to detect audio device changes. That hack sometimes caused playback interruptions when other software interacts with Media Foundation. Playback interruptions were handled in Dopamine by switching to the next track. In build 820, the hack was removed, and proper audio device switching was implemented.
