### ISSUE TITLE
Discs 10+ out of Order

### ISSUE THREAD

**Issue by chadfranklin47** [digimezzo/dopamine-windows#1054]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro Version 1903 build 18362.476
* Dopamine version: 2.0 (Preview 15)

## Reproduction steps

* Add an album in a folder that contains more than 10 Discs
* Open the album inside Dopamine and choose the "By Album" sort order

## Observed behavior

* Dopamine will order the Discs in the order: 1, 10, 11, 12, 13, 14, ..., 2, 3, 4, 5, 6, 7, 8 ,9.

## Desired behavior

* Dopamine should order the Discs in the order: 1, 2, 3, 4, 5, 6, 7, 8 ,9, 10, 11, 12, 13, 14, ....

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3866342/Dopamine.log)

**Comment by lushuyu** [comment]
It looks like dictionary order.
