### ISSUE TITLE
Back Arrow Key and Timing

### ISSUE THREAD

**Issue by chadfranklin47** [digimezzo/dopamine-windows#1055]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Hello again, I wasn't sure whether to put this in the feature request or the bug section as it isn't that serious, but when a user presses the back button in a song, it jumps back 15 seconds. This is UNLESS the song is not yet at the 15-second mark, which then the back button does nothing. I believe it would be better for the back button to return the song to the beginning when it is before the 15-second mark. Also, on the same topic, what do you think of adding an option to customize the interval in which the song skips by clicking the arrows? Maybe just a dropdown with intervals of 5 ranging from 5 - 30 seconds?

**Comment by digimezzo** [comment]
@chadfranklin47 I agree that it should skip to the beginning when it has not reached the 15 seconds mark. I have now fixed this. 
For the configurability, I'm planning this option for Dopamine 3.0. By the way, if you press CTRL+arrow, you skip by 5 seconds instead of 15.

**Comment by chadfranklin47** [comment]
Ok, that's good to know. Thanks for the update :)
