### ISSUE TITLE
bogus metadata reading from mp3s

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#106]
I grabbed some albums from CD back in the day (with iTunes 7.6... 8 years ago) and several of them show Unknown Artist / missing Artwork in Dopamine (the Title is mysteriously listed - but not in the Edit / Information window). Every media player shows the details, even Windows can read out the metadata correctly, even the Artwork as an icon. I refreshed the collection several times.

![missing](https://cloud.githubusercontent.com/assets/4146263/17622888/6709b918-609d-11e6-9580-401375ea46eb.JPG)

**Comment by digimezzo** [comment]
Would you mind sharing one of those mp3's? I'd like to test this out.

**Comment by kbalint** [comment]
Sure, please mail me in private.

**Comment by digimezzo** [comment]
The file's ID3v2 is corrupt. Some programs can read the tags, others can't. MP3Tag can't read them either: 
![mp3tag](https://cloud.githubusercontent.com/assets/11945339/17631012/6e6f8d20-60c2-11e6-9426-884c79312184.png)

TagLib#, which I use in Dopamine to read the tags, fails to read them. I'm afraid there is no better tagging library for .NET. So the only option is fixing the tags. You can easily do that in Windows Explorer by rating them, applying the change, and then unrate them again and applying the change. That will fix the corrupt ID3v2 frames in the MP3's. MP3tag sees them as valid, and Dopamine can also read them.

**Comment by kbalint** [comment]
Thanks for the checking! 
However it was auto-generated by iTunes - specifically it was added by " iTunes CDDB". In a test app loaded it up with [UltraID3lib](https://github.com/crowell/Linebeck/tree/master/ultraID3lib) without any exceptions, and I see all fields here (see attached).
Furthermore I've added TagLib# as well from NuGet (2.1.0) and it shows all tags without exception also :)

On a different note, [some say](http://stackoverflow.com/questions/19191269/exists-any-risk-of-corruption-when-deleting-id3v1-id3v2-tags-in-a-music-file) UltraID3lib is even faster than TagLib# for modifying mp3 tags.

![taglib](https://cloud.githubusercontent.com/assets/4146263/17632613/a99e0e60-60c9-11e6-8cae-be010ce51bac.JPG)
![capture](https://cloud.githubusercontent.com/assets/4146263/17632614/a9a8682e-60c9-11e6-9c39-c86abf23ec65.JPG)

**Comment by kbalint** [comment]
Thanks for checking - the files were generated by iTunes, so it is interesting. 
Anyway - I wrote a checkup console app, and I can confirm both UltraID3Lib and TagLib# fails on the original files (my deleted comment was on the modified file, sorry). However none of them raises an exception / reports an error, which is strange: just Artist / Title / Genre are String.Empty. Possibly this could be reported to the user?

**Comment by digimezzo** [comment]
Seems like impossible. There is no indication of possible corruption in the information I get back from taglib. Indeed, the tags just seem empty.
