### ISSUE TITLE
Dopamine doesn't remember window position

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#1080]
A user reports that, when Dopamine is positioned on a secondary display, at the next reboot, it appears on the primary display.

**Comment by xerta555** [comment]
> A user reports that, when Dopamine is positioned on a secondary display, at the next reboot, it appears on the primary display.

Hi, for me on 1909 it works fine, this type of issue is fixed most of time by creating a new Windows account.
Also, for exemple, the NVidia drivers installer when it reset the windows positions of opened softwares can fix it, unfortunatly i don't know exactly wich file(s)/folder(s) it delete.

**Comment by digimezzo** [comment]
@xerta555 It, indeed, works as expected. Dopamine makes sure to always be visible. If Dopamine is positioned on a secondary monitor, and that monitor is disconnected, Dopamine is shown on the main monitor after a restart.

The user just informed me that his secondary displays are shut down automatically by a power controller, as soon as the PC is shut down or goes into standby. So that explains why Dopamine behaves this way. This is a non-issue.

**Comment by xerta555** [comment]
@digimezzo It all makes sense :)
