### ISSUE TITLE
Changing Volume Icon

### ISSUE THREAD

**Issue by chadfranklin47** [digimezzo/dopamine-windows#1081]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Hello, I was just listening to music wondering why the volume was so low. I checked the Dopamine volume level in the bottom right and it was set to 50%. The problem is that at the moment there is no way to tell the approximate Dopamine volume without changing it. I propose removing the rightmost volume icon curve once the volume is below 66% volume, then the middle curve once below 33% volume, and the leftmost curve once at 0% volume.

![image](https://user-images.githubusercontent.com/37273511/71644032-03452f80-2c90-11ea-9e31-750781a6c53e.png)

**Comment by digimezzo** [comment]
That's a good idea. I'm planning this for Dopamine 3.0

**Comment by digimezzo** [comment]
This is fixed in Dopamine 3.0
