### ISSUE TITLE
System Notification/multimedia keys stopped working with new beta

### ISSUE THREAD

**Issue by wetfly** [digimezzo/dopamine-windows#1085]
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Home 1903
* Dopamine version: 2.0 Beta 2

## Reproduction steps

* Enable System Notification
* Press pause/play media key.

## Observed behavior

Media Keys do not function properly with the "Enable System Notification" setting enabled. When pause/play is pressed, the song plays (or pauses) for a split second before going back to the original state. With the "Enable default multimedia key support" setting enabled (not sure what this setting is but seems relevant) this happens much quicker, fast enough that I don't hear any change in the song, but I see the play/pause icon flicker.

With System Notification turned off, the media keys work fine (default multimedia key support doesn't affect this)

## Desired behavior

With System Notification enabled, pressing pause/play pauses/plays the song. This worked fine in the previous Beta.

**Comment by digimezzo** [comment]
@wetfly This is probably related to the fix for #775.

**Comment by digimezzo** [comment]
I found the issue. System notifications have their own media keys support. When using system notifications, Dopamine should disable its own media keys support. I'm fixing this for Beta 3 (to be released today or tomorrow).

**Comment by Chealer** [comment]
If you believe you are experiencing this on Dopamine 2.0.3 or later, see ticket #859 .
