### ISSUE TITLE
Add support for m3u8 playlists

### ISSUE THREAD

**Issue by ferdinandwinters** [digimezzo/dopamine-windows#1090]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Is it possible for you to add support for m3u8 playlists? I have a bunch of playlists and they are all in that format. I use the app a lot but only with the albums, for playlists I need to fall back to VLC.

Thank you so much for your hard work.

**Comment by ferdinandwinters** [comment]
Well I made a typo I think, damn.

**Comment by digimezzo** [comment]
@ferdinandwinters Could you attach such a m3u8 file, of send it to info@digimezzo.com?
Thanks!

**Comment by ferdinandwinters** [comment]
Sure thing, here you go. Even though it's like 10KB, GitHub wouldn't let me attach it unless it was in a container.

I think the only difference between a m3u and a m3u8 is the latter is UTF-8 encoded. So functionally there is no difference and I could simply just rename each file to drop the 8 off the end and they would work. It's all in plaintext, guess it just adds support for additional characters in track names.

[Is it New Wave_.zip](https://github.com/digimezzo/dopamine-windows/files/4050112/Is.it.New.Wave_.zip)

**Comment by digimezzo** [comment]
@ferdinandwinters Perfect, thanks! I'll quickly add support for m3u8. A new version should be available today or tomorrow.
