### ISSUE TITLE
Certain Ogg files won't play

### ISSUE THREAD

**Issue by chadfranklin47** [digimezzo/dopamine-windows#1094]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro Version 1903 build 18362.535
* Dopamine version: 2.0

## Reproduction steps

* Download and Unzip the attached file to get the Ogg files
* Import those Ogg files into dopamine
* Attempt to play said files from Dopamine

## Observed behavior

* Dopamine refuses to play the songs.

## Desired behavior

* Dopamine plays the songs as expected. (The files are labeled as OPUS, but I'm not sure whether they are actually OPUS in an ogg container or just ogg vorbis.) Dopamine is supposed to support both of those file types though.

## Log file

[Dopamine.log](https://github.com/digimezzo/dopamine-windows/files/4056397/Dopamine.log)

[Fkj & Tom Misch - Losing My Way (152kbit_Opus).zip](https://github.com/digimezzo/dopamine-windows/files/4056400/Fkj.Tom.Misch.-.Losing.My.Way.152kbit_Opus.zip)

**Comment by elosant** [comment]
I have the same issue with 2.0. After uninstalling 2.0 and reinstalling 1.5.9, I'm not able to see the ogg files in my collection. I end up having to delete the Roaming/Dopamine directory and reinstalling 1.5.9 again for it to work properly.

**Comment by digimezzo** [comment]
@chadfranklin47 and @elosant I tested the ogg files which are attached to this issue with the upcoming Dopamine 2.0.1, and I can confirm that they will work in Dopamine 2.0.1. I'll release it today.

**Comment by chadfranklin47** [comment]
Alright, thanks for the fast fix @digimezzo . Look forward to the update :)

**Comment by digimezzo** [comment]
@chadfranklin47 Dopamine 2.0.1 was just released. I'm closing this issue.

**Comment by chadfranklin47** [comment]
Thanks again @digimezzo , can confirm it works on my end.
