### ISSUE TITLE
Taskbar mini view refresh delay

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#110]
![delayed](https://cloud.githubusercontent.com/assets/4146263/17831240/be341d2c-66e3-11e6-9df6-044fb368b10e.jpg)

the track info is the currently playing (Turbonegro) but the mini view is for the last track (Iron and Wine). 
To reproduce: switch to mini player; minimize it to taskbar, press next on the taskbar preview. When restoring from the taskbar, the view will refresh.

**Comment by digimezzo** [comment]
That's correct, and is a limitation of Windows. It only updates the previews when the application is visible. That should change in the future, when I display the album art in the preview instead of letting Windows showing a windows preview.

**Comment by digimezzo** [comment]
This is standard windows behavior and cannot be fixed.
