### ISSUE TITLE
CANNOT LOGIN TO LAST.FM

### ISSUE THREAD

**Issue by otobongetti** [digimezzo/dopamine-windows#1110]
Cannot login to last.fm to scrobble tracks, dopamine always shows "Sign in failed"

Tried the last.fm app but i can't find a plugin on the internet for dopamine music player.

Really frustrating as I have hundreds of unscrobbled tracks.

**Comment by digimezzo** [comment]
@otobongetti Are you still having this issue? I can't reproduce it here.

**Comment by otobongetti** [comment]
Yes I am.

Otobong Etti

**Comment by otobongetti** [comment]
Ignore that reply. I logged out of all my other devices and tried again.
It's working now.

Thank you

Otobong Etti

**Comment by otobongetti** [comment]
So there's something I have a problem with.

My music library has a lot of songs, some of these songs have volumes too
loud, or too quiet.

I've tried an app called 'Mp3Gain' which is meant to normalise the
individual volumes of the tracks to a set value.

I've followed the instructions carefully on using this app, but this
doesn't seem to actually make all the songs have a similar loudness.

I've used iTunes & Windows Media Player in the past and they automatically
did a 'volume leveling' on my music library. I didn't need to go through
this replaygain stress.

So do you have any plans to add such a feature to Dopamine? It would be
really nice.

Thanks for reading.
