### ISSUE TITLE
[bug] after deleting a song from disk using Dopamine button - albums tab becomes empty

### ISSUE THREAD

**Issue by Owyn** [digimezzo/dopamine-windows#1115]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 v1903
* Dopamine version: 2.0.1

## Reproduction steps

* Step 1: go to "Albums" tab
* Step 2: delete any song from disk
* Step 3: see you now have 0 songs in albums shown

## Observed behavior

albums tab becomes empty after a song is deleted

## Desired behavior

deleting a song shouldn't empty the whole albums thing

## Log file

[Dopamine.log](https://github.com/digimezzo/dopamine-windows/files/4393717/Dopamine.log)

screens: 

step1: ![изображение](https://user-images.githubusercontent.com/1309656/77760438-65bb8b00-7047-11ea-8d0c-9fee09801107.png)

step2: 
![изображение](https://user-images.githubusercontent.com/1309656/77760460-6f44f300-7047-11ea-828f-fa305553ca44.png)

**Comment by digimezzo** [comment]
@Owyn Does this issue happen each time? I can't reproduce it here. Maybe I'm missing some steps?

**Comment by Owyn** [comment]
Yea, each time
Make sure it's "Albums" tab selected

**Comment by digimezzo** [comment]
@owyn Could you reproduce the problem once more, and then attach the new log file here again? I'd like to understand what is going on.

**Comment by Owyn** [comment]
Sorry, I uninstalled Dopamine months ago (see issue date) cuz it wasn't working as I was expecting it to and now using foobar2000 so I can't, you may close the issue if you'd like.
