### ISSUE TITLE
(Feature request) Sort by song adding time

### ISSUE THREAD

**Issue by chuwza** [digimezzo/dopamine-windows#1120]
First of all, thank you for your development work. Dopamine is currently the best local music player^_^

But, current dopamine is very difficult and slow to find newly added songs ... I can only search to confirm where the newly added songs are in the list ...

I think this is a very important and commonly used function for a local music player
(Most players such as win10 groove and plex have this function, and I can immediately see where my newly added music is)

**Comment by digimezzo** [comment]
@BlessWz Sorry for the late reply. There is an option "By date added" in all the screens.
In the songs screen, you'll have to add it as an extra column by right clicking on the songs grid and selecting "Date added" as a column.
