### ISSUE TITLE
PC goes to sleep thus stoping music

### ISSUE THREAD

**Issue by simonogru** [digimezzo/dopamine-windows#1129]
Otherwise its a perfect player but I think that preventing a PC from going into sleep mode is a must have in case of a music player. 
Im using Dopamine on Surface 3 and i want it to go to sleep in other cases, so changing the energy plan is not a solution for me.

**Comment by digimezzo** [comment]
Note to myself:

https://stackoverflow.com/questions/38282770/stop-screensaver-programmatically
