### ISSUE TITLE
Dopamine Linux?

### ISSUE THREAD

**Issue by onlycs** [digimezzo/dopamine-windows#1132]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x ] Feature request
</code></pre>

Is there a Dopamine Music Player for Linux? It is quite possibly the best player on Windows, and I would love for it to be available on Linux.
Thanks!

**Comment by johnnymatthews** [comment]
There's an [Electron version available](https://github.com/digimezzo/dopamine), but there are no install instructions unfortunately.

**Comment by digimezzo** [comment]
The electron version does nothing useful yet. That is why there are no install instructions.
I'm planning to continue the work on the electron version very soon.

**Comment by johnnymatthews** [comment]
Good to hear @digimezzo. Feel free to tag me as a reviewer when there's more to work with! I'd be happy to help out.

**Comment by onlycs** [comment]
So when it comes out, how would you compile it?(I am very new to Linux) I have been trying to make it work on Wine and Mono (converts C# Source) but it never works.

**Comment by digimezzo** [comment]
@dragonBall561 There will be .deb and .rpm packages. That will cover all debian and redhat based Linux distros. There will also be a AppImage package and it will be published to the snap store and arch user repository.

**Comment by onlycs** [comment]
Cool!

**Comment by onlycs** [comment]
Ok so I will close this now

**Comment by dragonBall561** [comment]
How do I close this now?

**Comment by dragonBall561** [comment]
Ok. Found the button
