### ISSUE TITLE
Lack of bit-perfect playback and lowering quality through resampling.

### ISSUE THREAD

**Issue by EugenyN** [digimezzo/dopamine-windows#1152]
This player has a wonderful interface that displays well on 4k, but this player is not suitable for playing high-resolution audio files. Resampling to a lower sample rate occurs before playback. The bitrate of the track is also reduced. 

As a result, if we have 32 bit and 88200 Hz audio file, its quality decreases to 48000 Hz 16 bit before playback on the device. And we can’t reach the bit perfect playback. I attached a screenshot:

![dopamine](https://user-images.githubusercontent.com/7301351/85225987-8e041d00-b3dd-11ea-96e0-eb28f7fd9c0d.png)

**Comment by FrozenCoder1** [comment]
It's True
