### ISSUE TITLE
Song stuttering when changing artists or changing to currently playing screen

### ISSUE THREAD

**Issue by curtismbeard** [digimezzo/dopamine-windows#117]
When I'm playing a song or album and I'm in the artists view, if I start to select another artist, the song skips.

This also happens if I click the current songs artwork to go to the now playing screen and switch between the now playing list and the showcase.  Going back and forth there seems to skip every time.

I reported something similar via neowin and it was tracked down to artwork drawing.  Just wondering if this is an issue still or wasn't fixed yet.  Thanks.  Let me know if you need more details.

**Comment by digimezzo** [comment]
Which version are you using? I hoped to have fixed that issue a long time ago. I haven't been able to reproduce it since fixing the issue.
If the issue remains, could you play a bit with the audio latency setting in Dopamine? Usually, a higher latency helps.

**Comment by curtismbeard** [comment]
Using Version 1.1 (Build 681) Preview.  I'll play with the latency and report back, thanks.

**Comment by curtismbeard** [comment]
I increased the latency to 300 ms which still had the issue.  Then increased it 500 ms and still the same issue.  However, I closed the application and restarted it (leaving the 500 ms latency) and that seems to have made it work with out a stutter now. 

I would say perhaps it is just limited to my setup now and seems to be ok.  Thanks for the response about changing the latency. 

Closing this issue then.

**Comment by digimezzo** [comment]
BY the way, when you change the latency, it is only applied when the next song starts playing, or when you start a new song yourself. It is not applied to the currently playing song.
Also, it is indeed audio device dependent. Some audio devices allow a lower latency, others require a higher latency. 500 ms is already quite high. If the issue pops up again, feel free to re-open this issue.
