### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#119]
Hello, first I want to thank you for an amazing app. But I have a problem with using this program. When I want to show the equalizer or go to the mini player, so the application crashes. I think it was a mistake for me, but it seems not. Dopamine I tried to run on another computer with both Windows 10 and Win 7 and 8, but still falls the same application error. Thanks a lot.

**Comment by digimezzo** [comment]
Could you send me the logfile? You can find it by pressing Ctrl+L when Dopamine is open.
Also, is it a clean install, upgrade or stand alone version?

**Comment by ghost** [comment]
I tried as a portable version and the installation itself.
Here is the logfile: [`Dopamine logfile`](https://1drv.ms/u/s!AsQm4isQSZWotW5WXllGXKi8dwH_)

**Comment by ghost** [comment]
I figured it out. Somehow it has to do with language localization system. When you set the default language to English so the application works, but when I set my language in the Czech language and application crashes.

**Comment by digimezzo** [comment]
Could you reproduce the error once more? Once it crashed, could you get the Settings.xml file which is in folder %appdata%\Dopamine and send it to me?

Do you mean the Windows language or the language in Dopamine?

It seems to crash when fetching the volume from the settings file. The conversion from the value in the Settings.xml, to a number seems to fail. I thought I had that figured out, but there seems to still be cases where it fails.

**Comment by ghost** [comment]
Here is [settings.xml](https://1drv.ms/u/s!AsQm4isQSZWotW8G52MSJHd8wBJ3)
screen: [https://vid.me/3DQt](https://vid.me/3DQt)

**Comment by digimezzo** [comment]
Thanks. I have 1 more request. Could you start Dopamine, then delete the logfile, then reproduce the crash like in the video by opening the equalizer and then send me that log?

**Comment by ghost** [comment]
[https://1drv.ms/u/s!AsQm4isQSZWotXAsEK16O8hBA_vg](https://1drv.ms/u/s!AsQm4isQSZWotXAsEK16O8hBA_vg)

**Comment by digimezzo** [comment]
Thanks! I've installed a Czech Windows 10 in a VM tonight, as I couldn't reproduce the crash in my US Windows 10 set to Czech language. However I can still not reproduce it. I guess there is some regional setting I'm missing. Can you send a screenshot of the number formats on your system? (like below)

![regional](https://cloud.githubusercontent.com/assets/11945339/18030442/6f740584-6cb6-11e6-8c35-8cc5293abfb3.png)

**Comment by digimezzo** [comment]
As I can't reproduce it here, we'll have to try the following:

I created 2 dll's which contain a fix for this issue: Dopamine.Core.dll and Dopamine.Common.dll. You can find them here: [Dropbox](https://www.dropbox.com/sh/1p8v22sf0bqbldo/AABNIFK60-hmmMocy5VLkq3Ia?dl=0)

Could you replace the dll's in your Dopamine (installed of portable, doesn't matter) by those, and try to reproduce the issue?

Thanks!

**Comment by ghost** [comment]
So I replaced the DLL and it works. But it appeared another error when I want to add more folders to the collection, so it throws error [https://vid.me/VfoY](https://vid.me/VfoY)

![screenshot_20160828110218](https://cloud.githubusercontent.com/assets/5471789/18032793/d6735716-6d11-11e6-9f70-02244baf63f8.png)

**Comment by ghost** [comment]
LOG: [https://1drv.ms/u/s!AsQm4isQSZWotXEWCyHNpsbykMip](https://1drv.ms/u/s!AsQm4isQSZWotXEWCyHNpsbykMip)

**Comment by digimezzo** [comment]
Thanks a lot for testing it out. I'm committing the fix. I've opened a separate issue #120 for the collection folder problem, as it is caused by a totally different issue.
