### ISSUE TITLE
New Icon for app ( Fluent Based )

### ISSUE THREAD

**Issue by prakharb5** [digimezzo/dopamine-windows#1197]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

With the arrival of new windows Fluent design, I suggest that the app icon should be updated to match the design.

I had saw a good-looking icon on the web. I will attach it here.

![icons8-headphones-96](https://user-images.githubusercontent.com/51435948/93011811-59a49500-f5b7-11ea-8a10-486215562e93.png)

What do you think about it?

( I am neither the designer nor the owner of this icon. This icon is here - https://icons8.com/icon/set/headphone/fluent )

**Comment by digimezzo** [comment]
@Cyberdroid1 Thanks for looking into this. A fluent icon has already been designed for Dopamine 3. You can have a look at it in the Dopamine 3 repository: https://github.com/digimezzo/dopamine

**Comment by prakharb5** [comment]
Ohk, thanks for letting me know. When will the version with this icon be released?

**Comment by prakharb5** [comment]
Will the icons for media files be also updated?

![image](https://user-images.githubusercontent.com/51435948/93048011-7aceb980-f67b-11ea-858d-9b200840a526.png)

Will these icons be updated too?

**Comment by digimezzo** [comment]
@Cyberdroid1 Sorry, I lost track of this issue. Yes, the media icons will also be updated.

**Comment by digimezzo** [comment]
Done in Dopamine 3.0
