### ISSUE TITLE
[Feature Request] Play Count

### ISSUE THREAD

**Issue by adamhl8** [digimezzo/dopamine-windows#1203]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

After googling this, it seems like the play count for songs used to be a feature in an old version of Dopamine but as far as I can tell the feature no longer exists (or I'm possibly blind and I'm missing something obvious).

Anyway, if this is not already a feature, I'd love a column in the Songs menu for play count and to be able to sort by play count.

**Comment by digimezzo** [comment]
It's still there, but you have to add the column:

![image](https://user-images.githubusercontent.com/11945339/94338083-ef94e280-ffef-11ea-9378-27a6d6c15102.png)

![image](https://user-images.githubusercontent.com/11945339/94338091-fa4f7780-ffef-11ea-9ed0-7869f451f6dc.png)

**Comment by adamhl8** [comment]
Ah, never thought to right click there. Thanks!
