### ISSUE TITLE
Notification area: put emphasis on track name

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#121]
Reported by a user:

The notification gives emphasis to the artist, not the track name… when you activate the notifications, you want to see the name of the song playing, not the artist… so, making the artist’s name smaller, and the song’s name bigger seems better in my opinion. it’s a pain to my eyes to read such a small text font to discover the song’s name, having such a big font just for the artists name right below.

**Comment by digimezzo** [comment]
Also changed this on other screens.

**Comment by curtismbeard** [comment]
Was this included in the latest build of 1.2 (preview build 763) for the notification?  It seems like it should be, but when I switch tracks and see the notification, the track name is still smaller than the artist name.  Any ideas or am I just missing the point of the change (from looking at the commit was the notification view updated at Dopamine.Common/Services/Notification/NotificationWindow.xaml [if that is even correct])?

**Comment by digimezzo** [comment]
You're right, I missed it for the Notification window. The change was only applied for the Playback controls of the notification area icon. I'm re-opening this issue. It'll be fixed in the next preview.
