### ISSUE TITLE
You shouldn't need to install SDK

### ISSUE THREAD

**Issue by jaigak** [digimezzo/dopamine-windows#1211]
Windows.winmd is located under System32\WinMetadata so installing the SDK shouldn't be needed. The SDK splits the files into separate components but you don't need them to run. Also is there a plan to provide an installer so I can run without compilation or SDK?

**Comment by ShankarBUS** [comment]
You don't need to install the Windows 10 SDK to run the app. It's only required to build the app.

You can remove the **"*.winmd"** reference and add a package reference to `Microsoft.Windows.SDK.Contracts` to build the app.

Did I understand your point wrong?

Am I missing anything?

> Also is there a plan to provide an installer so I can run without compilation or SDK?

The author do provide an installer on their website.

[Here you go](https://www.digimezzo.com/content/software/dopamine/)

**Comment by jaigak** [comment]
@ShankarBUS If there's an installer available, why is it not linked on the home page? How am I supposed to know where to download the installer?

**Comment by ShankarBUS** [comment]
It's there but not noticeable at glance https://github.com/digimezzo/dopamine-windows/blob/master/README.md#L7

> More information and downloads are available at https://www.digimezzo.com.
