### ISSUE TITLE
Dopamine does not let Windows 10 go to sleep

### ISSUE THREAD

**Issue by gjclemens** [digimezzo/dopamine-windows#1227]
Dopamine should stop holding the audio device driver when music is paused so that the computer can go to sleep. No other apps running, music paused for hours, computer will still not go to sleep because Dopamine is holding it. This has been an issue for me since 2.0.1, I had previously seen a case tracking the issue on here so I figured it would be addressed, I don't see that case anymore but the issue hasn't gone away for me.

Screenshot attached.
![image](https://user-images.githubusercontent.com/72425808/95157744-c7735500-074e-11eb-8fa0-d15a656c52a7.png)

**Comment by digimezzo** [comment]
Fixed in 0f475af2971ab9fc991bef38cc8e08dfb7046341
