### ISSUE TITLE
Feature request: Sort albums by most recently played

### ISSUE THREAD

**Issue by Bearlify** [digimezzo/dopamine-windows#1278]
My library consists of some 1700+ albums. Obviously, most of the time I am only listening to a small portion of those. It would be nice to be able to order them based on most recently played, to keep the most 'relevant' music at the top!

**Comment by Tovape** [comment]
I wrote a pull for that, check my fork and compile it

**Comment by oaisjdgoijdsoiagj** [comment]
How would I compile?

**Comment by Tovape** [comment]
Oh nvm, my fork added sorting by date added, not by relevancy, to compile read the instructions, I used visual studio code. If you want I can drop a portable pre compiled version
