### ISSUE TITLE
Responding to media buttons

### ISSUE THREAD

**Issue by Tovape** [digimezzo/dopamine-windows#1282]
Would love to play/stop music using bluetooth headphones
👍

**Comment by Faywool** [comment]
My Bluetooth headphone can do that, play/pause, pre and next music.

**Comment by Tovape** [comment]
What headphones are you using? I have the Sony CH700N, maybe I'm forgetting something

**Comment by Faywool** [comment]
Sony WH-1000XM 2.
If other player software is available, Dopamine should be the same. 
The keys of the headphone are just equivalent to the media keys on the keyboard

**Comment by Tovape** [comment]
Nvm I found out why, I had this disabled, my bad 
![image](https://user-images.githubusercontent.com/49490716/112519018-3e9eb300-8d9a-11eb-9463-54841515cddf.png)

**Comment by Faywool** [comment]
Congratulations.
Please close this issue by the way.
