### ISSUE TITLE
Cannot compile, getting a bunch of "tag does not exist in XML namespace" errors

### ISSUE THREAD

**Issue by Tovape** [digimezzo/dopamine-windows#1400]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ x ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10
* Dopamine version: 2.0.9

## Reproduction steps
* Step 1
Installed Visual Studio 2019
* Step 2
Changed Project NET Framework to 4.5
Added the windows.winmd
* Step 3
Built Solution, got the errors

All of them are like:
The name "ProgressRing" does not exist in the namespace "clr-namespace:Digimezzo.Foundation.WPF.Controls;assembly=Digimezzo.Foundation.WPF"

The type or namespace name 'Digimezzo' could not be found (are you missing a using directive or an assembly reference?)

**Comment by digimezzo** [comment]
Foundation uses .NET 4.7.2. So the .NET version in Dopamine should be set to 4.7.2 or higher. Why did you change it to 4.5?

**Comment by Tovape** [comment]
> Foundation uses .NET 4.7.2. So the .NET version in Dopamine should be set to 4.7.2 or higher. Why did you change it to 4.5?

I read the compilation readme notes and I read it had to be set at 4.5. Thanks for replying btw, I will change it in a few hours and see if all goes well

**Comment by Tovape** [comment]
Okay it works now, thanks so much
