### ISSUE TITLE
Windows 11 does not remember Dopamine's size & position

### ISSUE THREAD

**Issue by Pressed250** [digimezzo/dopamine-windows#1404]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 11 v10.0.022621 Build 22621
* Dopamine version: 3.0.0-preview.19

## Reproduction steps

* Step 1: open Dopamine
* Step 2: resize & position window
* Step 3: close Dopamine
* Step 4: open Dopamine ... starts in 'default' size & position

**Comment by digimezzo** [comment]
Not reproducible
