### ISSUE TITLE
Unable to Drag & Drop Files into Dopamine

### ISSUE THREAD

**Issue by kimuk1** [digimezzo/dopamine-windows#1415]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 22H2
* Dopamine version: Dopamine version: 3 preview 19

## Reproduction steps

* Open Dopamine
* Open a Windows Directory containing .MP3 or .AAC or .FLAC
* Try to drag files into Dopamine (unable to complete)

## Observed behavior

Dopamine highlights that the files are to be copied, however does not copy or add the files

## Desired behavior

Drag and drop files into Dopamine to be played.  Alternatively windows shell integration would be great

## Log file

https://github.com/digimezzo/dopamine-windows/assets/24640054/19ae4248-9feb-4c91-8405-c1f42558f614

N/A

**Comment by digimezzo** [comment]
This seems to be a Dopamine 3 issue which has since been fixed.
