### ISSUE TITLE
Bind space to pause/play

### ISSUE THREAD

**Issue by Aemony** [digimezzo/dopamine-windows#142]
Space is often a more easily accessible keyboard shortcut than the actual media keys, so I think this would be a good enhancement to the player. This is especially useful if the user wants to quickly pause/play the track by clicking on the Dopamine window and hitting space, a habit taught by media players as far back as Winamp.

**Comment by digimezzo** [comment]
I've tried this in the past, but there was a conflict with the search window, when the search window is selected. The space is then typed in the search. I'm willing to give this another go though. I'll need to find out how to differentiate between "space" pressed in the context of a search, or rather to pause/unpause.

**Comment by gjhwssg** [comment]
@digimezzo  When the search window is selected,do you want to respond to pause/unpause or type a space?

**Comment by digimezzo** [comment]
@gjhwssg That's the hard part. Pressing space in the search window should type a "space", as you can search for multiple words. But then, if the search field is accidentally selected, and the user wishes to play/pause by pressing space, play or pause won't be triggered. This makes the space key not an ideal candidate for play/Pause action. I just tested a few applications:
- Winamp: doesn't react on space
- Foobar2000: doesn't react on space
- MusicBee: space automatically triggers a search
- Groove: doesn't react on space

I'd, honestly, rather have that keyboard presses automatically focus the search field, and triggers a search (like MusicBee), than controlling audio. That would allow a user to quickly trigger a search without having to select the search field first.

**Comment by Aemony** [comment]
> I'd, honestly, rather have that keyboard presses automatically focus the search field, and triggers a search (like MusicBee), than controlling audio. That would allow a user to quickly trigger a search without having to select the search field first.

Hmm... Would it be possible to add an IF statement that took into account how long ago another key was pressed? I mean, how often does a search query begin with a space character? It might be possible to design a workaround that serves both purposes, with a small possibility of confusion for a few users.

So _only_ treat space as a character if another key have been pressed within the last five seconds, or so?

**Comment by digimezzo** [comment]
@Idearum Something like that might work. I'll have a look at it for v1.2.

**Comment by digimezzo** [comment]
I've spent a few hours trying to get this right, but the conflicts with the search box are too complex. When the search box has been activated at least once, both the search box and the main window react to space. Filtering out key presses would have to happen in both locations, and is not even reliable. This issue won't be fixed.

**Comment by Khidreal** [comment]
I have nothing to do with this thread, it just showed up on my email because I'm subscribed, but the time you take to grab your mouse, click the window and hit space is more or less the same time you need to click Fn + Play/Pause or whatever shortcuts your computer has to use media keys, and we're talking about being on the desktop, if you are for example inside a game, using the media keys on your computer is way faster...

**Comment by digimezzo** [comment]
This feature is being requested a lot. I decided to implement it as such:

- A search cannot start by a space: when pressing space when the search box is empty, space toggles play/Pause
- When there is already text in the search box, space types a space in the search
