### ISSUE TITLE
saving playback position

### ISSUE THREAD

**Issue by neomag** [digimezzo/dopamine-windows#1422]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

Dopamine does not save playback position in playlist
This creates inconvenience when listening audiobooks

how to reproduce:
select not the first track in the playlist
shut down dopamine
open - playback will start from the first track

**Comment by digimezzo** [comment]
This seems to be a Dopamine 3 issue, which has since been fixed.
