### ISSUE TITLE
Digimezzo site has been hijacked by a random sports TV site

### ISSUE THREAD

**Issue by Danielshmaniel** [digimezzo/dopamine-windows#1425]
The site where Dopamine is downloaded from, digimezzo.com, has changed into a random website irrelevant to Dopamine. Are there any alternative download links?

**Comment by digimezzo** [comment]
@Danielshmaniel I gave up the digimezzo.com domain for financial reasons. It became too costly. The website is now hosted on GitHub here: https://digimezzo.github.io/site/

**Comment by Danielshmaniel** [comment]
@digimezzo Got it. You might want to replace the old digimezzo.com link with this new github site in the Read-me so people don't confuse the two.

**Comment by digimezzo** [comment]
@Danielshmaniel I just updated the readme. Thanks for pointing that out.
