### ISSUE TITLE
Using WinUI 3 instead of WPF

### ISSUE THREAD

**Issue by frav1982real** [digimezzo/dopamine-windows#1426]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

I think Dopamine can be rewritten using WinUI 3 instead of WPF.
Reasons for choosing WinUI 3:

- the UX/UI of WinUI 3 is more aesthetically appealing
- WinUI 3 is as light as WPF
- it is easily integrated into C#

**Comment by digimezzo** [comment]
@FrankVan1982 Dopamine 2 has entered maintenance mode. Dopamine 3 is now in active development. So there are no plans to change Dopamine 2's frameworks. But feel free to fork it.
