### ISSUE TITLE
when a folder and one of its subfolders are added to collection but only the subfolder is checked, the collection becomes empty after refreshing

### ISSUE THREAD

**Issue by mah-qurashy** [digimezzo/dopamine-windows#144]
![capture](https://cloud.githubusercontent.com/assets/20822445/18297803/e6ea7cf6-74b3-11e6-9470-7f4babbf5e0f.PNG)

**Comment by digimezzo** [comment]
Confirmed. Currently, tracks are mapped to only 1 folder: the first folder that added the track to the collection. Taht causes this bug.

To fix this, and extra database table will be needed: FolderTracks. The only purpose of this table is to allow N to N relations between Folders and Tracks by mapping FolderIDs and TrackIDs.

In table Tracks, remove the column FolderID.

Upgrade:

Make sure to create and entry in table FolderTracks for each FolderID in Tracks before removing the FolderID column.
