### ISSUE TITLE
MSI installer always installs in Program Files (x86)

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#155]
The MSI installer always installs in "Program Files (x86)" whether or not you choose "Program Files (x86)" or "Program Files" because the MSI installer is a 32 bit installer. Windows Installer doesn't allow a 32 bit installer to write files in "Program Files". 

For other directories: if you configure a directory which is none of the "Program Files" directories, it does install it there.

The only solution for the "Program Files" problem, seems to be to create 2 installers: 1 for 32 bit systems and 1 for 64 bit systems. 

Problems when doing that:
1. Packager needs to be updated to create and upload 2 packages
2. Updater needs to detect user's architecture and download correct MSI package

**Updater**

It is not possible to know which installer a user used on his system by checking the install directory or architecture of the OS.

Possible workaround: add a Installer_architecture.txt file to the installation directory. This file could contain a switch Is64Bits=True/False that would be set when packaging. The updater could then read this file and decide which package to download.

**Comment by Keith94** [comment]
Why not build the setup as an EXE rather than MSI? Just wondering if there's any reasons to prefer MSI. I mean, you could have a pretty icon embedded in an EXE, so that's one (cosmetic only) advantage.

**Comment by digimezzo** [comment]
I hate MSI. It's complex and causes a lot of issues, especially missing files on some user's computers.
What which installer would you recommend? My requirements:

- Adding of an icon to Add/remove programs
- Copying of files
- Adding of registry entries
- Adding of shortcuts

**Comment by Keith94** [comment]
Well, if you take a look at something like [foobar2000](http://www.foobar2000.org/download)'s .exe installer, it should have basically everything you want, including normal/portable installation options and all the requirements you listed. Can you use something such as that?

**Comment by digimezzo** [comment]
@Keith94 Yeah, that's great and all. But looking at the installer, doesn't tell me how it is built.

**Comment by digimezzo** [comment]
Won't waste more time on this issue. It's just cosmetic. In time, when 32 bit computers will be gone, this won't even be an issue anymore.
