### ISSUE TITLE
Add option to download missing album art from Last.fm

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#161]
Also add an option to embed album art in the audio files (maybe a maximum size option too?).

**Comment by ecdesa** [comment]
actually i prefer if you download the cover from itunes. using the album page small picture and changing its url from 170*170 to 600*600.

**Comment by digimezzo** [comment]
@mohamadnorouzi20 I'm not sure what you mean. Could you explain more?

**Comment by ecdesa** [comment]
@digimezzo You can download album art from itunes website . (it's not official though)
in every album page there is a small album art.if you change the name of file in the album art url from cover170x170 to cover600x600 you can download the album art from itunes. i think there are 400x400 and 1200x1200 sizes too.
