### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Khidreal** [digimezzo/dopamine-windows#166]
can I put feedback here? or it should be by email?
anyway, I think that dopamine is heading towards "lots of features" mindset and recent previews have added things that are wanted, but not needed. I started to use dopamine because of it's simple interface, a player that goes straight to the point; but recent previews, introducing each time more wanted features instead of needed is really starting to make me start searching for simpler alternatives. I feel Dopamine is too much bloated and my love by it is starting to decrease. I love earlier versions of dopamine, specially versions 1.1 4xx and 5xx, but since then I just saw dopamine having each time more wanted features. there are a couple of things I don't agree with and I don't know how can they be that useful or spare a considerable amount of time to users:
- size of the collection (does it costs that much opening your music folder and click properties?)
- I would never put artists, genres, albums and songs separated. maybe on early stages but than joining them into 1 single page would be a top priority
- dopamine aligned to left feels I'm reading a book and because it's aligned left, for example I can't activate everything on the columns menu or I lose half the word
- Cloud is associated to internet (cloud storage, search things in the cloud, etc. > internet) and what shows on that page is nothing more than a secondary now playing screen. you already have 2 (click the song on the bottom left) why you need that one? even if it acted as a playlist... but you need to click on every single track to make them play
- the background on the now playing screen makes the default size covers (500x500) become awful: unfocused, pixelated. you need at least a 1000x1000 cover to make it look (almost) as it should on a 1366x766 screen
- support for online search: totally a wanted feature, not needed or essential, if not say useless. to start with, all songs need the metadata "Artist name", meaning: songs saying "UNknown artist" won't be able to search 
- last.fm scrobbling can be used to add ID3 metadata to songs. any song you buy comes with the needed ID3: song name, artist and cover. some of them even come with year, genre and even BPM. besides, not everybody uses last.fm; most of people use Soundcloud or Spotify. last-fm is nice for discovering songs though, but just another wanted feature.

well, that's my feedback, sorry if I'm too ruthless or something, I am just like that while speaking.
maybe it's just about time to stop complaining and send feedbacks that a company will just put on a can and throw it into a river, and build my own music player.

**Comment by digimezzo** [comment]
I'd like to refer you to paragraph **Why wasn’t my suggestion accepted?** in the [Dopamine F.A.Q](http://www.digimezzo.com/software/dopamine-f-a-q/).
