### ISSUE TITLE
Last.fm login password box conflicts with volume control

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#175]
A user reported that signin failed (**error 403, forbidden**) when using a password which contains the character: ^.

These are the requirements of Last.fm concerning passwords:

> Your password is not strong enough. New passwords must:
> Be at least six characters long
> Contain one or more numbers
> Include at least one of the following special characters: !"#$%&'()*+,-./:;<=>?@[]^_`{|}~, or a space 

Let's try to find out why sign in fails when using ^ in the password. It might be caused by the routine which generates the secret. When the generated secret is incorrect, sign in fails with **error 403, forbidden**.

**Comment by digimezzo** [comment]
This doesn't seem to be an issue. Signing in using a passwords which contains ^ works fine. Not sure what was going on here, but this issue is closed because it is not reproducible.

**Comment by The-Choo-Choo-Shoe** [comment]
This is an issue for me in 1.5.14, I can't use + \ ? when typing last.fm password, I had to copy paste it from another text field.

I use Nordic keyboard layout, Windows 10 1803.

I don't know which update this stopped working but it has worked in the past.

**Comment by digimezzo** [comment]
@The-Choo-Choo-Shoe ? and \ seem to work here. + and - don't. Their mapping to volume up and down is interfering it seems. I don't yet understand why it doesn't interfere when typing + and - in the username box though. I've reopened the issue for further investigation. Thanks for reporting this.

**Comment by The-Choo-Choo-Shoe** [comment]
@digimezzo Ah, that's probably why then, + \ ? is on the same key for me so when + doesn't work the other ones don't work either.
