### ISSUE TITLE
Disable now playing items and add option to choose default now playing screen

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#191]
User request:

Can we have an option to make one of the views like Showcase the default when switching to the Now Playing screen, and be able to disable unwanted options from view (like lyrics).

**Comment by mah-qurashy** [comment]
I've been thinking that now playing should be added as a tab in top, containing playlist, lyrics, artist info and showcase and only showcase would hide to top menu.
then we can get to choose where clicking on the bottom left album art actually leads to, that we would have all the options on a tab, but the album cover is a short way to go to one of them.

**Comment by digimezzo** [comment]
The last user "Now playing" screen is now remembered. I don't see the need to add extra clutter to choose  a default now playing screen. Issue closed.
