### ISSUE TITLE
Cannot be closed via setup.msi

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#197]
TrayIcon and taskicon has disappeared but process is alive, and the setup will wait for application exit forever.

**Comment by digimezzo** [comment]
I'll need more details about the circumstances in which this issue occurred. I can't reproduce it here.

**Comment by Magentaize** [comment]
Ummm,Dopamine must is in playing some tracks...
BTW,if choose the "Repair" button in setup.msi,that also cannot be closed.Maybe the background thread of CSCore is still running.

**Comment by digimezzo** [comment]
I just tried out the repair option, and Dopamine was successfully closed by the msi installer. Could the process be locked by an anti virus on your computer?

**Comment by Magentaize** [comment]
I have no anti virus,but...maybe that is a special circumstance on my system.Sorry for disturbing you.

**Comment by digimezzo** [comment]
No problem. If you find more details about this, feel free to add it to this issue.

**Comment by Magentaize** [comment]
Yep, I make Dopamine is playing some tracks and open the msi setup choosing 'closing the applications and attempt to restart them', the icon in taskbar has disappeared but the process is still running.
![default](https://cloud.githubusercontent.com/assets/11793304/20647330/ed710fca-b4d4-11e6-913f-970e8e3f77fa.png)
So I attach to it.
![default](https://cloud.githubusercontent.com/assets/11793304/20647327/d84e3154-b4d4-11e6-8ff0-f795f52c494f.png)
The `CSCore.PlayBackProcess` is running.

And my solution is below:
This Windows Installer Dialog named **MsiRMFilesInUse** which located in **WixUI_Advanced.wxs**, and the `RadioButton` has a return value `AppsShutdownOption = "All"` if I choose the first one.The button's default command is to use Restart Manager to do other things but I can bind a custom `Published Event` which is Execute custom action — “taskkill.exe -im Dopamine.exe -f"

**Comment by digimezzo** [comment]
Thanks for this info! I think I fixed the issue in commit 969f84ccf133cb47816f4d3cd1675a522ef72a2c. I'll publish this with the next preview.
