### ISSUE TITLE
Shuffle all is confusing

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#218]
The position of the shuffle all button confuses users. E.g. in the playlists screen, there is a Shuffle all button. Users expect this button to shuffle only the songs in the playlist.

Conclusion: find another position for this button.

**Comment by mah-qurashy** [comment]
maybe if you click this number it shuffles whatever it's, and add a little shuffle icon to it
![capture](https://cloud.githubusercontent.com/assets/20822445/20647167/d2c40324-b495-11e6-8c5c-299c64243677.PNG)
