### ISSUE TITLE
Add blur effect to analyzer like ZUNE

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#222]
much beautiful

**Comment by digimezzo** [comment]
I'm afraid I have no idea how to do this at this point.

**Comment by Magentaize** [comment]
Ah, my friend has a solution about this and I'll try to add the effect by myself.
Ref [https://github.com/higankanshi/xZune.Visualizer](https://github.com/higankanshi/xZune.Visualizer)

**Comment by digimezzo** [comment]
Cool! I'm curious to see the result.

**Comment by Magentaize** [comment]
![20170324212736](https://cloud.githubusercontent.com/assets/11793304/24294253/1abdfc26-10d9-11e7-9597-7ff9115161df.png)
How about this style?It has a bigger spectrum and softer animation like Zune but I must minutely adjustment various.

**Comment by digimezzo** [comment]
I like it! Is this a mockup or did you implement it?

**Comment by Magentaize** [comment]
Ahmm, I implement it but the code is mess and I have to do more on it.
Honestly speaking, the blur effect takes much more CPU almost 10%, I'm considering to implement it with shader.
