### ISSUE TITLE
Can we reliably detect that we're running on "N" editions of Windows?

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#223]
The "N" editions of Windows are exhausting. I'm getting multiple reports that audio files don't work in Dopamine. Mostly this is due to "N" editions of Windows which don't have Windows Media Player, Internet Explorer and Media Foundation installed. Detecting that a user is running such version is complicated, because the user usually doesn't know himself/herself what he/she is using.

Can we detect this with some piece of code, and maybe warn the user with a pop up?

**Comment by Magentaize** [comment]
More info?Dopamine works well in my Windows8.1 with latest updates and also works well after upgraded to Windows 10.
So do my friends.

**Comment by digimezzo** [comment]
@PeoLeser In the European Union, Microsoft was forced to release a version of Windows without Media Player and related feaures. See info [http://winsupersite.com/windows-10/what-are-windows-10-n-and-kn-editions](here).

These versions of Windows don't have Media player and Media Foundation, and are called "N edition". Dopamine relies on Media Foundation to play sound. So it fails to open media files on "N" editions of Windows.

Fixing that issue on a "N" edition, consists of installing the Media Feature Pack. Example, for Windows 10 N and KN: [https://www.microsoft.com/en-us/download/details.aspx?id=48231](Media Feature Pack for N and KN versions of Windows 10).

The problem is, that users have no idea what these editions are, and even less, that they are usign such edition. So they just complain that Dopamine doesn't work.

**Comment by Magentaize** [comment]
I have find some info in MSDN. XD
For Windows Server : dism /online /get-featureInfo /FeatureName:ServerMediaFoundation
For Windows : dism /online /get-featureInfo /FeatureName:WindowsMediaPlayer

And DISM provides series of native API: [Link](https://msdn.microsoft.com/en-us/library/windows/desktop/hh824735(v=vs.85).aspx)

**Comment by digimezzo** [comment]
Thanks. But I've done something different. In commit 39cf25063eae3918f470f8b2108f2e05c6a87a54. I added a small test audio file (which I know works well in Dopamine), which is played silently at every start of Dopamine. If it fails, the user is notified what could have gone wrong. The user also gets information of N versions of Windows.

**Comment by Magentaize** [comment]
Well, I did not realize this operation needs elevation so it cannot be applied.

**Comment by digimezzo** [comment]
Indeed, I noticed that too. That's why I decided to apply the workaround with the test file. At least the user now gets a warning before Dopamine starts. That'll prevent lots of confusing e-mails.

**Comment by digimezzo** [comment]
The check that I added, causes Dopamine to fail to load on some computers that don't have Windows N edition. I'll probably have to remove that check.

**Comment by kbalint** [comment]
what about checking for %windir%\system32\mf.dll or \mfplat.dll? I guess these have the entry points for all Media Foundation stuff.

**Comment by Magentaize** [comment]
@kbalint That's right, but we cannot get the KeyToken in GAC.

**Comment by Magentaize** [comment]
@kbalint I'm wrong, although mf.dll is located in GAC, it also be linked to system32. @digimezzo  So we can use `File.Exist` to detect N version (it actually not exists in N).

**Comment by digimezzo** [comment]
@PeoLeser and @kbalint Nice find! I'll implement this check.
Note to myself: Environment.SystemDirectory should allow me to get the location of system32.

**Comment by digimezzo** [comment]
Fixed in 6de40bd44d9b12a25ecf02a087a302360c6a0290 and b0cece09feb5198c3a8fdb251f5a26547f6b856d

**Comment by kbalint** [comment]
well in 6de40bd at line 128 you left an additional isSuccess = false; in, so it will always show the error

**Comment by digimezzo** [comment]
I know. It was a test (I had to see if the Oops screen is OK in such cases). That mistake was fixed in b0cece09feb5198c3a8fdb251f5a26547f6b856d

**Comment by kbalint** [comment]
ah, didn't scroll that far ;)
