### ISSUE TITLE
Sort albums by DateAdded is not always working

### ISSUE THREAD

**Issue by motir** [digimezzo/dopamine-windows#248]
1. Open dopamine
2. Auto-detected and added 3 albums
3. Sort albums by date added
4. The albums are not present at the top of the list

Looking at the Dopamine db file, I see DateAdded is 0 for all albums so this might be a problem with inserting new records?

Added 3 albums - see attached log file.

[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/663056/Dopamine.zip)

**Comment by digimezzo** [comment]
I can't reproduce this, and looking at the code, if getting or storing the DateAdded should fail, it should have been logged. However I can't see anything in the log. I suspect there is something else going on. So I've created a small test application to verify that:

Could you download the application GetDateCreated.exe from here [Dropbox link](https://www.dropbox.com/sh/fqvqotogo2jv7kr/AAC54ENOFA89y78d30bMihRWa?dl=0)

This is the source code (so you know it is safe):

```
using System;

namespace GetDateCreated
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Please provide the path to a file:");
            string path = Console.ReadLine();

            try
            {
                string time = new System.IO.FileInfo(path).CreationTime.ToString();
                Int64 ticks = new System.IO.FileInfo(path).CreationTime.Ticks;
                Console.WriteLine("Time=" + time);
                Console.WriteLine("Ticks=" + ticks.ToString());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            Console.ReadKey();
        }
    }
}
```

All it does is, ask you for the path to a file. Provide the full path to one of those audio files. Then the application shows you the creation date of those files. That's What Dopamine uses as DateAdded.

Could you send me a screenshot of what the application window shows you?

Thanks!

**Comment by motir** [comment]
Please provide the path to a file:
d:\Music\Album\01.mp3
Time=16/04/2014 08:02:18
Ticks=635332321383112542

Looks like this is working ok.
If you add those numbers to the main dopamine logfile, I can re-add the album and see what is added.

Maybe a problem with saving the numbers, not with getting them right from the files?

**Comment by motir** [comment]
Ok, I figured out what the issue is.

You are using the date the files were added *to the file system*, not to dopamine.

In this case I added 3 albums that were created on the HD weeks ago but were not in the dopamine scanned folder. I just moved them to the folder and they were not at the top of the list because although the update date were today the creation date was 4 weeks ago.

I used http://www.nirsoft.net/utils/bulk_file_changer.html to change the creation date to today, removed and re-added the albums to Dopamine and now they're at the top of the list.

I think when you add an album to the DB you should just put the current datetime in DateAdded, not what you read from the files.

**Comment by digimezzo** [comment]
Ok thanks for the info. A long time ago, Dopamine used the current date as date added. That makes much more sense. But then there was a remark about this behavior: it should use the date created from the file instead of the current time. Using the current date is more logical, so that's how I'm going to solve this issue.

**Comment by digimezzo** [comment]
I'm reopening this issue. After consideration, using the current date isn't optimal. When doing a full re-index of the collection, Dopamine picks up the files in random order and the sort by date added is useless.
I'll have another look at this for version 1.3.

**Comment by motir** [comment]
Three options, I think:
1. When you re-index (why do you do that, btw?) don't reset the date-added field
2. If, for some reason you have to delete the db entry so you can't keep date-added, then only when you do full re-index use the file creation date as date-added. But during normal use, when new albums are added to an existing db, use the current date.
3. More complicated (GUI wise) - you can separate "sort by date added" and "sort by file creation date".

**Comment by digimezzo** [comment]
I'm adding an extra option "by date created".

- by date added: will sort by the date the songs are added in Dopamine
- by date created: will sort by the date the files were created in explorer

**Comment by Riajyuu** [comment]
what about `last modified date`. Is this going to be ignored?

**Comment by digimezzo** [comment]
@EMLVIRUS Yes
