### ISSUE TITLE
Zh-CN Locale

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#249]
Yes, me again. I'm also be able to help you with this, still same email.

**Comment by digimezzo** [comment]
Everyone it free to help with the translations. If a translation already exists for your language, just take the existing XX.xml file (where XX is the language code) in C:\Program Files (x86)\Dopamine\Languages, update it, and send it to me by e-mail.

Or, you can directly contribute through GitHub and send me a pull request for the updates.
