### ISSUE TITLE
ape support

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#251]
Add ability to play ape files.

**Comment by AsukaLangleyfag** [comment]
CSCore have support of FFMpeg via CSCore.Ffmpeg and Monkey's Audio is supported by ffmpeg. Also, it would be good to have it due of .apl, i find it good by being able to load one track instead of all sheet.

**Comment by digimezzo** [comment]
~~I'll test this out in Dopamine 1.5.1.~~
Test has been moved to Dopamine 1.5.
