### ISSUE TITLE
Default Keyboard Shortcut

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#254]
Play/Pause: space; Last: PageUp; Next: PageDown
Such shortcuts, though supported as multimedia key, should be set as default as they are really popular among basically every media player.

**Comment by digimezzo** [comment]
I've tried the space play/pause thing multiple times. It causes conflicts with the search box. There was no clean way to solve this problem. Agreed, some players use the space bar for play/pause, but lots of them also don't.
