### ISSUE TITLE
Add support for multichannel FLAC

### ISSUE THREAD

**Issue by jls2933** [digimezzo/dopamine-windows#255]
First, thank you for that awesome player.
I have some 5.1 FLAC tracks that i cannot play with Dopamine.

I got following error in logs :
`2016-12-21 17:28:35.7625|Error|Dopamine.Common.Services.Playback.PlaybackService+<TryPlayAsync>d__161.MoveNext|Could not play the file \Jean-Michel Jarre\Aero\5.1\1-Aero Opening.flac. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: IAudioClient::Initialize caused an error: 0x88890008, "Unknown HRESULT".. StackTrace:    à CSCore.SoundOut.WasapiOut.InitializeInternal()
   à CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   à Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   à Dopamine.Core.Audio.CSCorePlayer.Play(String filename)
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__161.MoveNext()
`

The FLAC files have following codec properties :
Channels : 3F2R/LFE
Frequency : 48000Hz
Bits / sample : 24 bits

**Comment by digimezzo** [comment]
Can you send me one of these FLAC files? (not through GitHub, but e-mail or a share).

**Comment by jls2933** [comment]
Sure, you can access to it at the following temporary url :
http://jeanlucmathieu.freeboxos.fr:8080/dl/1-Aero%20Opening.flac

**Comment by digimezzo** [comment]
Fixed thanks to #327
