### ISSUE TITLE
Tray Control Follow Tray Position

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#262]
When task bar is not docked at the bottom of the screen, tray control doesn't follow tray position.
![20161226_223647](https://cloud.githubusercontent.com/assets/16912240/21483377/09981420-cbbc-11e6-9c18-ebe28cdbdfe5.png)

**Comment by digimezzo** [comment]
That's a known issue. See #85

**Comment by digimezzo** [comment]
Fixed by 4d41cf91680acd031cdff3f887ca7017b761b73f
