### ISSUE TITLE
m3u Playlist Processing

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#263]
When I add a m3u playlist, nothing is displayed.
![20161227_151100](https://cloud.githubusercontent.com/assets/16912240/21493511/bf186d1a-cc46-11e6-9c7e-b0b315f15daf.png)

**Comment by digimezzo** [comment]
Those songs are probably not part of the collection. The current playlist implementation is rather basic. Only songs which are in the collection will appear in the playlists when opening playlist files. This limitation will be fixed in version 1.3. See #124.

**Comment by digimezzo** [comment]
See #124
