### ISSUE TITLE
Add support to Metrolyrics

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#265]
See [www.metrolyrics.com](www.metrolyrics.com).

**Comment by Riajyuu** [comment]
Hey, since you are considering lyrics plugins, why not consider this instead http://www.autolyric.com/
As it has a larger library.

**Comment by digimezzo** [comment]
@EMLVIRUS It would be great if it had and API or an easy way of automating lyrics search (e.g. using a simple, consistent URL that leads to a parsable webpage). Autolyric had neither (I'd be glad though if you could contradict me).
