### ISSUE TITLE
Add support for side mouse buttons

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#267]
A useful functionality that's missing is using Mouse 4 and Mouse 5 buttons to play the previous and next track, respectively. foobar2000 supports this natively, whenever the cursor is simply over the window.

**Comment by Riajyuu** [comment]
What do you mean by Mouse 4/5? If you the the two buttons places aside of six-button mouses, I would like to have such interaction as well.

**Comment by Keith94** [comment]
>What do you mean by Mouse 4/5?

Mouse 4/5 are buttons on the side of some mice, like this example.

![mouse buttons](https://cloud.githubusercontent.com/assets/5490615/21576593/c7dc2a76-ceea-11e6-827b-4d6b767eca75.jpg)

**Comment by digimezzo** [comment]
I don't have a mouse with as much buttons. Any help on this, is appreciated.

**Comment by motir** [comment]
OP - you should be able to use the Logitech software to set this up.
I have the MX Master and I mapped some gestures into play/pause and track next/prev. This works flawlessly with Dopamine, of course.

**Comment by Riajyuu** [comment]
@motir this is indeed reasonable for some Logitech mouse users. But for those whose use a instant plug-in-using mouse, software should have support for them as such types of mouses doesn't have any driver app.

**Comment by Keith94** [comment]
Added in 1.2.857.2 - thanks to @filoe
