### ISSUE TITLE
SetWindowLongPtr causes Exception on 32 bit operating systems

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#269]
If you add a great amount of tracks together (over 2000 or even more), Dopamine performances awfully: buggy, stopping working or crashed, especially with album covers embed.

**Comment by digimezzo** [comment]
Could you be more specific? Some hints:

- Delete the log file
- Reproduce the problem
- Send me the new log file

FYI, the log file is in %appdata%\Dopamine\Log

I'm adding 4000 tracks daily during development, and never saw this issue. So I need to know what's so different about your tracks.

**Comment by Riajyuu** [comment]
Plus os is Windows 7

![qq 20170101172758](https://cloud.githubusercontent.com/assets/16912240/21580737/19915a08-d049-11e6-8648-df08f4e2f1cc.png)
![qq 20170101172803](https://cloud.githubusercontent.com/assets/16912240/21580736/177dd638-d049-11e6-950d-368cb3a9b392.png)
Log is sent with email

**Comment by digimezzo** [comment]
This is the relevant part to the log. It has nothing to do with the amount of tracks added. No idea yet how this call suddenly fails on your computer. It has been in Dopamine for ages.

> 017-01-01 17:20:59.3790|Info|Dopamine.App.ExecuteStartup|### STARTING Dopamine, version 1.2.1 (Build 846), IsPortable = True, Windows version = Microsoft Windows 7 Æì½¢°æ  (Microsoft Windows NT 6.1.7601 Service Pack 1) ###
> 2017-01-01 17:21:01.5403|Info|Dopamine.Bootstrapper.InitializeWCFServices|CommandService was started successfully
> 2017-01-01 17:21:01.5725|Info|Dopamine.Bootstrapper.InitializeWCFServices|FileService was started successfully
> 2017-01-01 17:21:01.5725|Info|Dopamine.Bootstrapper.InitializeShell|Showing Main screen
> 2017-01-01 17:21:02.2117|Info|Dopamine.Common.Services.Indexing.IndexingService.IndexTracksAsync|+++ STARTED INDEXING COLLECTION +++
> 2017-01-01 17:21:02.7707|Info|Dopamine.Common.Services.Indexing.IndexingService+<IndexTracksAsync>d__30.MoveNext|Tracks removed: 0. Time required: 557 ms +++
> 2017-01-01 17:21:03.5197|Info|Dopamine.Common.Services.Indexing.IndexingService+<IndexTracksAsync>d__30.MoveNext|Tracks updated: 0. Time required: 502 ms +++
> 2017-01-01 17:21:03.5197|Info|Dopamine.Common.Services.Indexing.IndexingService+<IndexTracksAsync>d__30.MoveNext|Tracks added: 0. Time required: 6 ms +++
> 2017-01-01 17:21:03.6478|Info|Dopamine.Common.Services.Indexing.IndexingService+<IndexTracksAsync>d__30.MoveNext|+++ FINISHED INDEXING COLLECTION: Tracks removed: 0. Tracks updated: 0. Tracks added: 0. Time required: 1435 ms +++
> 2017-01-01 17:21:03.6478|Info|Dopamine.Common.Services.Indexing.IndexingService.IndexArtworkAsync|+++ STARTED INDEXING ARTWORK +++
> 2017-01-01 17:23:22.3357|Info|Dopamine.Views.Shell.PerformClosingTasksAsync|Performing closing tasks
> 2017-01-01 17:23:23.8378|Error|Dopamine.Core.Database.Repositories.QueuedTrackRepository+<>c__DisplayClass3_0.<SaveQueuedTracksAsync>b__0|Could not save queued tracks. Exception: Busy
> 2017-01-01 17:23:24.2788|Info|Dopamine.Common.Services.Playback.PlaybackService+<TryPlayAsync>d__170.MoveNext|Playing the file F:\Music\3OH!3 - My First Kiss (feat. Ke$ha).m4a. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False
> 2017-01-01 17:23:27.6840|Error|Dopamine.App.ExecuteEmergencyStop|Unhandled Exception. Exception:
> **_System.EntryPointNotFoundException: Unable to find an entry point named 'SetWindowLongPtr' in DLL 'user32.dll'.
>    at Dopamine.Core.Win32.NativeMethods.SetWindowLongPtr(IntPtr hWnd, Int32 nIndex, IntPtr dwNewLong)
>    at Dopamine.Core.Utils.WindowUtils.HideWindowFromAltTab(Window win)
>    at Dopamine.Common.Services.Notification.NotificationWindow.Window_Loaded(Object sender, RoutedEventArgs e)_**
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
>    at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
>    at MS.Internal.LoadedOrUnloadedOperation.DoWork()
>    at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
>    at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
>    at System.Windows.Interop.HwndTarget.OnResize()
>    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Stack trace:
>    at Dopamine.Core.Win32.NativeMethods.SetWindowLongPtr(IntPtr hWnd, Int32 nIndex, IntPtr dwNewLong)
>    at Dopamine.Core.Utils.WindowUtils.HideWindowFromAltTab(Window win)
>    at Dopamine.Common.Services.Notification.NotificationWindow.Window_Loaded(Object sender, RoutedEventArgs e)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
>    at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
>    at MS.Internal.LoadedOrUnloadedOperation.DoWork()
>    at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
>    at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
>    at System.Windows.Interop.HwndTarget.OnResize()
>    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by digimezzo** [comment]
Is this a 32 or 64 bit Windows? Has anything changed with you Windows installation since the last time Dopamine worked correctly?

**Comment by Riajyuu** [comment]
This isn't my issue but my friend: I'm simply helping him to ask here. He has been experiencing such issue since Dopamine installed.
As far as OS. I will ask him later as he's offline now.

**Comment by digimezzo** [comment]
OK. Please also check if it it the first time your friend installed Dopamine. I'm trying to figure out if this is something that suddenly broke or just never worked.

**Comment by Riajyuu** [comment]
I'm pretty sure it is first time he has installed Dopamine as he used foolbar2000 and AIMP, both of which worked fine.

**Comment by Riajyuu** [comment]
@digimezzo It's x32 Windows 7 pro.

**Comment by digimezzo** [comment]
@EMLVIRUS Excellent! Thanks! I think I have an idea what is going on then. For my own reference, this might be the fix. To be tested on a 32 bit virtual machine: [https://www.medo64.com/2013/07/setwindowlongptr/](https://www.medo64.com/2013/07/setwindowlongptr/)

I'll schedule this for release 1.2.3. Hopefully available in a few days.

**Comment by digimezzo** [comment]
This bug is fixed in commit 687439e119c68d89ffc123fcd4f8f90de1466f21. The fix will be in release 1.2.3.
