### ISSUE TITLE
Button for Saving the Update Confusing

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#270]
When Dopamine detects a version update, there will be a banner notification. But only the small button at the very left is clickable.
At the very beginning, I didn't realize such a fact, I simply click everywhere at banner to try. This can be annoying sometimes.
Instead of point at the small button precisely, why not make the whole banner clickable. You can add a warning dialog before performing update after clicking,
Actually the reason I try to click everywhere on the banner is that there is no appearance indication about which area is clickable. So you can just add appearance element to make the button stands out or even make the text also clickable. But I don't think there is much to do within such a thick banner.
Or you may have better idea about this. Any way, your project, your decision :-)

**Comment by digimezzo** [comment]
Agreed. I actually had a similar issue with another application (not mine) yesterday. A banner appeared which told me I should install some extension to improve the application's experience. But I could not immediately find where to click.

For Dopamine, won't make the whole bar clickable, but the complete message (button+text).

**Comment by Riajyuu** [comment]
In that case maybe you need to add more appearance elements to both button and text so that users will realize them clickable as soon as they see it, otherwise issue still exists. But I don;t have any idea how.
