### ISSUE TITLE
Local .lrc Files  Support

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#271]
When even there is local .lrc files relevant to the tracks, Dopamine seems still ignoring them.
So in 1.3 release, can there be an option to display them directly instead of downloading them online again?
Plus, if you ask what kind of .lrc files can be treated as relevant, I may say the same file name except the file type suffix. But I don't know if I'm right.

**Comment by Riajyuu** [comment]
In #124 , you wrote:
>m3u files which are dropped in the My Music\Dopamine\Playlists folder, should be picked up automatically

Does that mean lrc files placed together with audio file will be moved to My Music\Dopamine\Playlists folder? Or ignored?

**Comment by digimezzo** [comment]
@EMLVIRUS  No, lrc files will remain where they are.
