### ISSUE TITLE
Severe UI Broken Down

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#274]
OS Windows 10.14393.577 64bit
Reproducible: most time, but not always
STR:
1. enable remember last opened page and tray control forward and make X button (close button) behavior to close windows but not quit (aka minimize to tray).
2. quit and rerun Dopamine
3.click to close button to minimize the tray
4.click the tray for tray control. try more than twice
5.open main window, not from tray control but from tray
6.UI black out
![20170103_155254](https://cloud.githubusercontent.com/assets/16912240/21602306/926c8ef4-d1cd-11e6-8377-b574e57bf612.png)

**Comment by Riajyuu** [comment]
Plus, I'm pretty sure there is nothing valuable in log file
![20170103_160840](https://cloud.githubusercontent.com/assets/16912240/21602472/2669b234-d1cf-11e6-8705-6524dfcb3853.png)

**Comment by digimezzo** [comment]
The log indeed has nothing useful. I'm however not able to reproduce this issue; There must be something else at play.

**Comment by Riajyuu** [comment]
Hey, could you try once again by choose your last opened page to playlist? Plus, my playlist is empty.

**Comment by digimezzo** [comment]
Sorry, it doesn't matter what I select, or which screen is selected. I can't reproduce this here.
