### ISSUE TITLE
Song list: No option to sort by "liked songs"

### ISSUE THREAD

**Issue by seirerman** [digimezzo/dopamine-windows#277]
IIRC, there once was a column for the heart icon where we could sort our library by favorite songs.
Was this removed on purpose or is this a bug?

**Comment by digimezzo** [comment]
The heart rating was removed, only star rating remains. Your heart ratings should have been converted to star ratings automatically. Heart rating was removed to add Last.fm "Love", which is using the heart symbol.

**Comment by Riajyuu** [comment]
@digimezzo I think you should re-introduce this. Here are my proves:

1. You may rename it into `Flag` or sth else to avoid confusion. This is an "unique" list only exist in Dopamine.
    - In this case, metadata will not change at all but ratings on last.fm will.
2. These marked songs should be all in a new screen as another independent list. Compared to `Frequent`, you don't have to play any file frequently.
3. Compared to last.fm rating, you don't have to register or login.

**Comment by digimezzo** [comment]
@EMLVIRUS The "Love" thing can be used without Last.fm. It's just that when last.fm is enabled, the love thingy is sent t Last.fm. Is that not sufficient?

**Comment by Riajyuu** [comment]
@digimezzo I mean there should be an independent screen to display all songs marked. There are always some songs you like best and you wanna see them at one pace.
