### ISSUE TITLE
Does the prev version need a restart to take effect after changing the "Remove from disk"?

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#285]
When I pull request, this change takes effect immediately.
If this is the case, why `SetProperty<bool>` not sends a `PropertyChanged` notification?

**Comment by digimezzo** [comment]
The toggle switch change the value in the settings file. But the property which controls visibility in the context menu,  didn't detect a change of the settings file. So the context menu wasn't updated. The context menu got updated only at creation of MergedTracks.

The fix I added, makes sure that a change of the toggle switch, forces the property to read the settings file again.

**Comment by Magentaize** [comment]
So, I understand.
Thanks.

**Comment by digimezzo** [comment]
Good job on that extra feature, by the way. Thanks! I just made some small adjustments :)
