### ISSUE TITLE
When delete a "Playing" track from the disk, it will only remove the track from the collection.

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#288]
Beacuse `this.trackRepository.RemoveTracksAsync(singletrack)` only remove the record in database, but the file handle is still owned by Dopamine and `FileUtils.SendToRecycleBinSilent(path)` always return `true`  and the actual parameter doesn't have enough information whether this track is playing or not.

**Comment by Magentaize** [comment]
Maybe we should use Reflection to get `IsPlaying` Property in `MergedTrackViewMode`?

**Comment by digimezzo** [comment]
I think know how to fix this. I'll have a look at it.
