### ISSUE TITLE
Cannot get the correct Bitrate

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#289]
Encoder:qaac@VBR Q127(foobar2000 Free Encoder Pack) 
![untitled picture](https://cloud.githubusercontent.com/assets/11793304/21717450/43aee350-d454-11e6-9442-89378516ba0b.png)

**Comment by PeoLeser** [comment]
The encoder is `qaac 2.55, CoreAudioToolbox 7.10.6.0, AAC-LC Encoder, TVBR q127, Quality 96`.
Maybe the taglib-sharp cannot support the latest encoders(it cannot resolve the correct  internal byte)

**Comment by Magentaize** [comment]
Waiting for fix.
This's indeed a bug in Taglib# because it cannot correctly resolve the AAC-ADTS metadata.@digimezzo

**Comment by Magentaize** [comment]
I think that for those files which use VBR encoder, if TagLib return a value "0", the text should be “vbr". Due to the definition in the latest ISO specification, the "avgBitrate" box should be zero if using VBR. @digimezzo 
![](https://cloud.githubusercontent.com/assets/11793304/23854447/e96c12c2-0834-11e7-9af8-79104c684cdc.png)
