### ISSUE TITLE
"Cloud" screen needs a better name

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#296]
Users don't understand what this screen tries to show. The cloud screen shows the most and last played albums. The more you played an album, the bigger it will be displayed.

The new name must reflect that functionality, but also be short an catchy.

**Comment by Riajyuu** [comment]
> The cloud screen shows the most and last played albums. The more you played an album, the bigger it will be displayed.

If so, why not call it Frequent.
Reflecting functionality, brief, straightforward.
