### ISSUE TITLE
Minor visual bug in the close animation

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#300]
When you close any popups like the Edit or Information panels, there is a small bug where the left border(?) doesn't fade away properly, or something. I made a short screen recording..

![2017-01-08_22-08-42](https://cloud.githubusercontent.com/assets/5490615/21758307/311c80e8-d5ef-11e6-9d84-c76fd6f569cc.gif)

**Comment by digimezzo** [comment]
I can't reproduce this here. It is probably very dependent on graphical hardware.

**Comment by Keith94** [comment]
In that case I'll close this since it's very minor.
