### ISSUE TITLE
Restoring tracks that have been removed from the collection

### ISSUE THREAD

**Issue by rc201612** [digimezzo/dopamine-windows#304]
I have removed a track from the collection using the below option:

![2017-01-12_23-27-00](https://cloud.githubusercontent.com/assets/18450631/21912589/c932d1ac-d91e-11e6-9808-300c626f11c3.png)

Is there a way to get this track back into the library? I have refreshed the collection and it doesn't appear to have been restored.

**Comment by Riajyuu** [comment]
You can simply find it from Windows Explorer and drag it into.

**Comment by digimezzo** [comment]
When tracks are removed from the collection, they are remembered in a list list in the database. So next time you re-index, they are not re-added to the collection. You can disable that behaviour here:

![image](https://cloud.githubusercontent.com/assets/11945339/21919199/b82cf1fa-d958-11e6-9168-1d08ebfee161.png)

**Comment by Riajyuu** [comment]
Any way to empty this list? Disable and re-enable the feature?

**Comment by digimezzo** [comment]
@EMLVIRUS No. I've created #305 for that.
