### ISSUE TITLE
If add a playing track to PlayNext, the queue will behave strangely

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#308]
![untitled picture](https://cloud.githubusercontent.com/assets/11793304/22055705/d0be9340-dd9f-11e6-8639-93be22fec708.png)
There will be many same tracks in the queue, even loop the list becomes loop one track.
The collection is better to be a HashSet.

**Comment by digimezzo** [comment]
That's intended behaviour. Play next, queues the selected track next, to make sure that it is played next. It's how MusicBee does it, and how I wanted to implement it. The option "Add to now playing" doesn't add doubles.

**Comment by Magentaize** [comment]
Maybe that's my expression fault Orz.
The key problem is the behavior of "PlayNext" in PlaybackService. For example, I have add the same track to play next, so this track should be played twice. Actually, it will be played again and again, forever.

**Comment by digimezzo** [comment]
OK I see what you mean (i just reproduced it). That's indeed a bug.

Notes for myself:

- Play a file
- Click "Play next" on the file which is playing => file it is added to now playing, but there are 2 bugs:
1. Both files are displayed as playing
2. Once the added file starts playing, play next fails to play any other file
