### ISSUE TITLE
If Taskbar is set to hide, it won't reappear in Dopamine.

### ISSUE THREAD

**Issue by nike300** [digimezzo/dopamine-windows#312]
Basically what the title says: 
When setting the Taskbar to hide in Desktopmode when not used, and having Dopamine in Full Screen Mode, the Taskbar does not reappear when moving your Mouse to the Bottom of the screen as it does in other Apps like Firefox and Office. 
Only works if you press the Windows Key. Then it reappears.
Love your Media Player. Keep going :)
Cheers

**Comment by seirerman** [comment]
Same here, can confirm with build 871.

Dopamine doesn't even have to be in full screen mode, as this happens in windowed mode as well.

And yes, Dopamine is dope! :-)
