### ISSUE TITLE
After removing Playing track, the next-played track will jump to the beginning of the queue

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#316]
This situation happens after refactoring the collection, I'll keep track of this problem.

**Comment by Magentaize** [comment]
There's another question, whether the playlist should be the shuffled queue instead of the original one?

**Comment by digimezzo** [comment]
That's indeed the bug. The next available track should be played instead.
As for the other question: the playlist shows the unshuffled order, because users want to be able to re-order songs by drag and drop. If the shuffled order would be shown, this would not work in a predictable way.

**Comment by Magentaize** [comment]
Wow, that's wonderful! I actually now know that the list can be re-ordered.
