### ISSUE TITLE
Mini player windows are buggy when using Windows 10 in tablet mode

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#32]
Detect tablet mode: http://stackoverflow.com/questions/31153664/how-can-i-detect-when-window-10-enters-tablet-mode-in-a-windows-forms-application

**Comment by digimezzo** [comment]
~~More info about detecting tablet mode: [http://stackoverflow.com/questions/33041370/know-when-windows-10-are-tablet-mode-windows-10-windows-10-mobile](http://stackoverflow.com/questions/33041370/know-when-windows-10-are-tablet-mode-windows-10-windows-10-mobile)~~
This info was for UWP apps

This doesn't seem so easy to detect in a WPF project. Moved back to v1.3.

**Comment by Riajyuu** [comment]
<del>
Hey, have you tried to check Registry value:

using System;
using System.Management;
using System.Security.Principal;
using System.Windows.Forms;
using Microsoft.Win32;

public partial class MainForm : Form
{
    public MainForm()
    {
        this.InitializeComponent();
        this.UpdateModeFromRegistry();

        var currentUser = WindowsIdentity.GetCurrent();
        if (currentUser != null && currentUser.User != null)
        {
            var wqlEventQuery = new EventQuery(string.Format(@"SELECT * FROM RegistryValueChangeEvent WHERE Hive='HKEY_USERS' AND KeyPath='{0}\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ImmersiveShell' AND ValueName='TabletMode'", currentUser.User.Value));
            var managementEventWatcher = new ManagementEventWatcher(wqlEventQuery);
            managementEventWatcher.EventArrived += this.ManagementEventWatcher_EventArrived;
            managementEventWatcher.Start();
        }
    }

    private void ManagementEventWatcher_EventArrived(object sender, EventArrivedEventArgs e)
    {
        this.UpdateModeFromRegistry();
    }

    private void UpdateModeFromRegistry()
    {
        var tabletMode = (int)Registry.GetValue("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ImmersiveShell", "TabletMode", 0);
        if (tabletMode == 1)
        {
            Console.Write(@"Tablet mode is enabled");
        }
        else
        {
            Console.Write(@"Tablet mode is disabled");
        }
    }
}</del>


Oops, still for UWPs........

**Comment by digimezzo** [comment]
The value HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ImmersiveShell\TabletMode does change between 0 and 1 whether or not Tablet mode is enabled. So even from a WPF application I should be able o check it.
