### ISSUE TITLE
Update CSCore to version 1.2.0

### ISSUE THREAD

**Issue by mchowdhury** [digimezzo/dopamine-windows#325]
CSCore has been update to 1.2.0

https://github.com/filoe/cscore/releases

**Comment by digimezzo** [comment]
Thanks for bringing that to my attention. I'll make sure that happens.

**Comment by mchowdhury** [comment]
Thanks! Something to note, is that update should fix the high pitched sound in exclusive mode in issue https://github.com/digimezzo/Dopamine/issues/291
