### ISSUE TITLE
Show tray controls positioning doesn't take desktop scaling > 100% into account

### ISSUE THREAD

**Issue by karanrajpal14** [digimezzo/dopamine-windows#332]
I've moved my taskbar to the top of my screen and when I click on the tray icon, the popup still shows at the bottom of the screen. Same for left and right.

**Comment by digimezzo** [comment]
Which version of Dopamine are you using? That issue is fixed in the version 1.3 previews, not in the version 1.2 release.

**Comment by karanrajpal14** [comment]
I'm was using the stable version until now. Just upgraded to the latest preview to check and now, the popup doesn't even show up. I click the icon once and nothing shows up at all. I've attached the log just in case.
[Dopamine.txt](https://github.com/digimezzo/Dopamine/files/793815/Dopamine.txt)

**Comment by digimezzo** [comment]
Hmm, that log doesn't tell me anything unfortunately. I'll add more logging for the next preview.

**Comment by digimezzo** [comment]
Could you download [1.3 build 898 (Preview)](http://www.digimezzo.com/content/software/dopamine/previews/)?

It has more logging when trying to open the tray controls. Send me the log file once you reproduced that issue with that build.

Thanks!

**Comment by karanrajpal14** [comment]
Hey, 
I just installed the new version and from what I can see, the logs don't say much. I've attached a screencast of what's happening since it shows what the issue is. I think you'll have to increase the logging level further to find out what the issue is. Here's a link to my Dropbox folder:
[Click here](https://www.dropbox.com/sh/oq91xei4ei0lycu/AAB502o_mhjzxg6X4-s9CuWWa?dl=0)

**Comment by digimezzo** [comment]
Thanks for this info. I found out what happens. You are probably using a desktop scaling of 125% or more.
The tray control positioning ignores that and causes the tray controls to open outside of your screen.

TODO for me: fix tray control positioning.

**Comment by digimezzo** [comment]
Fixed in 3a914c55e55dc9a85304a2af28737910e10c8815
