### ISSUE TITLE
Make the spectrum analyzer stereo

### ISSUE THREAD

**Issue by finn-wa** [digimezzo/dopamine-windows#342]
At the moment, the spectrum analyzer remains symmetrical no matter which channel the audio is playing from. It would be great if songs which use a stereoscopic effect (e.g Blame Game by Kanye West) could be reflected in the height of the bars each side of the centreline. Obviously just a minor request, love Dopamine, keep up the good work!

**Comment by digimezzo** [comment]
Fixed in e9fb73ad31f4fa5e9235dce4d1230b24ca3eb24e
