### ISSUE TITLE
Add enhance: don't download lyrics unless LyricsControl is shown

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#347]
The lyrics will not be downloaded until users enter NowPlayingScreenLyrics for the first time, but once users have entered it, the lyrics will always be loaded.

So, these following two cases should be considered to reduce the net request:
&emsp;**Case 1**: After had pressed the BackButton in NowPlayingScreen and have returned to the MainScreen.
&emsp;**Case 2**: Switch to other pages like NowPlayingScreenPlaylist.
Additional, one more thing should also be paid attention to that the lyrics must be loaded when jump to NowPlayingScreenLyrics from other pages if the current track haven't loaded lyrcis ever.

*Actually, I have no idea.*

**Comment by digimezzo** [comment]
I should be able to do that by using the Prism IActiveAware interface on the NowPlayingScreenLyrics control. I'll have a look at it for version 1.3
