### ISSUE TITLE
Playlist items with UNC paths are not loaded

### ISSUE THREAD

**Issue by public-virtualys** [digimezzo/dopamine-windows#349]
Steps to reproduce :
- add a folder in the Dopamine library pointing to a network drive ; use its UNC path to refer to it (\\SERVER\music for instance),
- all music from this folder is playing nicely at this step,
- create a playlist with one song from this folder,
- save the playlist on disk with the dropdown menu item,
- delete the playlist in Dopamine,
- reopen the previously saved playlist : the playlist is empty (and no error message is displayed).

In log file, i have the following error :
2017-03-13 17:10:52.176|Error|<OpenPlaylistAsync>d__31.MoveNext|Error while decoding playlist file. Exception: Le format du chemin d'accès donné n'est pas pris en charge.

**Comment by digimezzo** [comment]
Which version of Dopamine are you using? This is a known issue in version 1.2. The latest 1.3 preview should have fixed this.

**Comment by public-virtualys** [comment]
Yes, i was using release 1.2.4.
With the 1.3 preview, problem has gone.
Thank you, sorry for the inconvenience !
