### ISSUE TITLE
Remove From Disk doesn't work

### ISSUE THREAD

**Issue by Rhizix** [digimezzo/dopamine-windows#352]
The remove from disk option does not seem to work.
When I click the button, nothing happens.

**Comment by digimezzo** [comment]
It works here. Could you attach the logfile?

**Comment by Rhizix** [comment]
Here it is. (Changed file extension to txt because I couldn't upload a .log)
Can't see anything related myself in the log tho.
[Dopamine.txt](https://github.com/digimezzo/Dopamine/files/844381/Dopamine.txt)

**Comment by Riajyuu** [comment]
I also give a test and it also works fine (Windows 10 x64)

**Comment by Rhizix** [comment]
Works fine for me aswell now, I reinstalled and it's fine

**Comment by digimezzo** [comment]
Strange... I'm closing this issues. In case it comes back, and there are more clues about what could cause it, please reopen it.

**Comment by Magentaize** [comment]
I have faced the same issue. The problem looks like happened because the player cannot be disposed properly so the file handle will never be released.
By the way, even though I have switched to the next track, the prev file still cannot be deleted.

**Comment by Magentaize** [comment]
I captured a GIF but I don't know the reason. @digimezzo 
![](https://cloud.githubusercontent.com/assets/11793304/24834126/63d5540a-1d17-11e7-9fca-cd852bb9082e.gif)

**Comment by Riajyuu** [comment]
@PeoLeser According to the gif, it seems to be file occupation. Aka the audio file is occupied by Dopamine.

**Comment by PeoLeser** [comment]
Yep, it is caused by the new version of CSCore, hope I can find out the reason soon.

**Comment by Magentaize** [comment]
Due to issue # 174 in CSCore, the aac file will not be disposed.

**Comment by ancich** [comment]
The Remove from disk is missing from my right-click menu  (yes, it is enabled in the settings).  Anyone encounter this?
Better yet, any fix for this???
