### ISSUE TITLE
New idea: Follow the theme color of album cover

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#362]
It looks like a little difficult.Ah...

**Comment by digimezzo** [comment]
I have some code lying somewhere, which find the average color of an image. Should be doable.

**Comment by Riajyuu** [comment]
Just a hint: Windows 10 has similar feature and Microsoft post codes on MSDN but I just forgot where it was

**Comment by Magentaize** [comment]
@EMLVIRUS Do you mean that suming all RGB number and calculatong RGB/pixelCount?

**Comment by Riajyuu** [comment]
> suming all RGB number and calculatong RGB/pixelCount

yep, good point.

**Comment by Magentaize** [comment]
No, it's not a appropriate way. What we need is a algorithm which can get the graceful theme color, if we only get the average color, it may be not what we want.

**Comment by FirasDev** [comment]
~~Why is [this](https://i.gyazo.com/753c9dcd8378622fbaad634620d18955.png) okay ?~~

~~Why not change the code to use the song cover if it has no album cover ? only 10% of my music has album covers and no one wants to edit all of his audio files, it looks like a simple if else problem to me.~~

**Comment by digimezzo** [comment]
@kreedz1 I've logged another issue as this is off-topic. See #384

**Comment by Magentaize** [comment]
First, let's look at this tree, I generate it from a album picture.
![1](https://cloud.githubusercontent.com/assets/11793304/25062108/69954024-2200-11e7-9b90-9da38e159ad1.png)
As you can see, there're so many colors in this color palette but which one is what we need? Should we design a algorithm to find a graceful one or simply combine them into one color?

Second, now I'm using following code to get the album image but it's to slow. Averagely it will take 2 seconds. So, should we modify the `Track` structure to get the album much more rapidly?
```cs
var allAlbums = await albumRepository.GetAlbumsAsync();
var album = allAlbums.First(allAlbum => allAlbum.AlbumTitle.Equals(playbackService.CurrentTrack.Value.AlbumTitle));
var filePath = cacheService.GetCachedArtworkPath(album.ArtworkID);
var tree = Digimezzo.Utilities.ColorSpace.Octree.BuildOctree(filePath, 1);
var accentColor = Color.FromRgb((byte)tree.Red, (byte)tree.Green, (byte)tree.Blue);
```

**Comment by digimezzo** [comment]
The octree seems like a powerful algorithm, but it's hard to define which color to choose from it.
I've added the code to change the accent color based on the average album cover color in 6da531b000f5c506c0a7ae29fd6fd3001084b1b8. I think that code seems OK.

To get the dominant color, I'm just using an algorithm that transforms the image to a 1x1 bitmap. the resulting color of that 1x1 bitmap is the average color. That code can be found in the Utilities library in ImageUtils.GetDominantColor(). It's not optimal, but performant. However if you have an idea to further improve it (especially for dark images), that's welcome.

I won't added the octree code to the Utilities yet, as we're not sure if that once will give us a better solution.

**Comment by Magentaize** [comment]
I have tried another algorithm called K-Means, in most cases it works well like iTunes 11, however due to this reason, sometimes the picked color is not what we want. And your Implementation is much more better.
![1](https://cloud.githubusercontent.com/assets/11793304/25126780/5775275e-246e-11e7-94cd-eb349aa9123c.png)
![2](https://cloud.githubusercontent.com/assets/11793304/25126783/5bad0918-246e-11e7-9402-70309b3f6e7c.png)
