### ISSUE TITLE
Use Windows 10 notifications API

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#367]
A user requested this feature.
See these screenshots:

This should be a standard Windows 10 notification:

![safe_image](https://cloud.githubusercontent.com/assets/11945339/24476243/e287f23c-14d2-11e7-9b9f-14ced0203bf0.png)

This notification is used by Groove. But it only appears after pressing media keys it seems. I didn't find a way to display it on song change. Maybe the API provides such function, but it's not used by Groove.

![29d61d4e-d4a7-41d6-82b3-3daaa678c323](https://cloud.githubusercontent.com/assets/11945339/24476246/e368a1ec-14d2-11e7-9201-1a91db1dc610.JPG)

**Comment by Magentaize** [comment]
It can only be used by UWP.

**Comment by Riajyuu** [comment]
@PeoLeser is right. That's inaccessible for any desktop app.

**Comment by digimezzo** [comment]
I found this: [http://stackoverflow.com/questions/35910332/windows-10-notification-wpf](http://stackoverflow.com/questions/35910332/windows-10-notification-wpf)

I haven't tried it out yet, but I'm guessing this only concerns the bottom right notification, not the volume controls.

By the way, if any of this would even be possible in a WPF app, the original Dopamine popups must still be retained, to allow users to choose.

**Comment by Magentaize** [comment]
Yep, I have no idea about that volume control, but the popup notification can work well in a classic WPF application(I think dopamine's notification is more graceful).

**Comment by digimezzo** [comment]
I agree the default Dopamine notification is better. That's why I'd like to keep it. Windows 10 popups should be merely optional. This issue has low priority.

**Comment by Magentaize** [comment]
I got it! It is called SystemMediaTransportControls without an official name and it's a UWP control but we can use it in WPF app.

**Comment by amaan6999** [comment]
Definitely would be cool to have the option to integrate. Perhaps given the option at install?
