### ISSUE TITLE
Crash when Disposing CSCore.SoundOut.WasapiOut

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#379]
A user reported 2 crashes.

It seems there is an unhandled exception in CSCore.SoundOut.WasapiOut when disposing.
It seems to happen when starting to play a track. So I guess it happens when SoundOut of the previous track is disposed when a new track starts playing. These are the logs from the user;

**Crash 1**
> 2017-04-04 18:50:34.652|Info|<TryPlayAsync>d__171.MoveNext|Playing the file F:\Audio\Tamil\24\Naan Un.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True
> 2017-04-04 18:51:18.543|Error|App.ExecuteEmergencyStop|Unhandled Exception. Exception:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallbackNative(IMMNotificationClient notificationClient)
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(IMMNotificationClient notificationClient)
>    at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
>    at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean streamSwitch)
>    at CSCore.SoundOut.WasapiOut.Dispose(Boolean disposing)
>    at CSCore.SoundOut.WasapiOut.Finalize()
> 
> Stack trace:
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallbackNative(IMMNotificationClient notificationClient)
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(IMMNotificationClient notificationClient)
>    at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
>    at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean streamSwitch)
>    at CSCore.SoundOut.WasapiOut.Dispose(Boolean disposing)
>    at CSCore.SoundOut.WasapiOut.Finalize()

**Crash 2**

> 2017-04-04 23:06:34.663|Info|<TryPlayAsync>d__171.MoveNext|Playing the file F:\Audio\Malayalam\Munthirivallikal Thalirkkumbol\Athimarakombile.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True
> 2017-04-04 23:06:35.770|Error|App.ExecuteEmergencyStop|Unhandled Exception. Exception:
> CSCore.CoreAudioAPI.CoreAudioAPIException (0x80070490): IMMDeviceEnumerator::UnregisterEndpointNotificationCallback caused an error: 0x80070490, "Element not found.".
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(IMMNotificationClient notificationClient)
>    at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
>    at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean streamSwitch)
>    at CSCore.SoundOut.WasapiOut.Dispose(Boolean disposing)
>    at CSCore.SoundOut.WasapiOut.Finalize()
> 
> Stack trace:
>    at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(IMMNotificationClient notificationClient)
>    at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
>    at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean streamSwitch)
>    at CSCore.SoundOut.WasapiOut.Dispose(Boolean disposing)
>    at CSCore.SoundOut.WasapiOut.Finalize()

**Comment by digimezzo** [comment]
I honestly have no idea how to reproduce this issue. I'll close the issue for now unless another user has ever experienced this.

**Comment by filoe** [comment]
Might be connected to https://github.com/filoe/cscore/issues/233
