### ISSUE TITLE
The control bar does'nt show when I open the windows of the softwate 

### ISSUE THREAD

**Issue by Mackel123** [digimezzo/dopamine-windows#380]
I think it is little terrible about the problem, but when I open the window of the software after I close the window, I can't see the control bar. 

![image](https://cloud.githubusercontent.com/assets/27003282/24793603/4b32765c-1bb5-11e7-8f68-39b48a2f010a.png)

**Comment by digimezzo** [comment]
I'm afraid you'll have to be more specific. I can't reproduce it here.

**Comment by Riajyuu** [comment]
@Mackel123 you seems to be Chinese and I'm confused by your English. If so, please describe the steps more precisely in both English and Chinese. I may help out a little bit to pass your meaning to author.

**Comment by Riajyuu** [comment]
Plus, I can't reproduce as well.

**Comment by Mackel123** [comment]
好的，我担心您不懂中文，我就用中文来描述问题吧~就是软件在打开的时候上面关闭按钮那一块儿是完全不显示的，我自己不清楚原因，大概是打开软件之后然后最小化到任务栏，再打开软件窗口就会常出现问题，就像我截图的那样，需要我再发一次就图吗

**Comment by Riajyuu** [comment]
> 就是软件在打开的时候上面关闭按钮那一块儿是完全不显示的，我自己不清楚原因，大概是打开软件之后然后最小化到任务栏，再打开软件窗口就会常出现问

conclusion: windows control button disappeared if reopen the dopamine window after minimized to task bar.

I still can not reproduce.

此问题仍旧无法复现，你可能需要提供更多信息
PS 我不是作者 楼上那个是

**Comment by Mackel123** [comment]
OK， could I send the screenshot ?The proble is I could see the close button at the top right of software

发送自 Windows 10 版邮件应用

发件人: EMLVIRUS
发送时间: 2017年4月7日 17:25
收件人: digimezzo/Dopamine
抄送: Mackel123; Mention
主题: Re: [digimezzo/Dopamine] The control bar does'nt show when I open thewindows of the softwate (#380)

@Mackel123 you seems to be Chinese and I'm confused by your English. If so, please describe the steps more precisely in both English and Chinese. I may help out a little bit to pass your meaning to author.

**Comment by Mackel123** [comment]
OK， could I send the screenshot ?The proble is I could see the close button at the top right of software

**Comment by Riajyuu** [comment]
同样的截图无助于问题解决。建议尝试：

1. 排除软件冲突
2. 排查显卡问题
3. 尝试不同版本（PS 作者刚刚发布了新的预览版）

**Comment by Magentaize** [comment]
I have reproduced your problem. It's a historical issue and only occurs when taskbar is on the top.
Follow these steps:
1.Open Dopamine and set the window to maximum.
2.Close the main window via close button.
3.Left click the trayicon and click "Show Dopamine".

**Comment by Riajyuu** [comment]
Yes, @PeoLeser has provided the eaxct steps.
I also reproduce it with his step. Could your retry by following his steps? @digimezzo

**Comment by digimezzo** [comment]
Yes I can reproduce it now. Thanks for the steps! It only occurs when the taskbar is at the top, AND when choosing "Show Dopamine" from the tray controls. Not when choosing "Show Dopamine" from the right-click menu on the tray icon. Very strange.

**Comment by Mackel123** [comment]
Yes，bur it didn’t work. Maybe it is because of the bug of the software,.Maybe the other reason is the compatibility of the windwos10.

发送自 Windows 10 版邮件应用

发件人: EMLVIRUS
发送时间: 2017年4月7日 22:14
收件人: digimezzo/Dopamine
抄送: Mackel123; Mention
主题: Re: [digimezzo/Dopamine] The control bar does'nt show when I open thewindows of the softwate (#380)

Yes, @PeoLeser has provided the eaxct steps.
I also reproduce it with his step. Could your retry by following his steps? @digimezzo

**Comment by Mackel123** [comment]
I have tried by the way just nows, but it didn’t work. When I close the software to the notification area, I couldn’t see the the close button.

发送自 Windows 10 版邮件应用

发件人: PeoLeser
发送时间: 2017年4月7日 21:56
收件人: digimezzo/Dopamine
抄送: Mackel123; Mention
主题: Re: [digimezzo/Dopamine] The control bar does'nt show when I open thewindows of the softwate (#380)

I have reproduced your problem. And it only occurs when taskbar is on the top.
Follow these steps:
1.Open Dopamine and set the window to maximum.
2.Close the main window via close button.
3.Left click the trayicon and click "Show Dopamine".
