### ISSUE TITLE
Make the theme setting a dropdown menu

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#389]
A minor UI issue that bugs me:
The light or dark theme setting is presented like an on/off switch, but it's not the same as the other yes/no settings. It makes more sense if you change it into a dropdown menu, exactly like the "spectrum style" setting.

**Comment by Riajyuu** [comment]
Agreed. It is indeed a little bit confusing now.

**Comment by Magentaize** [comment]
Changing text to "Use light theme" may be better, I love that toggle animation so much!

**Comment by digimezzo** [comment]
@PeoLeser Could you send me a pull request for this change. I like the way you implemented it.

**Comment by Magentaize** [comment]
@digimezzo  Actually, I have changed it in [#596ac57](https://github.com/digimezzo/Dopamine/commit/2f91eb2c6da70f94eb740bcd3162f061062e127c)
