### ISSUE TITLE
After default audio device changes, the volume control doesn't work anymore.

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#411]
Steps to reproduce:

- Change the default Windows audio device (in windows 10 this is easy, just choose another device in the windows volume tray control)
- Switch back to the previous audio device
- change the volume in Dopamine (using the volume slider) => BUG: the volume doesn't change anymore.

Mute/unmute also stops working in the above case.

**Comment by digimezzo** [comment]
Could you comment a bit on the fix? I thought it was a Dopamine issue. Was this a bug in CSCore? Did you fix that bug or did filoe fix on the CSCore GitHub? I'd like to have a reference to the fix on the CSCore GitHub for tracking purposes and to avoid breaking it again when adding newer CSCore versions.

**Comment by Magentaize** [comment]
Sorry, I haven't subscribed this issue so that I do not see your commit in time. 
I think it's actually a bug in CSCore, I requested a pull request [here](https://github.com/filoe/cscore/pull/238).

**Comment by digimezzo** [comment]
No problem. I'll accept your full request but keep this issue open. I want to keep track of the pull request on CSCore. Once it's accepted on the CSCore project, we can close this issue on Dopamine.

**Comment by digimezzo** [comment]
Reopened: issue is fixed in Dopamine by fixing a bug in CSCore. The pull request fixing the CSCore bug is still pending.

**Comment by Magentaize** [comment]
The fix has been merged.
