### ISSUE TITLE
Margin under maximized window (fixed) and blurry cover in notification window

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#418]
Reported by a user. See screenshots.

Margin below maximized screen. This might be related to #408 and might already be fixed. Note: the user is using scaling of 125%. Check if the fix for #408 also works for scaling > 100%.
![idtisx0](https://cloud.githubusercontent.com/assets/11945339/26424334/27f09750-40d1-11e7-8a44-bcdeba3fae18.png)

Notification scales badly:
![t5gvgyu](https://cloud.githubusercontent.com/assets/11945339/26424348/38b95ed2-40d1-11e7-9018-3f2c57030377.png)

**Comment by HaloTechnology** [comment]
thanks for taking my comment :D your app is soooo Underrated

**Comment by Magentaize** [comment]
related to [#314](https://github.com/digimezzo/Dopamine/issues/314) but miximazied issue cannot be reproduced

**Comment by digimezzo** [comment]
The maximize issue is indeed fixed. I'm not sure if the latest 1.3 preview has the fix already. If not, it'll be in the next preview (to be available probably in a few days). 

The notification scaling "issue" is not an issue. To me, it seems this cover is not a square, and contains a front and back cover in 1 image. Due to this, it looks wrong on the notification, and also probably in other places where the cover is displayed. Am I right?

**Comment by Magentaize** [comment]
In my opinion, maybe the meaning of this user is that that notification looks like be blurred.

**Comment by digimezzo** [comment]
@PeoLeser You are right about the blurring. I'm renaming the issue to point this out.

I'll have to apply a fix similar to other places where covers are rendered. The pre-render size should be at least 150% so that WPF doesn't try to scale the images up when using 125 or 150% scaling in Windows.

**Comment by HaloTechnology** [comment]
yep @PeoLeser is correct that exactly what i meant :D

**Comment by Magentaize** [comment]
@digimezzo not only the image, but also the whole control region.

**Comment by HaloTechnology** [comment]
@PeoLeser correct also the right click menu have the same thing it's not scaled probably .

I think that why I love Dopamine that's it's DPI aware and those the only 2 issuies I found regarding scaling my windows is on 125% 

I wonder how Dopamine will look on a 4k display I am sure it will look epic

**Comment by digimezzo** [comment]
Commit be51f7be5be065704cdfee3ceeba53a819065bcb fixes the blurry context menu at desktop scaling > 100%.
Commit c843e450cd2e1d4d75f6ccb9c746c9d649c4f5e6 fixes the blurry notification window
Commit fc03ee6dba82af3b8af9e4dae615ad87b6a1ca30 fixes blurry tooltips
