### ISSUE TITLE
About the columns in the "song" panel 

### ISSUE THREAD

**Issue by schwarzichet** [digimezzo/dopamine-windows#419]
I have noticed that in the old version of Dopamine, there was a place to choose what metadata of a song should be displayed.
<img width="780" alt="image" src="https://cloud.githubusercontent.com/assets/15522755/26521549/9a61a1b4-431d-11e7-8f3d-ebf35a9c41df.png">
while I can't find that function on the newest version of Dopamine, neither in the "song" or settings.
<img width="791" alt="image" src="https://cloud.githubusercontent.com/assets/15522755/26521574/566db546-431e-11e7-91a2-fa48c419d9c9.png">

I want that feature back because more often than not my songs' Genre or Year information are lost. That's a little unpleasant for me.
By the way, Dopamine is very beautiful, probably the most beautiful music app on windows10. I expect its progress on other tiny details.

**Comment by Magentaize** [comment]
Right click at any row

**Comment by schwarzichet** [comment]
Thanks!
By the way, I noticed a tiny bug just now. The sorting order of the bitrate is wrong. 1000kbps shouldn't be the minimum.
 
<img width="765" alt="image" src="https://cloud.githubusercontent.com/assets/15522755/26522045/710c237c-432a-11e7-93a6-5f8b01fe6c16.png">
<img width="765" alt="image" src="https://cloud.githubusercontent.com/assets/15522755/26522049/7b771204-432a-11e7-9234-d079fd89d2e4.png">

**Comment by Magentaize** [comment]
What's the version you're using? This should be fixed in [this commit](https://github.com/digimezzo/Dopamine/commit/7a9cd34eca760c0b0b5ae30f1b86fcdf6e063111).

**Comment by schwarzichet** [comment]
1.2.4 (build 862)

**Comment by digimezzo** [comment]
Please try out the latest 1.3 preview. You can download it here: [http://www.digimezzo.com/content/software/dopamine/previews/](http://www.digimezzo.com/content/software/dopamine/previews/).

The previews are very stable. You should not have any issues using them.
Please let us know if it fixes your issue.

**Comment by schwarzichet** [comment]
good! No problem in 1.3.0.918.
Thank you!

**Comment by digimezzo** [comment]
Thanks for confirming! :)
