### ISSUE TITLE
A tiny bug on number display

### ISSUE THREAD

**Issue by schwarzichet** [digimezzo/dopamine-windows#423]
the "100" that I have circled seems to fail to display. And trying to scale the window is of no use. 
<img width="790" alt="image" src="https://cloud.githubusercontent.com/assets/15522755/26534574/56d2feac-4458-11e7-9850-bb6dc6a663b3.png">

**Comment by Riajyuu** [comment]
What do you mean by
> fail to display

It seems to be partially blocked by inner border instead. Maybe several pixels of padding will work.

**Comment by digimezzo** [comment]
@EMLVIRUS I've seen this before in WPF when using desktop scaling > 100%. Padding might indeed be the solution to this.

**Comment by schwarzichet** [comment]
My fault. My English is not so good QAQ. Your description is better.
the last zero is partially blocked. and changing the size of the Dopamine helps nothing.
