### ISSUE TITLE
Implement smart playlists

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#424]
See title. Look at iTunes and MusicBee for examples.

**Comment by trymeouteh** [comment]
If your able to make it so you can create smart playlist files that would be a bonus. That way we can backup the files and use them in other music players on other devices.

**Comment by Keith94** [comment]
Is it finally here? :D can't wait to try it.

**Comment by digimezzo** [comment]
@Keith94 Yes it is. I just need to do some tweaking, and Preview 2 will be released. If life treats me well, it should be this week :)

**Comment by The-Choo-Choo-Shoe** [comment]
Currently I find no way to make random playlists.

For example I like to make playlists where I limit a playlist to say 100 songs for by genre or whatever and it plays 100 different songs in random order every time the playlist is played.

**Comment by digimezzo** [comment]
HI @The-Choo-Choo-Shoe , I'm creating a feature request for this: #920
