### ISSUE TITLE
Play Next is Broken While Shuffle is on

### ISSUE THREAD

**Issue by Alamer99** [digimezzo/dopamine-windows#438]
Shuffle Causes "Play Next" To Be Ignored

How To (RE)Produce:
1st. Add 3 or More Tracks to Now Playing List.
2nd. Add One or More Tracks as "Play Next"
Once The Current Track Ends The Next Track Will Be Randomly Shuffled

**Comment by AhmetFUsta** [comment]
Bug resurfaced on v2
Whenever I add a track to "Play Next" and press next it jumps to the same song everytime (not the song I put on Play Next)
