### ISSUE TITLE
24 bit WAV files not working (to be verified)

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#441]
24bit WAV file plays ok in Groove, but Dopamine seems not to support it.
This was reported by a user and not yet verified.

**Comment by Riajyuu** [comment]
Well. Any available sample? I have only 24-bit Hi-Res FLAC. I'm not sure if converting it will be the same situation.

![image](https://user-images.githubusercontent.com/16912240/27863546-2b317242-61bd-11e7-806a-cf08d9d9a41c.png)

**Comment by digimezzo** [comment]
I've requested a test file. I'm awaiting feedback.

**Comment by Riajyuu** [comment]
@digimezzo I have tried to convert the display FLAC into WAV but both work properly

**Comment by filoe** [comment]
Wav can contain many different formats but by far not all are supported by cscore. The CSCore.Ffmpeg module would support some further formats.

**Comment by digimezzo** [comment]
File received. It is available [here](https://www.dropbox.com/sh/042tszdk8zjftm8/AABUxVdu0oxYwejFOelOibKga?dl=0)

This is the stacktrace when trying to play the file: 

> 2017-07-05 22:10:55.656|Error|<TryPlayAsync>d__179.MoveNext|Could not play the file C:\Users\rapha\Desktop\106 - Karma Police (Remastered).wav. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True. Exception: Waveformat is not supported. Invalid WaveformatTag.. StackTrace:    at CSCore.Streams.SampleConverter.WaveToSampleBase.CreateConverter(IWaveSource source)
>    at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
>    at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
>    at Dopamine.Common.Audio.CSCorePlayer.Play(String filename, MMDevice outputDevice)
>    at Dopamine.Common.Services.Playback.PlaybackService.<>c__DisplayClass178_0.<StartPlaybackAsync>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__178.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__179.MoveNext()

**Comment by filoe** [comment]
Well that is exactly I was talking about... seems like it contains a unsupported format.

**Comment by digimezzo** [comment]
I'm planning to add ffmpeg in Dopamine 1.4. I'll have a closer look at this bug then.

**Comment by digimezzo** [comment]
Fixed thanks to #327
