### ISSUE TITLE
Bug: Editing metadata of music either does not work or takes a while to update

### ISSUE THREAD

**Issue by MulverineX** [digimezzo/dopamine-windows#444]
When editing a song's metadata it does not update consistently and never updates in the editor when opening it up for that song again.

**Comment by MulverineX** [comment]
![capture](https://user-images.githubusercontent.com/12068027/27941319-554f01f4-628d-11e7-8d33-96baf56f4aa7.JPG)
You have to restart the program after changing the metadata for it to have effect on now playing but as shown it does not update in the editor.

**Comment by digimezzo** [comment]
I can reproduce the now playing which doesn't update after a metadata change and fixed it now. But I cannot reproduce the editor issue. When I change metadata for song, close and then re-open the editor, the metadata is up to date.
Can you describe steps to reproduce this issue?

**Comment by MulverineX** [comment]
I just updated to the preview/beta version and it updates now. Thanks for the fix! This program is fantastic, now if only there was a file explorer, text editor, and movie player this good.. XD.

**Comment by digimezzo** [comment]
I changed the title back to its original title. "Solved" it was a bit confusing when looking at the list of issues.
