### ISSUE TITLE
[Feature Request] Music Crossfading

### ISSUE THREAD

**Issue by MulverineX** [digimezzo/dopamine-windows#445]
An option to have at the end of a song the player turn down the volume of the current song and slowly at low volume going up introduce the next song in que/playlist/shuffle. BlackPlayer has this and I think it would be a nice feature on this as well.

**Comment by Riajyuu** [comment]
Is this dup to #92 ?

**Comment by MulverineX** [comment]
Probably but thats a ways back so I didnt notice
