### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by beerisgood** [digimezzo/dopamine-windows#447]
When i start Dopamine (1.0.660.0 - Portable) it eat 55MB with nano/micro mode and up to 70+MB in normal mode, without any playlist or songs played.

When i start AIMP it only need 13MB with small window mode and a big playlist.

Win7 SP1 x64
4GB RAM

I would say this is because of .NET, so i would suggest switch to another language because .NET is always a memory eater

**Comment by Riajyuu** [comment]
Well. I don't really care because 70MB or even 700MB are same for me. But it is up to @digimezzo

**Comment by digimezzo** [comment]
That's indeed related to .NET. I'm not going to explain how .NET manages memory here, as that would be time consuming. But it does quite a good job. I suggest you read about it if you have concerns.

If you find that memory usage increases a lot during usage, and that it never goes down anymore, there is a memory leak and that's an issue. If Dopamine uses more memory than an application written in unmanaged code but the memory usage remains more or less stable, then there is no issue.

As for switching to another language: sorry, no, .NET is powerful and fun to work with.

**Comment by beerisgood** [comment]
Fair enough.
Thanks for explanation
