### ISSUE TITLE
Provide checksum to check integrity

### ISSUE THREAD

**Issue by beerisgood** [digimezzo/dopamine-windows#448]
Please provide checksum (SHA2-256 or higher because MD5 and SHA1 is broken) so we can check that the files are not corrupted.

**Comment by Riajyuu** [comment]
I don't think this necessary as checking if an audio file is broken can be similar accomplished by calculating bit rate and sampling rare.

**Comment by beerisgood** [comment]
What? I dont talk about audio files.
I speak about verifing the Dopamine binarys

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
@digimezzo
*push*
Still no checksums for Dopamine binarys

SHA2-512 would be good. https://en.wikipedia.org/wiki/Sha512
SHA3 of course too https://en.wikipedia.org/wiki/SHA-3
Dont provide MD5 or SHA1 because both are broken and can be spoofed

**Comment by digimezzo** [comment]
Sorry, I don't see this as critical. If you download the from the Digimezzo website, you're sure to have the correct binaries.

The day this is feature is implemented, it will have to be fully automated. This means:

- the packager application should generate checksums for the installer and portable package
- the checksums for each package will be written into a text file
- the checksums text file is uploaded to the same location as the binaries

I no circumstances do I want to perform any manual action to provide this. So updating the checksum on a page of the website is out of the question.

**Comment by beerisgood** [comment]
But we cant verify the binarys. Not secured over HTTPS, no PGP sig to check the File is from you and No checksum to check that the File isnt corrupted
I dont understand why this is so hard

**Comment by digimezzo** [comment]
It is not a matter of this being hard. The software is created for free during my spare time. I have to use the time at hand in the most optimal way. That means keeping a realistic balance writing useful and quality code, and implementing security. This isn't NSA grade software. Also, most users don't know what checksums are, let alone calculate checksums for their downloaded files. So keeping the above in mind: providing downloads via HTTPS (which is already the case) and providing a file with checksums in the downloads sections, seems like the most optimal choice. It's already better than some other projects are doing.

**Comment by beerisgood** [comment]
Ah i doesnt see your website support HTTPS. Maybe it would be better if the site enforce HTTPS, cause all links to your sites - even from Github, is HTTP

**Comment by digimezzo** [comment]
Ok, I've just changed the link on Github. The site now also redirects to https automatically.
