### ISSUE TITLE
3 Issues in Removing Tracks From "Now Playing" Playlist

### ISSUE THREAD

**Issue by Alamer99** [digimezzo/dopamine-windows#450]
#### 1. Removing The Only Playing Track Doesnt Update The Bottom Playback Bar/Cover in The Background:
 * ![2017-07-09_15-45-40](https://user-images.githubusercontent.com/18061436/27994181-ff88d714-64c0-11e7-940d-32120f4e31cd.png)
 * ![dopamine_2017-07-09_15-51-34](https://user-images.githubusercontent.com/18061436/27994180-ff88a974-64c0-11e7-943f-9b0a7c960618.png)

#### 2. Removing All The Tracks in Now Playing Playlist Whilst One of Its Tracks is Playing Doesnt Stop The Current Playing Track:
 * ![dopamine_2017-07-09_16-00-12](https://user-images.githubusercontent.com/18061436/27994182-ff890a54-64c0-11e7-9013-7db051425ade.png)
 * ![dopamine_2017-07-09_16-01-41](https://user-images.githubusercontent.com/18061436/27994179-ff88b590-64c0-11e7-9433-175ab83d9b76.png)

#### 3. Removing a Track(s) Doesnt Update The Size/Duration However Adding One or More Does:
 * ![dopamine_2017-07-09_16-04-37](https://user-images.githubusercontent.com/18061436/27994183-ff8a1ac0-64c0-11e7-97eb-f1b83015050f.png)
 * ![dopamine_2017-07-09_16-05-04](https://user-images.githubusercontent.com/18061436/27994178-ff887b98-64c0-11e7-9629-1c41cea8e09b.png)

**Comment by digimezzo** [comment]
1 and 2 are not bugs. However they are open for suggestion. A matter of choosing if Dopamine should stop the removed track. 3 is a bug.

**Comment by Alamer99** [comment]
since its open for suggestion,
1: removing a track from the play list should clear the player, i dont see why keeping it is an option, clicking the play button doesnt play the same track anyway.

2: i honestly think that this is wrong, removing the entire playlist should stop it, i clear the playlist because i want it to stop

thats just my opinion on it.

**Comment by digimezzo** [comment]
OK, sound good to me. I'll fix all 3 things in version 1.4.
