### ISSUE TITLE
Show only album art in taskbar preview

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#453]
If a song is playing, Dopamine could have the cover art displayed full size like below.

![2017-07-10_16-31-17](https://user-images.githubusercontent.com/5490615/28044673-95906520-658d-11e7-9b41-2c4874b2a508.png)

**Comment by Riajyuu** [comment]
dup to #112 ?

**Comment by Keith94** [comment]
Yep, didn't see that one. Thanks
