### ISSUE TITLE
[Bug] Mini Player with Playlist Demonstrates Lag

### ISSUE THREAD

**Issue by 2JayCee** [digimezzo/dopamine-windows#455]
1. Open Dopamine

2. Searched an Album on the search bar

3. Opened/Played an Album on results

4. Pressed the Mini Player Button

5. Pressed the Playlist button on the bottom left.

6. Dragging the Mini Player on the desktop with the playlist extended displays lag.  (Dopamine is on my second monitor, I have dual-monitors with extend)

[Dopamine.txt](https://github.com/digimezzo/Dopamine/files/1143090/Dopamine.txt)

**Comment by digimezzo** [comment]
Do you mean that's the playlist window moves with some delay when dragging around? That's possible, depending on your computer performance. The playlist window is a separate window, which moves as a reaction to movement of the main window. Calculation of the playlist window position takes a fraction of time.

**Comment by 2JayCee** [comment]
Yes, exactly.  There is noticeable lag when moving the playlist window.  I'm running an Intel i7 4790K and GTX 780 Ti Classified for reference.

**Comment by Magentaize** [comment]
I don't think it's a problem of computer performance, after I replaced all variables with constants and used win32 api `MoveWindows`, when I dragging the mini player with playlist and no playing tracks, the behavior of window seems more smooth, however, if some tracks are playing, it becomes very lagging.

**Comment by 2JayCee** [comment]
Would transparency of the mini-player have an impact on the lag as well?

**Comment by Magentaize** [comment]
No.

**Comment by digimezzo** [comment]
This cannot be reproduced here.

**Comment by Magentaize** [comment]
It will not be fixed, link [WPF screen flickering while resizing ](https://connect.microsoft.com/VisualStudio/feedback/details/652771/wpf-screen-flickering-while-resizing)

**Comment by Magentaize** [comment]
Update:
You can try to decrease lag by disabling "Hey Cortana" . Actually, I have no idea about the reason why Cortana may influence the performance of system UI.

**Comment by 2JayCee** [comment]
My "Hey Cortana" is already disabled by default.  Do you mean disabling Cortana entirely?

**Comment by Magentaize** [comment]
You can try to enable Hey Cortana and then disable it or disable Cortana entirely. After disabling Cortana, my whole system works much more faster than before.
By the way, do you feel that the taskmgr is very sluggish when opening it?
