### ISSUE TITLE
Follow the windows color not remembered

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#460]

**Comment by digimezzo** [comment]
Reported by a user but not yet verified:
  
1. Go to Settings | Appearance and set it to follow the windows accent color 

2. Close Dopamine 

3. Re-open Dopamine 

4. Go back to Settings | Appearance and you'll see it immediately reverts back to the default blue color (and you have to toggle follow windows color off and then back on to get it working again).

**Comment by Magentaize** [comment]
It cannot be verified here.

**Comment by digimezzo** [comment]
This cannot be reproduced
