### ISSUE TITLE
"Loop Once" Loops The Same Track Endlessly

### ISSUE THREAD

**Issue by Alamer99** [digimezzo/dopamine-windows#461]
Settings The Loop Mode To Loop Once Loops The Same Track Over and Over

Produce:
1. Play a Track
2. Set Loop Mode to Loop Once

**Comment by digimezzo** [comment]
Isn't that how it is supposed to work? It's called "loop one". It loops the current song. If I remember correctly that's how other players do it also.

**Comment by Alamer99** [comment]
i checked wikipedia after seeing your comment and you are right, thats how its supposed to work
for some reason i thought that "loop once" is meant to repeat every song "once more" and then continue
sorry for the inconvenience
