### ISSUE TITLE
Opus support

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#462]
Hi, I've been using this app for the past few months without even knowing it was open-source. And again, was surprised by this. Every time I switch to a FOSS solution it's a hundred times better than the proprietary one. Thank you for this amazing player!

Now that I said that I miss just one feature to make it perfect and that is the **Opus** codec maintained by **xiph.org**. As you may know it reaches transparency at about **128kbps** which is pretty amazing. It also has the best quality at anything lower than that bitrate. Compared to any other codec it blows them out of the water. It's worth mentioning that it boasts the lowest latency and is suitable for speech but that's not really applicable here. But if Dopamine ever gets streaming capabilities Opus is a must have with it's quality at such low bitrates.

Anyway, I like keeping my music in FLAC format but for the other albums/songs that I don't listen to that much or just need to reduce storage usage I'd like to convert them to Opus, but since I can't play them easily on Windows (not many Opus players with such a well designed interface) I won't for now.

I hope this gets considered for the foreseeable future of this player. I mean, even if it doesn't I still love it and recommend it to my friends. Thanks again.

**Comment by digimezzo** [comment]
Fixed in 4cf4bea2f4a3d39499ef089414f89451c2770d3a
