### ISSUE TITLE
Crashes When Attempting to Jump to Albums Using Keypresses

### ISSUE THREAD

**Issue by Zeph72** [digimezzo/dopamine-windows#464]
If I click on an album, and then press a letter key that would cause the album list to jump to an album above or below those currently visible, Dopamine usually crashes.

Occasionally it doesn't, but I've yet to find a consistent identifier for when it won't. I can usually get away with pressing certain letters without a crash - for me, those seem to be A and C - but even that doesn't seem consistent, as I've had at least one instance of a crash after pressing C.

Running Windows 7 x64, Dopamine version 1.3.0.927.
In any case where the crash occurs, the error in the log file appears to be the same; I diffchecked a few of them and found them to be identical (except for the time, of course).

> 2017-07-25 13:33:00.702|Error|App.xaml.ExecuteEmergencyStop|Unhandled Exception. Exception:
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
>    at Digimezzo.WPFControls.VirtualizingWrapPanel.BringIndexIntoView(Int32 index)
>    at System.Windows.Controls.ItemsControl.MakeVisible(Int32 index, FocusNavigationDirection direction, Boolean alwaysAtTopOfViewport, FrameworkElement& container)
>    at System.Windows.Controls.ItemsControl.NavigateToItem(Object item, Int32 elementIndex, ItemNavigateArgs itemNavigateArgs, Boolean alwaysAtTopOfViewport)
>    at System.Windows.Controls.TextSearch.DoSearch(String nextChar)
>    at System.Windows.Controls.ItemsControl.OnTextInput(TextCompositionEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
>    at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
>    at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Stack trace:
>    at Digimezzo.WPFControls.VirtualizingWrapPanel.BringIndexIntoView(Int32 index)
>    at System.Windows.Controls.ItemsControl.MakeVisible(Int32 index, FocusNavigationDirection direction, Boolean alwaysAtTopOfViewport, FrameworkElement& container)
>    at System.Windows.Controls.ItemsControl.NavigateToItem(Object item, Int32 elementIndex, ItemNavigateArgs itemNavigateArgs, Boolean alwaysAtTopOfViewport)
>    at System.Windows.Controls.TextSearch.DoSearch(String nextChar)
>    at System.Windows.Controls.ItemsControl.OnTextInput(TextCompositionEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
>    at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
>    at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Loving Dopamine, by the way - been looking for a desktop music library program with both a good user interface and little bloat for a long time. Thanks for all the hard work!

**Comment by Magentaize** [comment]
This problem happened in VirtualizingWrapPanel.cs:218 of WPFControls, whether it indeed need a range verification should be considered more.
