### ISSUE TITLE
Bugs while playing music

### ISSUE THREAD

**Issue by TragicLifeHu** [digimezzo/dopamine-windows#467]
Notice:My English is very POOR.SORRY for my wrong grammars.
OS:Windows 10 Pro Creator Update 1703
CPU:AMD A8-6410 APU With AMD Radeon R5 Graphics
RAM:4GB
Language:Chinese Simplified
Issues:Almost every music of mine is .wav or .flac format.When one audio finished,it will make some noise just like hissing.....Why did it happened?
------------------------
Google Translated Version
When a song is played, I will hear some noise like hissing. This will appear after the .flac and .wav format songs have been played. What is the problem?

**Comment by Magentaize** [comment]
You'd better to upload your music file.

**Comment by 2JayCee** [comment]
Try playing those files with other audio players to see if it's the file itself first or the program.

**Comment by Magentaize** [comment]
I have reproduced, it's the problem of CSCore and special encoders. You'd better re-encode these files with the latest encoders.

**Comment by digimezzo** [comment]
The next Dopamine release will use another decoder (FFmpeg). Please try again once that version is released (should be in a few days).
