### ISSUE TITLE
Add Rainmeter support

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#478]
Requested by a user:

Do you know Rainmeter ? quite a nice desktop widget tool for Windows 10. Their music player plugin does not support Dopamine or vice-versa. But if anyone wants to update the plugin... just floating the idea ;)
 
Featuring here the nano player - I love it !! 

![598798bf4c1b7_screenshot2017-08-0618_29_01 thumb jpg e80e67625dbc58ad222b888a02a45300](https://user-images.githubusercontent.com/11945339/29074123-6b27e42a-7c4e-11e7-81cf-1364a4046f1d.jpg)

**Comment by Riajyuu** [comment]
dup of #252 ?

**Comment by digimezzo** [comment]
Yes indeed. I missed it. I'm closing this issue in favor of #252.
