### ISSUE TITLE
I have transplanted Prism.WPF to Prism.Windows

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#487]
The most important two functions ModuleCatalog and RegionManager both can work now and I only have tested a little with Dopamine.UWP, `IRegionManager.RequestNavigate` works well.
Link: https://github.com/Magentaize/Prism

**Comment by digimezzo** [comment]
That's amazing. Did you push this to the prism team?
I'll probably try to avoid using RegionManger in Dopamine.UWP. I made the mistake to overuse it in the Dopamine project and it became a big mess.

**Comment by Magentaize** [comment]
No, in other platform of Prism, it uses a different navigation system which uses the whole page instead of many regions. I have developed some UWP apps, and I have to say this Page navigation in UWP is so inconvenient and not flexible compared to WPF and all components will be loaded on startup not lazy load. But it's the best if you can find a better way to design the view architecture.
