### ISSUE TITLE
[Bug] Dopamine Auto Refreshes Library Even When Disabled

### ISSUE THREAD

**Issue by 2JayCee** [digimezzo/dopamine-windows#488]
![capture](https://user-images.githubusercontent.com/7156758/29856041-2153808a-8d05-11e7-911f-c090e75d5567.PNG)

I have Dopamine's auto-refresh disabled (since it takes far too long for the Collection to finish refreshing for some reason/this should be addressed to at some point).  

Every time I open Dopamine, and venture to the settings, Dopamine auto-refreshes the Collection.  I'm not sure if it's actually doing it or it's just simply displaying the refresh animation because of a bug, I'm not entirely sure.

**Comment by digimezzo** [comment]
I'll check it out. To assess why it takes so long to refresh, could you tell me how many songs are in your collection? Could you attach the log file?

**Comment by 2JayCee** [comment]
[Dopamine.txt](https://github.com/digimezzo/Dopamine/files/1265051/Dopamine.txt)
23256 are the total amount of songs I have.
