### ISSUE TITLE
[Feature Request] Album Art Next to Playlist Items

### ISSUE THREAD

**Issue by 2JayCee** [digimezzo/dopamine-windows#490]
# **Concept** (As Featured in Vox for iOS)
![img_0311](https://user-images.githubusercontent.com/7156758/30078674-e1dd2446-9232-11e7-8767-61560dc515b4.PNG)

# **Current**
![capture](https://user-images.githubusercontent.com/7156758/30078696-f425bbd6-9232-11e7-9db0-6faf27b03f17.PNG)

Would it be possible to have an option to enable Album Art Covers next to playlist items?

**Comment by digimezzo** [comment]
That has been implemented in version 1.4. The first 1.4 preview will be available today.
