### ISSUE TITLE
[Bug] Adding Song to Existing Playlists Clears Playlist

### ISSUE THREAD

**Issue by 2JayCee** [digimezzo/dopamine-windows#491]
1. Open Dopamine

2. Play Song

3. Right Click on Song that is Currently Playing and Add to Playlist.  

4.  All Songs in Playlist are removed and say 0 exist.  

(Closing Dopamine and re-opening fixes and adds songs back to Playlist including the newly added song).

Log File:
[Dopamine.txt](https://github.com/digimezzo/Dopamine/files/1278689/Dopamine.txt)

**Comment by digimezzo** [comment]
I can't reproduce this here. Are there other specific thing that you did to reproduce this issue?

**Comment by 2JayCee** [comment]
Actually, I found the "issue".  I had searched something to view a certain album.  Added a song then went to the playlist.  The search was still active and affected the playlists making me think it was glitched.  Clearing the search bar revealed the "missing" files.
