### ISSUE TITLE
Dopamine 1.4.0.952 doesn't start on non-Windows 10 systems

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#502]
For some reason the new preview version doesn't start on my system. The process closes within 1-2 seconds. Any ideas?

**Comment by Riajyuu** [comment]
No here.

**Comment by digimezzo** [comment]
I'll need the log file to figure that out. Could you send it to me?

**Comment by Keith94** [comment]
Here you go: [Dopamine.log](https://github.com/digimezzo/Dopamine/files/1339488/Dopamine.log)

**Comment by digimezzo** [comment]
OK I found the cause of the error in the logs.

> 2017-09-27 21:37:05.865|Error|App.xaml.ExecuteEmergencyStop|213|Unhandled Exception. Exception:
> Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "Dopamine.Views.Shell", name = "(none)".
> Exception occurred while: Calling constructor Dopamine.Common.Services.Notification.NotificationService(Microsoft.Practices.Unity.IUnityContainer container, Dopamine.Common.Services.Playback.IPlaybackService playbackService, Dopamine.Common.Services.Cache.ICacheService cacheService, Dopamine.Common.Services.Metadata.IMetadataService metadataService).
> Exception is: TypeLoadException - Could not find Windows Runtime type 'Windows.Media.Playback.BackgroundMediaPlayer'.

It is caused by the support for system notifications in Windows 10. You OS is Windows 8. The code is looking for something that doesn't exist on non-Windows 10 systems. I'll need to fix that.

**Comment by digimezzo** [comment]
The code checks if you're using Windows 10 and shouldn't execute the failing part if Windows 10 is detected correctly. So I suspect that my Windows 10 check has a problem. To verify that, could you download build 953 here: [https://www.dropbox.com/sh/b5ixkfxhf7d8x0s/AABy0uGFmLTV3FAy04O2PkZha?dl=0](https://www.dropbox.com/sh/b5ixkfxhf7d8x0s/AABy0uGFmLTV3FAy04O2PkZha?dl=0)

You can install that build over 952 (Next time a preview comes out, you can just install that preview without caring about build 953. It will be overwritten by the new preview).

Please start Dopamine build 953 and send me the log file that it generates. Thanks!

**Comment by Keith94** [comment]
Here's the full build 953 log: [Dopamine.log](https://github.com/digimezzo/Dopamine/files/1339623/Dopamine.log)

**Comment by digimezzo** [comment]
Did Dopamine 953 also crash? As I find it strange that there is no mention of it in the log. Could you verify the log again (just in case something else was added)?

**Comment by Keith94** [comment]
Now the log has more info (after several tries). Check it: [Dopamine.log](https://github.com/digimezzo/Dopamine/files/1339674/Dopamine.log)

**Comment by digimezzo** [comment]
@Magentaize It seems that adding the Windows 10 system notifications API broke compatibility with non-Windows 10 versions of Windows. I'm not sure why, as there is a check for Windows 10 in the code of NotificationService, which prevent initializing of a Windows.Media.Playback.BackgroundMediaPlayer object.  Do you have an idea?

**Comment by Magentaize** [comment]
This might be a little more hard, all codes are hard-linked during compiling (not as the same as making window transparent), so, I think it should dynamically load objects.

**Comment by Magentaize** [comment]
To avoid using reflection, it may be better to create another NotificationService for win8. In bootstraper, it injects different instance of INotificationService according to the system.

**Comment by digimezzo** [comment]
I agree about using a different NotificationService. That looks like a clean solution.

**Comment by digimezzo** [comment]
The bug is fixed. Spread the code of NotificationService between LegacyNotificationService (which is used on non-Windows 10 systems) and NotificationService (which is used on Windows 10 systems). Injection into unity, checks which type of system the user is running.
