### ISSUE TITLE
[Bug] 1.4 (Build 952) Dopamine resizes behind start taskbar

### ISSUE THREAD

**Issue by 1suky1** [digimezzo/dopamine-windows#503]
When I want to open dopamine from the notification area icon by double clicking it resizes the window behind the taskbar.

Steps: 

1. Close or minimize dopamine
2. Double click on notification area icon
3. Window is resized behind start bar

**Comment by digimezzo** [comment]
Could you provide more details? I can't reproduce this here. I started with a non-maximized as well as a maximized window, and then followed your procedure. The Window resizes fine.

**Comment by 1suky1** [comment]
Here you go https://gyazo.com/9eb97381792a41d71cb1d2293c9884f1

I have all 3 "Notification area" option enabled. https://i.imgur.com/H5ds2Gz.png

Window is maximized. Then I either minimize it or close it and it closes to the notification area. Then if I double click on the icon it opens the window but expands behind the start bar.

If I do right click -> Show Dopamine it opens normally, same if I open it through pinned icon on start bar.
