### ISSUE TITLE
Check for updates settings

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#516]
Hi,

Would it be possible to separate, in settings > start up > updates, the "check for updates (at start up and every 15 minutes" option in two? I would like for the app to check for updates when I launch it, but not to call home every 15 minutes to check if there is a new build. 

Thanks and great app!

**Comment by digimezzo** [comment]
Yes, that makes a lot of sense. I'll definitely do that in one of the next previews.
