### ISSUE TITLE
Color interpolation is broken

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#542]
I made slight modifications to the ApplyColorSchemeAsync function in AppearanceService (mostly removing the isViewModelLoaded boolean). Color interpolation works just after Dopamine startup. But after a while (quickly, but unpredictable when) interpolation stops working. When choosing another accent color, instead of interpolating, it seems to wait a few seconds, and then directly switches to the new color without interpolating.
I'm not sure yet what caused this and might revert to the code before my modification if this is not found out.

**Comment by digimezzo** [comment]
Reverting to the code which uses isViewModelLoaded doesn't fix the issue.

The issue is reproducible when browsing through all the Dopamine screens, and then trying to change the accent color. I suspect there are too many active screens to refresh and causes the animation to fail?
The different with older versions of Dopamine is that we now use a pivot to display screens. All screens remain active now. In the past Prism regions were used. Inactive regions, which could have caused less screens to be active.

**Comment by Magentaize** [comment]
I reverted to commit 2f195997, color interpolation works well.

**Comment by digimezzo** [comment]
The interpolation code was OK (I removed the timer though, and am now using async await. The code performs the same as with the timer). 

There seems to be a performance issue. This was done to reproduce it:

- Make sure there are a lot of songs (I tested with 3000)
- Click on all headers in the collection section (artists, albums,...). Make sure you opened all screens.
- Go to the settings and try to choose another accent color

You should see that it takes a few seconds before the color changes. And the color doesn't interpolate. Approximately 5 seconds after choosing a new color, the color jumps to the new color.

I'm not sure yet what causes this. I suspect it has to do with the number of DynamicResource references to RG_AccentBrush in all the screens. As it only happens when all screens have been opened AND when there are a lot of songs in the lists. The pivot control is based on the WPF TabControl, which unloads tab content when a tab is not active. I verified that this is still the case in the Pivot. So it's a bit strange that there suddenly is a performance problem.

The interpolation works fine when only 1 collection screen was opened before changing the color.

I'm reopening the issue, as it is interesting to investigate further. In commit 3bea9ef1aa279b78c1bf7b096ca90e239fc6f1fc I adjusted the interpolation timings, so that the new code with async await performs the same as the older code which used the timer. So you don't have to revert to an older version to see the issue.

**Comment by digimezzo** [comment]
I'm currently trying to restore UI performance by using Prism regions again. Although I'm trying to keep the code as clean as it was when using the Pivot. Using Prism regions seems much more performant. And the color interpolation works much better again. I'll commit the changes tomorrow.
