### ISSUE TITLE
not starting after initial setup when language other than EN

### ISSUE THREAD

**Issue by KrayZeee** [digimezzo/dopamine-windows#559]
Hello Devs,
i have a small but anoying problem with the current source. when removing dopamine folder in %appdata% dopamine boots fine, is able to set everything up play my music with an UI in my prefered language. but as soon i close the player and open it again it crashes. by setting the language in the settingsfile to EN dopamine boots fine again. 

log in the attachment
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1488057/Dopamine.log)

**Comment by KrayZeee** [comment]
thanks for the quick fix. @digimezzo you are awesome mate ;)

**Comment by digimezzo** [comment]
Fixed by 48612603b835a4d52b50b5cb09885aab1c4c97af.
You're welcome!
