### ISSUE TITLE
Korean language file is missing in 1.5.x.

### ISSUE THREAD

**Issue by Blizzardfall** [digimezzo/dopamine-windows#565]
New strings are left untranslated when I updated to 1.5.2, so checked all three 1.5.x versions but only 20 language files are included in it, which means Korean is the only language that removed.

**Comment by digimezzo** [comment]
Thanks for notifying me! Apparently is was in the portabe version, but ot the installable version.

**Comment by Blizzardfall** [comment]
It's missing in both portable and install version.
![2017-11-22_00-05-56](https://user-images.githubusercontent.com/19769002/33079479-0a0a6bfe-cf19-11e7-8295-bdbcc95bec1d.png)

**Comment by digimezzo** [comment]
Fixed in 0c02487584d73758a1170c6beb72a528120b0a9e
