### ISSUE TITLE
cannot play music with special character in filepath

### ISSUE THREAD

**Issue by KrayZeee** [digimezzo/dopamine-windows#567]
title says it all
v1.5.2.0

this looks like cscore related, but maybe there is a workaround.

> 2017-11-21 18:21:53.825|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\KoЯn\(1994) KoЯn\1 - KoЯn - Blind.mp3. EventMode=False, ExclusiveMode=False, LoopMode=All, Shuffle=False. Exception: avformat_open_input returned 0xffffffea: Invalid argument. StackTrace:    bei CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)
>    bei CSCore.Ffmpeg.AvFormatContext..ctor(String url)
>    bei CSCore.Ffmpeg.FfmpegDecoder..ctor(String url)
>    bei Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
>    bei Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
>    bei System.Threading.Tasks.Task.Execute()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__184.MoveNext()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__185.MoveNext()

**Comment by digimezzo** [comment]
I think this might be related to #563

**Comment by KrayZeee** [comment]
@digimezzo 
i digged a bit through the code and got it to work by changing the parameter of the ffmpegdecoder ctor from stringtype to streamtype, which is available as overload at cscore

line 242 cscoreplayer.cs:
> Stream str = File.OpenRead(this.filename);
> IWaveSource waveSource = new FfmpegDecoder(str);

i tried to encode the filepath but unfortunatly didnt want to work

**Comment by KrayZeee** [comment]
i have send a pullrequest #568

**Comment by digimezzo** [comment]
Nice find! I've merged the pull request and will do some tests here. I suspect this is an issue in how cscore processes the path, but I'll have to look more in detail. If this change is as performant, it is a nice workaround.

**Comment by digimezzo** [comment]
This seems to fix all 3 reports of unplayable files that I got since the release of version 1.5. These were the file names:

クラブナイトメア.mp3
I.O.I - miss me_ [FLAC]1 너무너무너무.flac
クラブナイトメア.mp3

The performance seems good.

**Comment by KrayZeee** [comment]
well i am less concerned about small files but more about bigger files.
c# isnt my first language i dont know how exactly it handles copy vs reference and if file.open.read read the whole file or just metadata on ctor. big files on slow hardware could possibly result in delayed start of song

**Comment by digimezzo** [comment]
I don't have enormously large files, but I tested with a 32 MB flac file, playing from a NAS (which is rather slow). The file played instantly. I'll try with a larger, merged file.

**Comment by digimezzo** [comment]
I've tested with a 600 MB flac file which I created by merging all files of an album twice. It plays instantly too. Let's try to publish with that workaround and see how the world reacts :)

**Comment by KrayZeee** [comment]
jea i did meanwhile a few tests myself. got my slowest usbdrive ~5mb/s put a 150 mb flac on it, plays indeed instantly
