### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by usyboi** [digimezzo/dopamine-windows#573]
since the update 1.5.2 dopamine have been consuming about 1.3 GB of ram it makes the PC slower. is this normal or what ?

**Comment by digimezzo** [comment]
It's not supposed to be that high. How large is your collection? Are there specific actions that you perform which cause the memory increase? That info would help track down potential memory leaks.

**Comment by usyboi** [comment]
i have about 1700 tracks - 17GB and i just open it and it just consumes upto 1.4GB of ram
![capture](https://user-images.githubusercontent.com/9163313/33147648-2d5f72ee-cfd1-11e7-9a75-fb785acbfb6d.PNG)

**Comment by digimezzo** [comment]
How much total RAM do you have on your computer? I'm just trying to understand. On mine, it uses approx 100 MB of RAM with 3000 tracks.
Did you use older version of Dopamine before and did they use less RAM?

**Comment by usyboi** [comment]
i have 8GB of Ram 
i tried with the older version i have which is v1.3.0.927 - Portable i just opened it and here is the usage it is about 150mb
![capture](https://user-images.githubusercontent.com/9163313/33178163-d33559d0-d06d-11e7-9c02-6f55b3eff223.PNG)

**Comment by usyboi** [comment]
updated to 1.5.3 fixed it
