### ISSUE TITLE
chocolatey package - bad url, old version

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#575]
Hello, the choco package for the player is outdated, and the download url is not working anymore.

https://chocolatey.org/packages/dopamine

Are you affiliated with the maintenance of this package?

**Comment by digimezzo** [comment]
No, I have noting to do with them.

**Comment by kbalint** [comment]
I stepped up as a co-maintainer of the package, so the latest version has been added as a new package.

**Comment by digimezzo** [comment]
Excellent, thanks! :)
