### ISSUE TITLE
Logitech SetPoint: media keys don't work

### ISSUE THREAD

**Issue by ecdesa** [digimezzo/dopamine-windows#578]
version: 1.5.4

The changelog says that the media keys are fixed, but only next and prev keys are fixed.
play/pause and stop still don't work.

**Comment by digimezzo** [comment]
That's strange. All media keys work here, also Play. What type of keyboard do you have? Is it a Logitech? I know that logitech drivers sometimes interfere with media keys.

Could it be a similar issue; https://superuser.com/questions/338108/how-do-i-get-my-logitech-media-buttons-to-control-spotify

**Comment by bwat47** [comment]
Mine weren't working in 1.5.3 (including play/pause), but I can confirm play/pause is now working for me in 1.5.4 (with a corsair k40)

Stop still doesn't seem to do anything for me though (I never use stop though so I'm not sure if that was even working at any point in the past)

**Comment by digimezzo** [comment]
@bwat47 Thanks for confirming that they work in 1.5.4. I made a mistake in 1.5.3 that broke them. But I corrected the mistake it in 1.5.4.
Stop is not mapped at the moment, as I don't provide a stop button.

**Comment by Alexander12444** [comment]
Can confirm it's a Logitech issue, specifically when automatic game detection is enabled. Switching to on-board memory fixes the issue, as does using another brand of keyboards media keys.

**Comment by Anime37** [comment]
Ah i guess i'll wait til you start providing a stop button support :P

**Comment by hypnotiqiv** [comment]
I have a Corsair k70 with the same issues. Im using F9-F12 as media keys, Next/Previous both work fine, Play/Pause is goofed. It works like 1 in 1000 times randomly, but almost never.

**Comment by Chealer** [comment]
This seems quite similar to the bug reported in ticket #859, or maybe in #743 which mentions intermittency.
