### ISSUE TITLE
UWP Version

### ISSUE THREAD

**Issue by 10Dev** [digimezzo/dopamine-windows#59]
I don't see this on a quick glance through the issues and I know you have been thinking about it, so this issue permits a discussion of sorts.

One of the interesting decisions would be maximizing common code between WPf and UWP, something Microsoft should be doing.

And it also leads opening the consideration of  using Xamarin to add in Android and IOS but that also skews the architecture another whole notch if maximum common code is a desirable item.

**Comment by digimezzo** [comment]
A UWP version is in the works. However, code maximization between WPF and UWP projects proved to be harder than I thought. The API's are quite different.

**Comment by 10Dev** [comment]
Implements some UWP controls in WPF:
https://github.com/dotMorten/UniversalWPF

Implements a WPF control in UWP:
https://github.com/rickapps/UWP-UniformGrid-Control

Some controls implemented for both WPF and UWP:

https://github.com/sourcechord/ResponsiveGrid

https://github.com/terrence0488/CreativeXamlToolkit

https://github.com/FantasticFiasco/mvvm-dialogs

https://github.com/Meowtrix/Xaml.Extend

https://github.com/durow/AyxWaveForm

https://github.com/charri/Font-Awesome-WPF

A cross platform Xaml  UI that might have something useful:
https://github.com/AvaloniaUI/Avalonia

**Comment by digimezzo** [comment]
UWP version is cancelled and all UWP code was removed from the repository.
