### ISSUE TITLE
Drag-and-drop .opus doesn't work

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#590]
### Steps to reproduce
1. Create new playlist
2. Drag-and-drop .opus file from Windows Explorer to playlist

### Actual results
Drag-and-drop operation doesn't work

**Comment by digimezzo** [comment]
That's normal. Opus is not yet supported.

**Comment by Keith94** [comment]
That's unfortunate since I've converted many of my .flac to Opus format now... please add support soon

**Comment by digimezzo** [comment]
Do you have an opus file that you could share with me (preferably a file which is properly tagged)? I want to test if taglib can read/write tags to opus files.

**Comment by Keith94** [comment]
I sure do, give this one a try: [opusTrack.zip](https://github.com/digimezzo/Dopamine/files/1530064/opusTrack.zip)

Let me know if that works or if you need anything else :)

**Comment by digimezzo** [comment]
Thanks for the file. Bad news, taglib can't read tags from it. I'll have to look for another tagging library.

Edit: there might be hope. If I understand correctly, taglib#'s Github has support for Opus. I'l try to compile from source.
Edit2: ok that works. I've added support for Opus.

**Comment by Keith94** [comment]
Thank you for adding support!

You can close #462 too.
