### ISSUE TITLE
About UWP version

### ISSUE THREAD

**Issue by schwarzichet** [digimezzo/dopamine-windows#598]
I wonder whether there exist possibility that a UWP version of Dopamine will be provided.

**Comment by digimezzo** [comment]
Short answer: no.

Long answer: a UWP version was planned a few month ago and I even started development. The main goal was to have a Mobile Dopamine, with the added plus of being compatible with the Windows 10 desktop thanks to the power of UWP. 

When Microsoft killed mobile, I decided to cancel it. To me, UWP makes no sense without a mobile tier. My time is better spent on improving the current Dopamine and creating more cool WPF applications.

**Comment by schwarzichet** [comment]
That's reasonable. Thank you for such a good music player.
