### ISSUE TITLE
A small duration of music plays after restart.

### ISSUE THREAD

**Issue by RobH99** [digimezzo/dopamine-windows#603]
Hello!  I just want to say that I think Dopamine is superb.  You have done really well with this.  You will definitely be getting a donation from me. 

A small observation - Using W10 and Dopamine set to the 'default playback device' I am getting a small pulse of music whenever I start dopamine up after pausing the music and closing down Dopamine previously.  I believe it is from the track that I was playing last.  No major problem, but it makes me jump sometimes.

~~This leads me to a feature request - is it possible to have a setting for fade out and fade in on pause and resume of music?~~

~~Also, like some others have requested, the text looks a bit small on my monitor, so it would be great to be able to adjust the typeface size on the main screens and maybe the showcase screens etc.~~

Anyway, thanks very much for taking your time to develop Dopamine.  It is now becoming noticed and you deserve every bit of praise for the looks and functionality of the program - you have got it just right.  I will be following development really closely from now on and will look forward to downloading every new release.

Rob H.

**Comment by digimezzo** [comment]
The small duration of music playing after restart should be fixed in the next version. If not, let me know.

I've split up your feature requests into: #612, #613.

**Comment by RobH99** [comment]
Superb - Thank you very much!
