### ISSUE TITLE
Crashing on win7 pro!

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#608]
When i try to play a song on win 7 pro the program crashes, here is the report:
 
 Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	Dopamine.exe
  Version de l’application:	1.5.5.0
  Horodatage de l’application:	5a299daf
  Nom du module par défaut:	StackHash_08bb
  Version du module par défaut:	6.1.7601.23539
  Horodateur du module par défaut:	57c99842
  Code de l’exception:	c0000374
  Décalage de l’exception:	000c3b03
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	08bb
  Information supplémentaire n° 2:	08bbc13cfd9432b44c6332b198900aa0
  Information supplémentaire n° 3:	182a
  Information supplémentaire n° 4:	182ac94d7a6f55a7e6ce7756e792f676

**Comment by digimezzo** [comment]
Can you attach the log file?

**Comment by ghost** [comment]
Here it is:
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1564771/Dopamine.log)

**Comment by digimezzo** [comment]
Thanks! I see what's going on and will fix it for the next minot release.
