### ISSUE TITLE
No rear speakers

### ISSUE THREAD

**Issue by RobH99** [digimezzo/dopamine-windows#611]
Possible bug - trying everything to get around it - no sound from rear speakers when using Dopamine on my Quadraphonic speaker setup - sound from front speakers only.

W10 64 Creators Update
Dopamine Settings > Playback = Default audio device.

Realtek HD audio manager set to 'Quadraphonic'.

Windows Media Player, AIMP, MusicBee, all play to front AND rear speakers.  Dopamine only plays to the front speakers.  

Aimp and MusicBee set to Directsound Windows Default / Primary Sound Driver.

No change when selecting 'Speakers (Realtek High definition audio)' within Dopamine, which is also the default output set from 'Windows Playback Device'.

**Comment by RobH99** [comment]
I am investigating this further because I have a similar computer and audio system in the lounge, and Dopamine is playing perfectly through all four speakers on that computer.  It also just updated to W10 creators update, and it is still fine.  Very strange!

**Comment by RobH99** [comment]
Computer differences
------------------------
Intel i7 with Realtek High Definition Audio - **Cannot get Dopamine to play to rear speakers**.
Intel i5 with Soundblaster Audigy 5 DX - Dopamine plays perfectly to rear speakers.

In Common
--------------
Both computers latest W10 64 bit Creators Edition updates (December).
In Dopamine, both computers set to 'Default audio device', Latency 200ms, Exclusive mode OFF, 
Dopamine Information - Both computers - 'Sound is played through the Windows Audio Session API (WASAPI).
A number of other music players play to all four speakers on both computers.

Tried so far
------------
All audio drivers updated as far as I can go and fully rebooted computer a number of times.
Adjusted settings in Windows playback devices and Realtek HD audio manager - I notice a change in one interface immediately applies to the other, so settings are changing.  Tried many speaker configurations, quadraphonic, 5.1, 7.1 etc.

**Comment by filoe** [comment]
@digimezzo Try to set `UseChannelMixingMatrices` (see [github](https://github.com/filoe/cscore/blob/master/CSCore/SoundOut/WasapiOut.cs#L424)) to true.

**Comment by RobH99** [comment]
Latest:
-------
Totally deleted all sound drivers (found some for my 1070i graphics card on the system, although I think they only play through the HDMI connection and I have never used them.)

Realtek drivers were completely cleaned off before reinstall.   Reinstalled Realtek latest sound drivers and set up the system to 'quadraphonic' again - result the same unfortunately.  

After reinstall, all other music players play to front and rear speakers.

I have to say I am not convinced this is purely a Dopamine problem, as Dopamine plays to rear speakers on my other computer.

**Comment by filoe** [comment]
Of course it is a Dopamine "problem". 
The stereo or mono file has to be mapped to all channels. Is is possible as described above.

**Comment by digimezzo** [comment]
Hi all. Thanks for reporting and investigating this. @filoe, thanks for pointing that out. As I don't have a 4 speaker system, I can't test this out. So I created a testing release which has `UseChannelMixingMatrices `on true. This was added in commit 370e4c5ef318d86aa8e1b7c8d8c4ebd894a9b241. @RobH99, could you download the installable or portable 1.5.5.1 TEST version here: [http://www.digimezzo.com/content/software/dopamine/](http://www.digimezzo.com/content/software/dopamine/) and confirm if that resolves the issue.

**Comment by RobH99** [comment]
**IT WORKS!**  Superb!  

Thanks to Filoe and of course Digimezzo for working on this and finding the fix.

As a side note, I discovered the other computer was sending the music to the rear speakers because it had a separate Soundblaster sound card application that was 'mixing' the sound feed to all speakers.
I don't have access to this application on my main computer due to having a different sound card.

Thanks once again.

Rob

**Comment by RobH99** [comment]
It works!  Thank you so much for fixing this.  I have posted on GitHub also.

Rob

**Comment by digimezzo** [comment]
@RobH99 Thanks for confirming! :) This fix will be in the upcoming 1.5.6 release (due in a few days). You can safely keep the TEST release until then. It will upgrade to 1.5.6 seamlessly.

**Comment by RobH99** [comment]
Excellent!  Thanks once again and I wish you a Happy New Year for 2018!

**Comment by filoe** [comment]
Would suggest to create an extra option to enable or disable that feature.

**Comment by digimezzo** [comment]
@filoe: good idea. I've added it in 0156c1007fc208b2086f2cbecaebfd47ed8739ca
