### ISSUE TITLE
Provide GPG sig to verify binary

### ISSUE THREAD

**Issue by beerisgood** [digimezzo/dopamine-windows#623]
With GPG (https://en.wikipedia.org/wiki/GNU_Privacy_Guard) we can check if the binarys are realy from you.
See it as digital signed binary alternative

We just need your GPG Key ID (you need to publish the public key at official GPG key server or post the whole public key here) + the fingerprint to verify the key.
Then you just need to sign every binary and upload the signed (.sig) file too.

**Comment by Riajyuu** [comment]
I don't think it is necessary since this isn't anything security sensitive.
Perhaps free SSL from Let's Encrypt will ensure you will get a **real** installer.

**Comment by digimezzo** [comment]
While I understand why such mechanism exists, it is overkill in the case of Dopamine. This won't be implemented. However, #448 is taken under consideration, if it can be implemented without a need for a manual action.
