### ISSUE TITLE
Lyrics couldn't scroll

### ISSUE THREAD

**Issue by Youxikong** [digimezzo/dopamine-windows#625]
Dopamine version: 1.5.6
System version: Windows 10 Insider Preview Build 17063
.Net version: 4.7.03036
This is what log shows:
> 2018-01-06 23:42:26.246|Error|LyricsControl.xaml.ScrollToHighlightedLyricsLineAsync|82|Could not scroll to the highlighted lyrics line. Exception: 无法将类型为“Dopamine.ViewModels.Common.LyricsLineViewModel”的对象强制转换为类型“Dopamine.Presentation.ViewModels.LyricsLineViewModel”。

**Comment by digimezzo** [comment]
Could you send me that audio file which has the problematic lyrics?

**Comment by Youxikong** [comment]
[Audio File Sample](https://1drv.ms/u/s!AkgmYyoB5MvQwBXsdUa4Lti2cD9S)
Exactly all lyrics embeded in all audio files (mp3 or flac) couldn't scroll **to the highlighted line**. I think it is a bug.

**Comment by digimezzo** [comment]
Thanks for the sample. I downloaded it and will verify what is going on.
