### ISSUE TITLE
How to post the update for a localization file properly?

### ISSUE THREAD

**Issue by pva-br** [digimezzo/dopamine-windows#627]
Hi. 
I've edited the Brazilian Portuguese language file and translated some (not all, but most of them) of the lines that were added in version 1.5.6 but weren't localizated yet. I'm a newbie to git-hub and would like to know how to post it properly to the developers. Should I click "Commit directly to the master branch" or "Create a new branch for this commit and start a pull request"?

Thanks in advance.

**Comment by digimezzo** [comment]
You can just fork this repository and send a pull request.

**Comment by pva-br** [comment]
Hi!

I just sent the changes now. I hope I have uploaded it to the right place. 

Thank you, @digimezzo .

**Comment by digimezzo** [comment]
Yes, you did it correctly. Thanks!
