### ISSUE TITLE
Dopamine stops working randomly when lyrics mode is displayed

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#628]
Like title says, you usually can see **lyrics** without no **problem** until a random ammount of time.
When that time happens, **Dopamine stops working**.
I also **can't edit lyrics** sometimes.
The most curious thing is that my computer recently got upgraded to Windows 10, but in **Windows 8.1** that feature worked with **no problems**.

System Specs: 

- OS: Windows 10 Pro x86_64
- RAM: 8gb DDR3
- Graphic chipsets: 
    1. Intel HD graphics 5500
    2.  Nvidia geforce 820m(2gb)
- Dopamine Version: 1.5.6

> Sidenotes: I'm using Dopamine with my Intel HD graphics, but same problem occurs with my Nvidia.

**Comment by ghost** [comment]
UPDATED: It's getting worse, I can only get working with no problems "songs tab" under "collection"
Please, any help would be appreciated.
Thanks you.

**Comment by digimezzo** [comment]
Please attach the log file

**Comment by ghost** [comment]
[Dopamine (2018-01-11 04.18.52.442).log](https://github.com/digimezzo/Dopamine/files/1622986/Dopamine.2018-01-11.04.18.52.442.log)
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1622987/Dopamine.log)

**Comment by ghost** [comment]
I also have an apng file that shows both problems, you'll only need to download it and open that in a web browser like chrome or firefox based :) I'ts an animated png.

https://drive.google.com/file/d/1_0eePOaCBLTbd-52jpafWUV-UhOLcV7G/view?usp=sharing

**Comment by digimezzo** [comment]
~~Could you send me the file in question? I'd like to see the contents of the lyrics and investigate with the file. Thanks!~~

Nevermind, I found the mistake and I am fixing it.

**Comment by ghost** [comment]
Really thanks :D I've never found such a good program like that for playing music, I didn't know of it's existence, but when I knew I felt in <3 with the interface and i'ts ways to be, thanks for that amazing support, I'll never replace that app :D
