### ISSUE TITLE
Sorting by track number is done alphabetically

### ISSUE THREAD

**Issue by bogdan-calapod** [digimezzo/dopamine-windows#632]
Hello,

I've noticed a small bug - when sorting by track number in the Songs view, the numbers are sorted alphabetically, e.g.:

1, 10, 100, 2 instead of 1, 2, 3, ... 10

Thanks for an absolutely *amazing* music player! It honestly revolutionized my music library :)

Platform: Windows 10 Fall Update | x64
Dopamine version: 1.5.7

**Comment by RaceWish** [comment]
Hi,

I just wanted to say that I am also experiencing this issue. The 1.5.9 update didn't seem to have fixed the bug. It would be greatly appreciated if this issue could be resolved soon.

However, I agree that Dopamine is indeed an amazing music player!
