### ISSUE TITLE
Gapless Playback

### ISSUE THREAD

**Issue by RobH99** [digimezzo/dopamine-windows#633]
I have a number of albums where the music track flows from one into the next.
Is this possible with Dopamine?  
At the moment there is a definite gap between the tracks.

This player is coming on just great by the way.  I am sure it will become very popular and mainstream if it continues in this direction and with a few improvements.  I already recommend it to my friends now as it is so simple to use and it looks superb.

Thanks,

Rob

**Comment by digimezzo** [comment]
This is related to #217. I'll close this issue in favor of the other one.
Thanks for liking Dopamine and recommending to it others! :)
