### ISSUE TITLE
Possible issue concerning Album art

### ISSUE THREAD

**Issue by pva-br** [digimezzo/dopamine-windows#648]
Hi,
After upgrading to version 1.5.8, album covers no longer appear in "albums" (see the circle in the image above) **for artists who only have one album** in the media library.  (for artists with more than one, it works as expected). 
Could you please fix it in the next update?

Thanks a lot!

![dopamine](https://user-images.githubusercontent.com/9351094/35477104-79ab99b0-03a3-11e8-9356-3ca2d5daa48d.png)

**Comment by digimezzo** [comment]
I confirm. In an attempt to fix a sporadic crash when displaying albums, this issue was introduced. I'm working on a fix and will release a fixed 1.5.9 version ASAP.

**Comment by digimezzo** [comment]
Fixed in 78049b87af7ea580002564d68478ba49ba255512
