### ISSUE TITLE
Issue with semantic grouping

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#65]
Reported by a user:

In at least one instance, I saw a duplicated letter grouping in the Artists list -- where seven artists under 'V' were in their own group, and one other 'V' artist was in a second 'V' group by itself.

**Comment by mah-qurashy** [comment]
it seems to be related to searching
when i search for an artist that starts with letter A the A group will always split
does the same thing for genres list

**Comment by digimezzo** [comment]
Thanks for the extra info. I'll check it out.

**Comment by digimezzo** [comment]
I could reproduce it. It's indeed caused when searching and then clearing the search. In that case double or triple groups start to appear. I'm working on a fix.
