### ISSUE TITLE
Shuffling entire music library, huge memory footprint

### ISSUE THREAD

**Issue by ilovetorrents** [digimezzo/dopamine-windows#650]
When I want to shuffle my entire music library which consists of nearly 100 GB of music, Dopamine's memory footprint grows to the point of using up all available memory (grows to 6GB+ of RAM) rendering it and the whole system unusable.

**Comment by digimezzo** [comment]
Needs investigation. But I can imagine that shuffling such a large amount of songs can cause a memory issue.

**Comment by digimezzo** [comment]
I can reproduce this issue when Track covers are displayed in the playlists. Could you verify if you're having this issue with track covers displayed?

![image](https://user-images.githubusercontent.com/11945339/35820861-4521a436-0aa7-11e8-9c67-dcf75b0a8492.png)

**Comment by ilovetorrents** [comment]
Well hiding track covers definitely slows down the rate at which the Dopamine process grows but it grew nonetheless with the same end result (reached 4GB in 5 minutes roughly). I've also noticed that it becomes very CPU intensive as well.
