### ISSUE TITLE
Support for alternative music collections

### ISSUE THREAD

**Issue by mormond** [digimezzo/dopamine-windows#655]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Scenario - I have lossless audio available on my home network and lower-quality mp3 versions of the same tracks available for when I'm unable to access my homeserver. These might be located at `\\homeserver\lossless` and `C:\Music` respectively. I would like to be able to select which is in use.

Currently, if I add both locations only one version of each track shows up and I have no control over which it is.

I can probably achieve the desired result by creating two separate instances of the application but it would be a nice feature to be able to control the "active" folders from within the app.

**Comment by digimezzo** [comment]
This used to be possible in the 1.3 versions. However, due to a regression, the checkboxes to allow that functionality are not displayed. Next version (1.5.10) will fix that. I'll be released very soon.

**Comment by digimezzo** [comment]
Version 1.5.10 has just been released. Could you verify if it resolves your issue?

**Comment by mormond** [comment]
Yes, that seems to do exactly what I'm looking for. I just have to be careful not to refresh the collection when a source can't be reached. Many thanks!

**Comment by digimezzo** [comment]
Ok thanks for confirming. For the refresh annoyance, I've opened a new issue: #664
