### ISSUE TITLE
Dopamine doesn't play audio on 32 bit systems

### ISSUE THREAD

**Issue by Mirlu-exe** [digimezzo/dopamine-windows#673]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 7 Home Premium
* Dopamine version: 1.5.10

## Reproduction steps

* Step 1
 Open the exe
* Step 2
Add a folder
* Step 3
Try playing a song
* Step 4
It will crash inmediatly.

## Observed behavior
It stops working.

## Desired behavior

To play songs normally without crashing

![dopamine has stopped working](https://user-images.githubusercontent.com/36609728/36358056-2a96f404-14de-11e8-8cef-cc540b224bc1.png)

## Log file
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1735216/Dopamine.log)

I tried with all the older versions, and they stop working as soon as I try to play a song.
Thanks for your hard work!.

**Comment by shoker537** [comment]
I agree, I have the same bug.

**Comment by digimezzo** [comment]
@shoker537 also on Windows Home Premium? Could you attach your log file?

Also, is it a 32 or 64 bit version of Windows?

**Comment by shoker537** [comment]
@digimezzo Windows 7 Professional x32, Windows 10 Pro x32.
.Net is installed on 10 and was installed on 7.
Older versions don't work too. When I open a song directly (via "open using -> Dopamine"), it still crashing.

**Comment by shoker537** [comment]
Log: 
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1777576/Dopamine.log)

**Comment by digimezzo** [comment]
The issue is reproducible here. However I need input from the CSCore (the audio lib used in Dopamine) developer before being able to provide a fix. There seems to be a problem using the FFMpeg decoder on 32 bit systems. This is the issue that I logged on the CSCore GitHub: [https://github.com/filoe/cscore/issues/331](https://github.com/filoe/cscore/issues/331)

**Comment by shoker537** [comment]
@digimezzo OK, good luck!

**Comment by digimezzo** [comment]
I can't figure out, for now, why FFMpegDecoder fails on 32 bit systems. It would be great if someone could assist on this. See CSCore bug: [https://github.com/filoe/cscore/issues/331](https://github.com/filoe/cscore/issues/331)

**Comment by shoker537** [comment]
@digimezzo Hey, sorry, I can't solve a problem :( But I'll try to help you. Can you use libs that AIMP uses? I don't have any problems with it or if you'll find another decoder to use it will be awesome.
Or you can try to use DEV builds of libs...

**Comment by digimezzo** [comment]
@shoker537 I had a look at those a while ago. I think AIMP uses BASS lirary. However, I think it is not free.

**Comment by shoker537** [comment]
@digimezzo  Even so, there must be another free decoder. I don't think FFMpeg is the only stable music decoder...

**Comment by digimezzo** [comment]
@shoker537 Unfortunately not. There aren't many free audio decoders for .NET. Those I know, don't support as many audio formats as CSCore. I this issue is not revolved, my only resort is to revert back to CSCore without FFMpeg. This would fix the 32 bit issue, but support for the Ape and Opus audio formats will be lost :(

**Comment by shoker537** [comment]
@digimezzo Ohhhhhh... Of corse. I need opus... But if changing .opus to .mp3 will make this working without opus support... Just for now it should be reverted back to CSCore without FFMpeg...

**Comment by digimezzo** [comment]
An idea that I had a few years ago, before using CSCore: use Gstreamer. Banshee audio player has successfully done this in WIndows. I didn't succeed back then. But it's worth having a look at. See: https://github.com/digimezzo/Dopamine/issues/697

**Comment by digimezzo** [comment]
@shoker537 and @Mirla-exe, I have resolved the issue, but I need you to test it out too.

Could you download the file **Dopamine 1.5.11.0 - Portable TEST.zip** from [https://www.digimezzo.com/content/software/dopamine/](https://www.digimezzo.com/content/software/dopamine/)?
It is a portable version of Dopamine, meaning that it won't interfere with your currently installed Dopamine and it won't interfere with your existing collection.
Please unzip this file, and in the unzipped folder, double click Dopamine.exe. Please try to add a collection folder and try to play the audio files.

Let me know if it now works. Thank you.

**Comment by shoker537** [comment]
@digimezzo It's working. But I don't think it must be like this: 
![image](https://user-images.githubusercontent.com/17161332/37711310-5b308854-2d21-11e8-8a94-925ee041cf92.png)
And I sent you email via your site.
Thanks.
UPD: I think It was when player was importing my songs... Now % is not high.

**Comment by shoker537** [comment]
@digimezzo .opus is working too, but only song progress not working
![image](https://user-images.githubusercontent.com/17161332/37711723-b07927f2-2d22-11e8-9ea5-f145b588e4e5.png)

**Comment by digimezzo** [comment]
@shoker537 Could you send me the file that doesn't show progress? The Opus files I have here show progress fine here.

**Comment by shoker537** [comment]
@digimezzo every opus I have - about 350 files (song collection).
Ok, one of them: https://yadi.sk/d/yFwDs1XL3TcJ2M
MPC-HC opens it fine.

**Comment by shoker537** [comment]
@digimezzo and the player don't see .opus files when I add a folder with .opus songs, it plays them only when I drop .opus file to dopamine.exe (in not portable version it would be like "open with Dopamine" in context menu)

**Comment by digimezzo** [comment]
@shoker537 hmm, the file header cannot be read by taglib. It tries to find tags but that format is not supported (it seems it's a webm file). Also, this file seems to have no tags at all. I have to brainstorm how to handle that, as currently I refuse to import fiels where tags cannot be read.

**Comment by shoker537** [comment]
@digimezzo Okay, maybe that is because I downloaded this files from youtube videos like audio files (using "savefrom"). This can be a reason - no need to solve it, this is yt...

**Comment by digimezzo** [comment]
@shoker537 You can use Vitomu for that purpose: [https://www.digimezzo.com/software/](https://www.digimezzo.com/software/). It creates valid audio files.

**Comment by shoker537** [comment]
@digimezzo I'll try :D Thanks. What can you say about my email?

**Comment by digimezzo** [comment]
@shoker537 Lot's of good ideas. I replied :) Thanks.
