### ISSUE TITLE
Bass distortion on v 1.5.10

### ISSUE THREAD

**Issue by DiverseInternet** [digimezzo/dopamine-windows#676]
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10 Pro
* Dopamine version: 1.5.10

## Reproduction steps

* Step 1 play any flac or wav file
* Step 2 listen for distorted bass
* Step 3 codec issue?

## Observed behavior

Bass distorted, particularly noticeable on bass heavy tunes. Playing same files in Groove Music or Windows Media player is fine. Also Dopamine 1.5.9 is fine. This behaviour only applies to 1.5.10. I removed then reinstalled 1.5.10, problem still existed. Then uninstalled 1.5.10 and regressed the version to 1.5.9 and all OK now.

## Desired behavior

1.5.10 should play to the same quality as 1.5.9

**Comment by digimezzo** [comment]
Would you mind sharing an audio file which has this issue?

**Comment by DiverseInternet** [comment]
It's a large file, so I've shared it on OneDrive:

https://1drv.ms/u/s!AkudQ9O7SaqygeVJ698qNrem7q1dUg

By the way, thanks for a fantastic piece of software guys, aesthetically beautiful and does the job perfectly. Please don't be tempted to add bells and whistles such as video or downloads.

**Comment by KrayZeee** [comment]
have you checked your equalizer settings(dopamine/sound driver)?
as soon as i turn dopamines bass preset on it gets distorted but otherwise it sounds fine.

**Comment by DiverseInternet** [comment]
I never use the equalizer, I like the  sound to be as pure as possible, without any digital enhancements.

Were there any changes in v. 1.5.10 that could have affected the sound output?

**Comment by DiverseInternet** [comment]
Second thoughts, I may have played with the equalizer once, just to try out all Dopamine's settings.

I thought I'd disabled it, but maybe not, I've just reinstalled 1.5.10, made sure the  equaliser was off and it sounds great. Sorry.

Thanks again for a great product, donation on the way.

**Comment by Magentaize** [comment]
All bands sound well on my laptop.

**Comment by digimezzo** [comment]
No problem. Thanks for the clarification. I couldn't reproduce the problem here either. I'm closing the issue.
