### ISSUE TITLE
Clean git repository binary files

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#702]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Since NVorbis and those test files have been deleted, they're useless. However they're not be truly removed, actually, they were laid on git history blobs and took up space in vain. Some developer users complain it's a so huge repository when cloning from github.

So, [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) can be used to clean useless binary files harmless and release these space.

**Comment by digimezzo** [comment]
This has now been done. Clone size has been reduced from 700 MB to 32 MB :) Thanks for the tip!
