### ISSUE TITLE
[Feature Request]Added the option of sorting songs by date last added

### ISSUE THREAD

**Issue by trungdoan2507** [digimezzo/dopamine-windows#706]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x ] Feature request
</code></pre>

Hi,
I usually listen music by the last added playlist, so hopefully you can add sorting by date added in the song page as you did in the album page.
Thank you.

**Comment by digimezzo** [comment]
Fixed in 165347b263703107a54a516a0ffbb9707a5ef19e
