### ISSUE TITLE
Resource usage

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#71]
Users report high CPU usage and RAM. Can something be done about that?

Info from a user:

My library according to Dopamine: 42.8 GB, 17.1 days, 275 album artists, 790 albums, 6445 songs
My PC: i7-3960X 12-core CPU, 64GB RAM, GTX970

Resource usage is absolutely through the roof. Currently with all three running and idle, I'm seeing:
  Dopamine: 10% CPU, 810 MB RAM
  foobar2000: 0.1% CPU, 17 MB RAM
  Groove: 0.1% CPU, 50 MB RAM
As soon as I start Dopamine, it jumps immediately to a steady and consistent 3% CPU and 150 MB RAM. Doing a simple 3-artist, 10-album filter immediately jumps it to 10% CPU, 490 MB RAM. When it reaches this level of resource consumption, even just changing to a different artist with a single album can take upwards of 5-10 seconds. Sometimes it seems to break it entirely, such that selecting different artists does not filter the albums/songs at all.

**Comment by digimezzo** [comment]
RAM usage was trimmed down after fixing a serious memory leak. CPU usage is mostly caused by the spectrum analyzer. It might improve later.

**Comment by beerisgood** [comment]
It is possible to reduze the RAM usage?
After i start Dopamine with just 1 album it eat ~55MB. If i minimize to tray and wait it go to 51MB.

But if i use AIMP, without minimize it, it only need less then 10MB

**Comment by digimezzo** [comment]
@beerisgood Only if there is a memory leak. 55MB doesn't look like a memory leak. It is normal for a .NET application to "reserve" more memory than a native (e.g. written in C or C++) application. Just because a .NET application reserves memory pages, it doesn't mean that the reserved memory isn't available for Windows if required. Long story short: it is normal and you have nothing to worry about.
