### ISSUE TITLE
Lyrics support shuold be enhance

### ISSUE THREAD

**Issue by wjk199511140034** [digimezzo/dopamine-windows#710]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

lrc improve，
If one row has multiple timestamps, it won‘t be display appropriately
![default](https://user-images.githubusercontent.com/12637627/38415591-8e31431a-39c4-11e8-949b-2bc412b9f0ed.jpg)
I dont know it is a standard's timestamp format or not, but this format was pretty common, I dont know why Dopamine not support this, ,,,

**Comment by digimezzo** [comment]
I understand what is happening. In case of lyrics with multiple timestamps per line, the sorting by timestamp only occurs when all lines have at least 1 timestamp. This limit exists to avoid strange looking lyrics when there are lines with an without timestamps. In such case, positioning is strange.
Please remove the first line, which doesn't have a timestamp, and the sorting will work.

Even if it works, please leave this issue open, as it could use some improvement.

**Comment by wjk199511140034** [comment]
@digimezzo 
yes, its warking, I thought that was standard format, each of my lrc file have head like this, its a huge work to edit one by one 
`[ti:A Hero Comes Home]

[ar:Idina Menzel(End Credits Version)]

[al:Beowulf(贝奥武夫)]

[by:路西法の哀伤]
`

**Comment by digimezzo** [comment]
Thanks for confirming that it works. I agree though that it should work, even with the header. I'll look at that this week and will try to release a fix asap.
