### ISSUE TITLE
Sort music by date

### ISSUE THREAD

**Issue by GBry** [digimezzo/dopamine-windows#714]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x ] Feature request
</code></pre>

Please add sorting music by Date (Modified, Created, etc.)

**Comment by digimezzo** [comment]
This is related to #706

**Comment by digimezzo** [comment]
Fixed in 165347b263703107a54a516a0ffbb9707a5ef19e
