### ISSUE TITLE
It's not necessary to call RaisePropertyChanged after SetProperty

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#722]
Actually, Prism has done it for us.
[BindableBase.cs](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Mvvm/BindableBase.cs)

**Comment by digimezzo** [comment]
I am aware of this. Did we call RaisePropertyChanged after calling SetProperty in some places?

**Comment by Magentaize** [comment]
Sorry, I misunderstand local older files...
