### ISSUE TITLE
Dopamin crashes when indexing library of 52k at 80%

### ISSUE THREAD

**Issue by derausgewanderte** [digimezzo/dopamine-windows#730]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10, version 1803
* Dopamine version: 1.5.13 (release)

## Reproduction steps

* Step 1 open Dopamine, it starts indexing
* Step 2 Dopamine starts indexing library for first time
* Step 3 

## Observed behavior
 Dopamine crashes at 80%, total songs scanned 42371. It does this at exactly the same number every time. 

## Desired behavior
 Dopamine finishes indexing

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1935003/Dopamine.log)

**Comment by digimezzo** [comment]
The crash always occurs when processing tags from this file: D:\Users\Hilmar\Music\R\Roger Eno\Roger Eno - Islands\Islands\02 Laraaji _ Zaragoza II.2.mp3

Could you send me that file so I can try to reproduce the issue here? Thanks!

**Comment by derausgewanderte** [comment]
Will do later today. Thank you
best regards, Hilmar
On Sun, Apr 22, 2018 at 1:59 AM -0400, "Digimezzo" <notifications@github.com> wrote:


The crash always occurs when processing tags from this file: D:\Users\Hilmar\Music\R\Roger Eno\Roger Eno - Islands\Islands\02 Laraaji _ Zaragoza II.2.mp3


Could you send me that file so I can try to reproduce the issue here? Thanks!

**Comment by derausgewanderte** [comment]
it's strange. When I added the folder R with Roger Eno on its own 
yesterday it did not crash. It didn't index the particular file either 
though.
I just noticed that I had two copies of that file in the same folder. 
When I try to play the one without tags in MusicBee it tells me the file 
is corrupted with an unknown file format.

Files are located here:
https://1drv.ms/f/s!AphNugawM6v6rqo5EKvbTxcWYcx_-Q

It must be just garbage because it zipped from 23Mb down to 7Mb, while 
the working file stays at 23Mb as it should (attached as well).
I will still try to narrow down the culprit in the S folder later today.

As for the remote, I am thinking of the MusicBee remote. It works via a 
plugin through MusicBee.

MusicBee Player: https://getmusicbee.com/

Plugin: https://github.com/kelsos/mbrc-plugin
Android app: 
https://play.google.com/store/apps/details?id=com.kelsos.mbrc
source: https://github.com/kelsos/mbrc

thank you!

best regards, Hilmar

------ Original Message ------
From: "Der Ausgewanderte" <derausgewanderte@gmail.com>
To: "digimezzo/Dopamine" 
<reply@reply.github.com>
Sent: 4/22/2018 7:28:36 AM
Subject: Re: [digimezzo/Dopamine] Dopamin crashes when indexing library 
of 52k at 80% (#730)

>Will do later today. Thank you
>
>
>best regards, Hilmar
>
>
>
>
>On Sun, Apr 22, 2018 at 1:59 AM -0400, "Digimezzo"

**Comment by derausgewanderte** [comment]
While I ask the program to scan my S artist folder it crashes and leaves this at the end of the log file:
```
2018-04-22 12:09:58.516|Error|IndexingService.ProcessTrack|647|Error while retrieving tag information for file d:\Users\hilmar\Music\T\Trixie Whitley\trixie whitley\04-trixie_whitley-pieces-gti.mp3. Exception: MPEG audio header not found.
2018-04-22 12:09:58.659|Info|IndexingService.IndexTracksAsync|286|Tracks updated: 51. Time required: 2867 ms +++
```
The mp3 file has no tags but it plays fine in other players. It's not corrupt. I uploaded it to the same folder on onedrive: 
https://1drv.ms/f/s!AphNugawM6v6rqo5EKvbTxcWYcx_-Q

**Comment by derausgewanderte** [comment]
Still crashes when adding a folder with new mp3s in it on latest version (1.5.14). Seems to get stuck at the same file above that works perfectly fine with other players.

**Comment by digimezzo** [comment]
@derausgewanderte That is normal. I haven't investigated this problem for 1.5.14 yet :) I'll do that for the next beta.

**Comment by digimezzo** [comment]
Ok. This is what I found:
Files **02 Laraaji _ Zaragoza II.2.mp3** and 04-trixie_whitley-pieces-gti.mp3 are corrupt. They don't play in Foobar2000 either and MediaInfo doesn't recognize them. So I can't do anything about them.

However, these files don't cause a crash. I think it is the file or the files which come just after **02 Laraaji _ Zaragoza II.2.mp3** that causes the indexing crash. Would the be the files in the R folder? Could you send me the file that comes just after **02 Laraaji _ Zaragoza II.2.mp3** in your folders?

**Comment by digimezzo** [comment]
This is probably related to #732. In #732 a StackOverflowException is thrown by TagLib# when reading tags of corrupt files. This exception makes Dopamine crash.

This issue could be related to TagLib# issue https://github.com/mono/taglib-sharp/issues/84
I'll check if I can patch Taglib# to fix the crash.

**Comment by derausgewanderte** [comment]
Whatever caused it to crash was in the S folder. Dopamine had no issues with any of the other folders. Today I scanned and fixed tags with mp3val on the entire S folder and it found over 9000 mp3s that it fixed in some form or another (based on .baks it made at over 5Gb, lol). After that Dopamine had no problems adding the folder. All fine now. Cheers!
