### ISSUE TITLE
CTRL+F to focus search bar

### ISSUE THREAD

**Issue by peter099** [digimezzo/dopamine-windows#733]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x ] Feature request
</code></pre>

CTRL+F will be a useful feature, and in general the abitlity to add custom (global) shortcuts will be useful.

**Comment by Keith94** [comment]
By "global shortcuts" do you mean shortcuts that function even while the program window is inactive?

**Comment by peter099** [comment]
Yes.
