### ISSUE TITLE
Vertical Monitor - GUI problem (almost Perfect)

### ISSUE THREAD

**Issue by vslmc** [digimezzo/dopamine-windows#740]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions
* Windows version: 10
* Dopamine version: 1.5.14 beta 2

## Observed behavior
* https://image.ibb.co/gRzbRx/doa.png
* https://image.ibb.co/deK7zH/doa.png
* (In my case I use 125% dpi)

**Comment by digimezzo** [comment]
Thanks for the feedback. I'll try to further tweak this for beta 3. Dopamine 2.0 will be much more elegant at fitting different screen sizes though. I'll will use some completely different ideas and layouts.

**Comment by digimezzo** [comment]
1.5.14 Release Candidate 1 is available. Please let me know if it works on your vertical monitor.
The titles at the top will wrap (you'll see what I mean). That is all I can provide for the 1.x branch. Dopamine 2.0 should provide a slightly better scaling experience.
