### ISSUE TITLE
Can't play songs with certain characters

### ISSUE THREAD

**Issue by 1suky1** [digimezzo/dopamine-windows#746]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10
* Dopamine version: 1.5.13

## Reproduction steps

* Play a song that has "à" or "æ" character in file name.
* Remove the characters from file name.
* Song can be played in Dopamine.

## Observed behavior

When I try to play a song with mentioned characters, the song doesn't want to play nor it shows up as "playing". Best example is to try and play "Sigur Rós - Sæglópur". 

So far "à" and "æ" are the only characters that I noticed that don't work. For example, "Sigur Rós - Njósnavélin (The Nothing Song)" or "Sigur Rós - Dauðalagið (The Death Song)" will play normally. 

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1961089/Dopamine.log)

**Comment by digimezzo** [comment]
It's the second time today that this issue is reported. I'm confused because, when I try to play a file Sigur Rós - Sæglópur.mp3 on my computer, it works fine. I see that FFMpegDecoder thinks that the file doesn't exist, so there is definitely something going on. I jut don't know what yet.

The only thing I can think of right now, is regional settings:

- What language is you Windows?
- What are the regional settings: language, keyboard, etc.? (anything you can find)

**Comment by 1suky1** [comment]
@digimezzo 

Windows language is English, region is Croatia. 

Keyboard language that I use is English UK but with Serbian Latin keyboard and Croatian with standard keyboard (due to windows 10 sometimes switching languages and input when I use other apps etc.) https://i.imgur.com/sYAISYv.png

**Comment by digimezzo** [comment]
Could you send me one of those files? I'm trying by renaming my files to the names with special characters, but probably, some information of the encoding of the characters gets lost when I do this. I might be able to reproduce by using one of your files directly. Thanks!

**Comment by 1suky1** [comment]
@digimezzo 
Here's a zip with a few songs that don't play and a full album that also doesn't play because of album name https://drive.google.com/open?id=1heVDw8Lc9COFVmglW5_r2wzbszef9rxO

**Comment by digimezzo** [comment]
Thanks for the files. I still can't reproduce this.
When you double click the files in Windows Explorer, do the files then play?

**Comment by 1suky1** [comment]
Yep, songs play without a problem in VLC and Groove.

**Comment by digimezzo** [comment]
I mean in Dopamine? Try right-click on one of those files, and choose "Open with..." and there, choose Dopamine

**Comment by 1suky1** [comment]
Ah yes, Dopamine finds it and opens the folder where the song is and selects it.

**Comment by 1suky1** [comment]
And opening the files with Dopamine opens Dopamine but doesn't play the file.

**Comment by digimezzo** [comment]
OK. In that case, there might be an error in the Dopamine database. Could you send me the Dopamine.db file which you'll find in folder %appdata%\Dopamine?

**Comment by digimezzo** [comment]
So am I correct if I say this?

* when you open the file from Windows Explorer by choosing "Play with Dopamine" it opens Dopamine and plays fine
* when you select the song from inside Dopamine, it doesn't play

**Comment by 1suky1** [comment]
[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/1961666/Dopamine.zip)
Here it is although I did try to reinstall Dopamine and removed the whole folder from appdata and had the same problem.

And when I open with Dopamine from Explorer it doesn't play. But if I right click the song in Dopamine and select "View in Windows Explorer" it opens the exact location of that song. So it's aware of the song and has the right location for it but doesn't want to play it.

**Comment by digimezzo** [comment]
Thanks for the info. Another question: are you using a 32 bit version of Windows?

**Comment by 1suky1** [comment]
Nope, 64 bit.

**Comment by digimezzo** [comment]
Could you download this Dopamine.Core.dll file? [https://www.dropbox.com/s/33hfo7vppcd7t32/Dopamine.Core.dll?dl=0](https://www.dropbox.com/s/33hfo7vppcd7t32/Dopamine.Core.dll?dl=0)

Then, replace the original Dopamine.Core.dll file which you'll find here C:\Program Files (x86)\Dopamine by the one you downloaded. Then try to play these files again. I'd like to know if this works.

**Comment by 1suky1** [comment]
Dopamine doesn't start with this.

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1961905/Dopamine.log)

**Comment by digimezzo** [comment]
I've created CSCore bug https://github.com/filoe/cscore/issues/344. I'm not sure yet what is causing this problem. It would have helped if it was reproducible here.

I might have a workaround for it. But a correct fix would be better.

**Comment by digimezzo** [comment]
Could you try this zip file: [https://www.dropbox.com/s/c3wn7nbwkz4dfnn/Dopamine%201.5.14%20%28Release%20Candidate%202%29%20-%20Portable.zip?dl=0](https://www.dropbox.com/s/c3wn7nbwkz4dfnn/Dopamine%201.5.14%20%28Release%20Candidate%202%29%20-%20Portable.zip?dl=0)

It is a patched version of the portable version of Dopamine. You can unzip it, then double click Dopamine.exe and use it like the installed version of Dopamine. It won't mess with the collection of your installed version of Dopamine. When you delete the folder to which you extracted the zip, it will be completely removed from your computer. Please try if that version of Dopamine plays your files.

**Comment by 1suky1** [comment]
Yep, this one works. All songs play without a problem.

**Comment by digimezzo** [comment]
Thanks for trying that out. The next release candidate will have this workaround. I'm leaving this issue open however. So I don't forget about it when creating Dopamine 2.0.

**Comment by digimezzo** [comment]
@1suky1 I'm further investigating this issue. Could I send you a small test application to verify if this issue still occurs on your computer?

**Comment by 1suky1** [comment]
@digimezzo sure.

**Comment by digimezzo** [comment]
@1suky1 Here is the test app: [https://www.dropbox.com/s/367ta4cnnfj34zn/TestApp.zip?dl=0](https://www.dropbox.com/s/367ta4cnnfj34zn/TestApp.zip?dl=0)

It is called TestApp.exe. You'll have to start that app. It will try to play the mp3 file which is in the same directory as the TestApp.exe file. The output window will look like this:

![image](https://user-images.githubusercontent.com/11945339/41499708-05011464-7185-11e8-8a05-dcae294f1efa.png)

Please attach a screenshot of the output window from your computer. Thanks!

**Comment by 1suky1** [comment]
@digimezzo Sorry for the wait. Tried it and it works, as well with a few other songs that I tested before. 

Edit: Here's a screenshot https://i.imgur.com/JFzAUq7.png

**Comment by digimezzo** [comment]
Excellent! thanks for confirming that. I'm closing this issue.
