### ISSUE TITLE
Where are Dopamine playlists stored?

### ISSUE THREAD

**Issue by Darkle** [digimezzo/dopamine-windows#751]
Hi, I was wondering where the playlists in Dopamine are stored. I'd like to symlink them to my dropbox so I don't lose them.

Thanks for the app btw, it's just what I was looking for.

**Comment by Keith94** [comment]
`%USERPROFILE%\Music\Dopamine\Playlists`, I think.

**Comment by Darkle** [comment]
@Keith94 Thanks.

**Comment by Keith94** [comment]
Np.
