### ISSUE TITLE
Improve the Update Method because the icon in taskbar becomes white :( 

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#759]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10 Version 1803
* Dopamine version: 1.5.14

**Comment by digimezzo** [comment]
Duplicate of #293. I haven't found the solution to this issue yet. This issue will be closed, in favor of #293.
