### ISSUE TITLE
Lyrics scrolling issues

### ISSUE THREAD

**Issue by ssmodk** [digimezzo/dopamine-windows#763]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 7, 10
* Dopamine version: 1.5.14

## Reproduction steps

* Listening to MP3 files with long lyrics in the lyrics viewer.
* Automatic scrolling is on, with no timestamps in the song.
* Attempt to scroll the long lyrics down while the track is playing.
* After 30-50% of the way down the page, it rubberbands back to the top (or close to the top) of the lyrics.
* The lyrics will scroll normally if the song is paused.

**Comment by DeusArcana** [comment]
Same
