### ISSUE TITLE
Issue importing lyrics from LyricWikia with non-standard naming schemes

### ISSUE THREAD

**Issue by ssmodk** [digimezzo/dopamine-windows#764]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 7, 10
* Dopamine version: 1.5.14

## Reproduction steps

* Attempting to import lyrics with only LyricWikia chosen in the settings.
* No lyrics can be found when the artist or song title features punctuation (including hyphens, question marks) or non-standard capitalization, even with the artist and song titles being spelled and punctuated exactly the same as on LyricWikia. (Example artists: Therapy?, KMFDM, SMP, BiGod 20, OhGr)

## Observed behavior

No lyrics were found.

## Desired behavior

Lyrics are found.

**Comment by digimezzo** [comment]
Do you have examples of combinations of artist and title which should provide lyrics?

**Comment by ssmodk** [comment]
Like examples that provide lyrics normally or examples of what should provide lyrics, but don't? I'll assume the latter.

For example, no track by the band Therapy? is picked up at all, because of the question mark in the band name. No band with all capitalized letters in the name is picked up (meaning nothing is imported from KMFDM, SMP, BOL); this includes acroynms with periods between capitalized letters, like the Out Out track "S.Y.O.". Names with irregular capitalization don't work for song titles or artist (Ex. BiGod 20, OhGr, most song titles by OhGr). Parentheticals in the song title also don't work at all; Skinny Puppy's track "God's Gift (Maggot)", for example, isn't found because of the presence of parentheses. 

That said, I haven't found any other problem characters. Tracks with +,@, or : didn't seem to be affected, at very least.

**Comment by digimezzo** [comment]
Note to myself: 

LyricWikia doesn't have an API anymore. That is why a workaround was implemented to get lyrics by providing "artist" and "title" in the URL. The URL must be of format: http://lyrics.wikia.com/wiki/Massive_Attack:Teardrop?action=edit

The ?action=edit URL is case sensitive. Casing must be 100% correct with the casing found in LyricWikia's database. 

Other example that works: http://lyrics.wikia.com/wiki/Out_Out:S.Y.O.?action=edit

The convention for the casing seemed to be: all lower case, except the 1st letter of each word. However, for band which are completely uppercase (like KMFDM), the casing must be all upercase in the url, liek this: http://lyrics.wikia.com/wiki/KMFDM:Splatter?action=edit

For Therapy?, the question mark must be translated to "%3F". So the URL becomes: http://lyrics.wikia.com/wiki/Therapy%3F:Loose?action=edit

**Conclusions:**

1. Replace ? by %3F
2. replace ' by %27
3. Perform 2 searches: 1st search using original casing. If that turns up no result, try to fix the casing and perform an extra search.

**Comment by ssmodk** [comment]
Ah... Yeah. Sorry. I can give some songs for you to check out. I just have to go through and find things I didn't already save lyrics to the files.

Here's some examples of issues involving capitalization in the names:

- BiGod 20 - The Bog
- KMFDM - Brute
- Out Out - S.Y.O.
- SMP - Finished
- BOL - On This
- Clock DVA - The Hacker

(This problem and some wonky performance aside, I have to really complement you on Dopamine. It often runs poorly and starts hogging massive amounts of memory for no discernible reason and it takes forever for it to load in the info for or play a playlist, but the layout has the smooth simplicity of the Zune software and it does exactly what I want it to. Despite whatever weirdness it has, I haven't been tempted to try something else. It's made a fitting replacement for the pretty-much-abandoned Winamp, which I'd been using as my media player of choice since Winamp 1.)

**Comment by digimezzo** [comment]
Thanks for reporting this. This issue has been fixed.
