### ISSUE TITLE
"Love" column does not display

### ISSUE THREAD

**Issue by kayasax** [digimezzo/dopamine-windows#770]
## I'm submitting a...

<pre><code>
[X] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10
* Dopamine version: 1.5.14

## Reproduction steps

* go to settings / behavior
* enable "show love button"
* return to collection / songs

## Observed behavior

the column does not appear
## Desired behavior

We shoud see a "Love" column
## Log file

no entry in logfile for this it seems

**Comment by digimezzo** [comment]
Hi, for the Songs screen, there is an extra option to show/hide columns. By default "Love" is hidden. You have to right click the Songs grid, and tick the "Love" box. Does that solve you issue?

![image](https://user-images.githubusercontent.com/11945339/41510429-bef95df6-7264-11e8-8201-5d078b12438c.png)

**Comment by kayasax** [comment]
Yes this is solved thank you very much 👍
