### ISSUE TITLE
Dopamine 2.0 design goals

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#771]
This is a checklist of goals to achieve for the Dopamine 2.0 design

- [x] Freshen up the current design to give it a more modern look (not "modern" as defined by Microsoft)
- [x] Gain vertical and horizontal space to display useful content (e.g.: move main menu items to a drawer)
- [x] Lighten up the dark style + tweak the light style to be less blinding
- [x] Remove vertical column lines. Indicate column by playing with shades of the background color.
- [x] Improve position of search box
- [x] Allow rating and loving of the playing track on the main screen

**Comment by Keith94** [comment]
Sounds exciting!
What do you mean by a more modern look? Similar to the material design language by Google? ...Screenshots are welcome :)

**Comment by digimezzo** [comment]
There will be subtle elements of material design. But I will not follow the standard fully.
With modern, I mean a fresher look. The current look is somewhat dated and can use a bit of improvement. I'm thinking of making it a bit less flat, without losing flatness too much.

The goal is to freshen up the UI, but keep Dopamine's idea alive. I don't want to shock my current users too much :)

There are no screenshots yet. It's all in my head :) You'll see the progress in the previews, and you'll be able to give feedback.

**Comment by Keith94** [comment]
OK great! I agree with everything; if you polish up the dark theme (making it less dark), I look forward to using it. :)

**Comment by The-Choo-Choo-Shoe** [comment]
Will "Remove vertical column lines. Indicate column by playing with shades of the background color." make https://github.com/digimezzo/Dopamine/issues/747 redundant?

**Comment by digimezzo** [comment]
No. Columns will probably still be resizable.

**Comment by Bearlify** [comment]
Will there ever be remote control similar to iTunes' Remote app?

**Comment by digimezzo** [comment]
@Bearlify No idea yet. I'll have to check what the iTunes remote app does.

**Comment by digimezzo** [comment]
First screenshot of the new design (work in progress)
![image](https://user-images.githubusercontent.com/11945339/41030208-148a64f8-697e-11e8-9603-28b0b82e8d1e.png)

**Comment by The-Choo-Choo-Shoe** [comment]
Looks nice, can't wait to test it out. What does highlighting look like in the new UI?

Are you sticking with the current design or moving to a more Windows 10ish look?
Like this: https://i.imgur.com/p32Txoz.png

**Comment by digimezzo** [comment]
Highlighting will be more grey-ish. I'm trying to prevent throwing too much accent color in the face of the user. I'm attempting to make the theme more subtle.

**Comment by Keith94** [comment]
Any ETA on preview builds? I'm sure users would like to provide feedback.

The new layout and colors look really nice so far, btw.

**Comment by digimezzo** [comment]
@Keith94 As soon as possible. Completing the first draft of the new design, so it is actually usable with both the dark and light theme, is the only remaining requirement to release the first preview. 
Maybe 1 week, or 2, if life gets in the way too much :)

**Comment by digimezzo** [comment]
Drawer menu:

![image](https://user-images.githubusercontent.com/11945339/41158357-ee764442-6b28-11e8-9604-b2d7cf9c5b5d.png)


More items should appear in the drawer menu in later builds:

- "Playlists" will be moved here and removed from the top menu. When Playlists item is selected, the top menu will provide sub items: amanual, smart, ...
- "Streaming" (? Still brainstorming about it)
- "Podcasts" (? Still brainstorming about it)

**Comment by Keith94** [comment]
Looks very good execpt that the "Dopamine" header looks very fat (tall). Should it be smaller or no?

**Comment by digimezzo** [comment]
@Keith94 Agreed. I made it smaller.

![image](https://user-images.githubusercontent.com/11945339/41179857-87514732-6b6c-11e8-8e36-b141026977b7.png)

**Comment by Keith94** [comment]
Nice!

**Comment by digimezzo** [comment]
Thanks. It looks rather simple and empty for now. But during development, more items will be added to the menu.

**Comment by digimezzo** [comment]
Another screenshot of design progress:

![image](https://user-images.githubusercontent.com/11945339/41206709-9d2625a8-6d08-11e8-9c9f-6862a435ed5c.png)

**Comment by Keith94** [comment]
Wow, great progress!

Do you think some extra padding is needed in the "Songs" list, i.e. along the left and right margins?

Any thoughts about implementing fluent design system?

**Comment by digimezzo** [comment]
Ohw, I didn't upload a screenshot of the Songs screen yet. I did add a little padding to that screen. Let me know what you think:

![image](https://user-images.githubusercontent.com/11945339/41213873-51dd7c1e-6d48-11e8-9fb4-bfad8e57af7e.png)

**Comment by The-Choo-Choo-Shoe** [comment]
Current issues in 1.5.14 with the songs category:

1. It defaults back to album artist sorting every time you close the program.
2. It doesn't show which category it sorts by, you need to click one after launching the program and then the text goes blue and the arrows shows up.
3. Not really an issue but would it be possible to make it so we can change how we want the columns sorted?, for example move rating to the far right.

Is this fixed in the new version?

Also, what's the top middle drawer looking thing? Is it thew new settings menu?

**Comment by digimezzo** [comment]
@The-Choo-Choo-Shoe I've created a new issue for the Songs screen issues: #793. The songs screen in 1.5.x is too basic. It doesn't save its status and sorting. I'll try to improve that screen for version 2.0. The improvements won't be in the 1st preview. They'll appear a bit later.

As for the drawer: I moved the top menu "Collection   Settings    Information", to the drawer. The drawer will have additional options below "Collection", like "Playlists", "Streaming".
When selecting the "Playlists" option in the drawer, a screen will open, which has multiple options in the top menu. For example: "Manual    Smart" (for manual and for smart playlists). That's all still ideas in my head though, so it might change a bit while developing.

**Comment by Keith94** [comment]
@digimezzo What I meant was the text is very close to the left/right margins, so it could use more padding.
I outlined the problem areas in red below.

![41206709-9d2625a8-6d08-11e8-9c9f-6862a435ed5c](https://user-images.githubusercontent.com/5490615/41257890-4d8ac7f8-6d83-11e8-846c-47462d67bec6.png)

**Comment by digimezzo** [comment]
Ah yes! I know :) That's the last part of the theming that I have to do. I'm leaving it as the last task because it is tricky. I want to keep the text alignment with the rest of the UI, so that means that the selection box will have to extend a bit more to the left and right.

**Comment by Keith94** [comment]
OK sounds good. :-)

**Comment by digimezzo** [comment]
@Keith94 What do you think about this selection box? It has more padding by extending more to the left and right. The text remains aligned with the blue alphabetic selectors. I would apply the same to the songs pane, where the text would remain aligned with the album title at the top of the songs pane.

![image](https://user-images.githubusercontent.com/11945339/41336554-dcae3dce-6eec-11e8-8fdb-7854e27ce4d0.png)

**Comment by Keith94** [comment]
It's good, but I prefer if you extend it all the way, i.e. fit to width. The Windows start menu uses the same, I think? Is that panel resizable btw?

![firefox_2018-06-13_09-34-31](https://user-images.githubusercontent.com/5490615/41366176-206fdd58-6ef0-11e8-99ab-c9ba583439ca.png)

**Comment by Keith94** [comment]
Hi :) I like what you did with 2.0.

For the albums panel, it's not so obvious which album is currently selected. What do you think?

**Comment by digimezzo** [comment]
I'm aware of it. The album selector is work in progress :)  I don't want to use the accent color anymore to indicate album selection. That's the cause of the issue. I'm not sure yet how to improve it, so I released the preview as is. But I will find a solution in the future.

**Comment by The-Choo-Choo-Shoe** [comment]
@digimezzo I downloaded an tested the 2.0 preview, one issue I found is that some text is white in the light theme. It doesn't look like buttons either as it does on the dark theme.
![untitled](https://user-images.githubusercontent.com/31801661/41499527-b31dc136-7181-11e8-8c5a-3b8b408ea165.png)

I'll just update this comment instead of making a new issue for everything, it's just the first test build after all.

Another issue, the spectrum analyzer is no longer centered: 
![untitled](https://user-images.githubusercontent.com/31801661/41499585-a85267c4-7182-11e8-9957-3bd707d7e847.png)

The margins me and @Keith94 talked about would look something like this if done like Windows 10, looks a lot cleaner making it edge to edge: 
![suggestion](https://user-images.githubusercontent.com/31801661/41499720-3ac8b41c-7185-11e8-9d47-dd99ae1c8220.png)

**Comment by digimezzo** [comment]
The light theme is not finished yet. You weren't supposed to be able to select it, however I forgot to disable the toggle button :)
Thanks for the other suggestions. I'll see what I can do.

**Comment by The-Choo-Choo-Shoe** [comment]
Hehe, I figured something wasn't right, didn't look as "complete" as the dark one.

You seem to want to change the album select process or colors so I came up with some mock-ups in paint, super professional.

Maybe it can give you some inspiration or what to do or what not to do :P

First one looks like the current one but when you select an album it moves the other albums down to its own row and extends the selected album to the right with more info about the selected album.

![suggestion](https://user-images.githubusercontent.com/31801661/41500321-7087216a-718f-11e8-992a-083e043c0b3b.png)
![suggestion 2](https://user-images.githubusercontent.com/31801661/41500326-74889c3a-718f-11e8-8bbe-535ed4d956a5.png)

The other one is more "old school" with mostly text, not so many pretty images. Colors are obviously crap as I copy pasted most of it.
![test](https://user-images.githubusercontent.com/31801661/41500333-ae0f55d4-718f-11e8-8c19-5423b271405f.png)

**Comment by digimezzo** [comment]
@The-Choo-Choo-Shoe I like your mockups. You're good at paint :) The top one is technically difficult. The wrap panel which is currently used, only supports items which have the same size. As soon as any item has a different size, things go very bad. The bottom one is perfectly doable. But I miss the album art. Maybe a combination of both would be nice (bottom one, with a vertically larger selector which contains the album art and other album details. I'll brainstorm about it (even about the top mockup. Maybe there is another solution that can be used instead of the wrap panel).

If you have other ideas, don't hesitate to post them here.

**Comment by The-Choo-Choo-Shoe** [comment]
Yeah, I didn't like my first one that much and I'll agree, it would have been hard to pull off for a rather meh end result.

Was thinking about doing what you're thinking when I was doing the mock-up but I didn't want to put all that time into it in paint, it would make it look a lot more lively with the covers next to the album names, I was even thinking a cover next to artist name as well but would require some database otherwise it would all show blank and boring. My first mock-up I did had a big cover in the songs panel next to the album name as well.

**Comment by digimezzo** [comment]
Some of the ideas are actually things I've been thinking about. Adding a artist picture in the list of artists. But that would only be interesting if Dopamine can pull artist pictures from the internet, link Lastfm. I'll definitely look into that. As for the songs panel album art, did you think about something like this?

![image](https://user-images.githubusercontent.com/11945339/41500908-f8eb48aa-719a-11e8-8e7e-f704627bfb94.png)

**Comment by The-Choo-Choo-Shoe** [comment]
Yeah, something like that. My idea was something looking like TIDAL with the whole border thingy above the songs list so it doesn't look like the cover is just floating in the air and the blurred background looks rather nice.

![41500333-ae0f55d4-718f-11e8-8c19-5423b271405f](https://user-images.githubusercontent.com/31801661/41501048-3225d35e-719d-11e8-8606-ea7543e1b4a7.png)

Dopamine already has a color picker so it could be used for the background as well if a blurred image doesn't look right, in the end I'm just trying to help with ideas, it's your choice how you choose to do it. My ideas might not even be doable.

**Comment by The-Choo-Choo-Shoe** [comment]
Here is another one: 
![41500321-7087216a-718f-11e8-992a-083e043c0b3b](https://user-images.githubusercontent.com/31801661/41501400-037ce5ea-71a4-11e8-9eb7-5d0ba02e6079.png)

Maybe it sticks out a little too much, I don't know. I just picked a color for the background from the cover art. The cover is a little too big still I think as well, it distracts from the bottom left cover of the currently playing song. Maybe it would look better if they were the same size.

I made a smaller one using the same size as the currently playing song: 
![41500321-7087216a-718f-11e8-992a-083e043c0b3b](https://user-images.githubusercontent.com/31801661/41501447-e512b7b4-71a4-11e8-85da-974f4126072a.png)

**Comment by digimezzo** [comment]
The design with the cover the same size as the currently playing song looks good. The background can be a blurred part of the cover (that is perfectly doable). I'll give that a try.

**Comment by The-Choo-Choo-Shoe** [comment]
I made one with cover art showing as well, it didn't look quite right with no border around the covers as they were too stacked, could also do padding between them. It's quite far from "Zune" looking at this point.

I don't know how a layout like this would scale in full screen, it would look a bit bare I think. It would be a nice addition though to the current setup as I feel like Artists, Genre and Albums all look kinda the same.

The album selector is supposed to kinda look like the playlist when showing covers.

![41501048-3225d35e-719d-11e8-8606-ea7543e1b4a7](https://user-images.githubusercontent.com/31801661/41501919-afb763e0-71ad-11e8-854b-70bc964d8a27.png)

I'll leave you to figure out what you want to do, at least I've given you some ideas, good and bad. I'm distracting you too much and throwing too much stuff at you. If anything maybe we could change album view by grid/list one day.

**Comment by digimezzo** [comment]
Don't worry about posting too many ideas. I haven't made up my mind yet about the final look. The thing that bother me most about the current look is that the list of albums is displayed in every screen (artists, genres and albums screens). That's indeed making all screens look similar. I'd like to change that but I'm still looking to find a balance between usability and good looks. Any idea is welcome at this point. Thanks for the time and effort you put in this! 🙂

**Comment by PhillyMay** [comment]
I played around with the Preview 1 (2.0) and must admit that I like the new design a lot. The slightly bigger spacings and the separate boxes (best example the album view) create a fantastic "clean" interface with enough information. 

The new "menu" is a nice addition, although I dislike its current accessability. Personally I think its not intuitive enough to click on the logo to pop out the bar. If there would be a "hamburger menu icon" it would be much clearer, as a lot of applications have us trained so far. 

As for entrys in the menu bar: Internet Radio (will file a separate request) and Podcasts (like mentioned above) would be great additions. I wouldn't mind if the podcast section would only be a place where you could add shows by pasting the respective links or by importing opml files. As much as I'd love to see a full "discover podcasts" feature, this would take too much work (dopamine is no dedicated podcast client, there are a lot of alternatives out there) and harm the inclusion of other, more important features. An "adding your own stuff" approach to have everything in one place would be enough for me.

**Comment by ThePharaohArt** [comment]
Personally not crazy about Google's material design, much prefer MS's Fluent Design with the acrylic transparency on the sidepanel.
