### ISSUE TITLE
Media Pause not working when Dopamine is the only media program running

### ISSUE THREAD

**Issue by quagzlor** [digimezzo/dopamine-windows#775]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 1803
* Dopamine version: 1.5.14

So I have an Alienware laptop, and it has a few programmable keys. I've set some to be media keys, namely volume, next, previous, and pause.

The next, previous and pause keys are programmed via fn+right arrow, fn+left arrow and fn+up arrow.

Now, a few versions back, I was having no trouble using the pause key with Dopamine.

Recently however, that seems to have stopped working. If Dopamine is the only application open, then unless i have it focused, the pause key simply will not work.

If i open say, VLC player, and then try, the pause key works perfectly.

**Comment by xCONFLiCTiONx** [comment]
This has been bugging me for a while now and pinpointed the problem at least for me:
The issue is that Low Level AND AppCommand cancel eachother out.
I went to "Dopamine\Dopamine.Services\Win32Input\LowLevelKeyboardHookManager.cs" commented out the following and it works perfectly within the application and globally:

```C#
        private IntPtr HookCallback(int code, IntPtr wParam, IntPtr lParam)
        {
            if (code >= 0 && (wParam.ToInt32() == WM_KEYUP || wParam.ToInt32() == WM_SYSKEYUP))
            {
                int vkCode = Marshal.ReadInt32(lParam);

                if (vkCode == (int)MediaKey.Next)
                {
                    LogClient.Info("LowLevel Key Next pressed");
                    // this.MediaKeyNextPressed(this, new EventArgs());
                }
                else if (vkCode == (int)MediaKey.Previous)
                {
                    LogClient.Info("LowLevel Key Previous pressed");
                    // this.MediaKeyPreviousPressed(this, new EventArgs());
                }
                else if (vkCode == (int)MediaKey.Play)
                {
                    LogClient.Info("LowLevel Key Play pressed");
                    // this.MediaKeyPlayPressed(this, new EventArgs());
                }
            }
            return CallNextHookEx(keyboardHookID, code, wParam, lParam);
        }
```

That will fix it but of course this leaves code that isn't seemingly necessary. Not sure if this is an issue for all cases or just a few. I am on a laptop running Windows 10 x64 latest updates and release.

**Comment by digimezzo** [comment]
That's an interesting find. I'll see what I can do about it.

**Comment by digimezzo** [comment]
@xCONFLiCTiONx I honestly don't know the effect of disabling lowlevel keys for some systems. There are so many types of media enabled devices. It's impossible to test. So my best idea is to add settings that allow the user to select which type of media keys they wish to use.

**Comment by xCONFLiCTiONx** [comment]
Yeah, sounds good to me. Not sure if there is a way to check the types or even what you would do with that information if there is.

**Comment by digimezzo** [comment]
@xCONFLiCTiONx Unfortunatly, there is close to no information on that type of stuff. It happens at OS level. I'll set AppCommand enabled by default in the settings, and add an option for low level keys. That shoudl work for most people out of the box (AppCommand seems to be the modern way of listening to key presses).

**Comment by xCONFLiCTiONx** [comment]
I've looked a bit more closely at this and enabled `appCommandManager` and disabled `LowLevel` and when Windows Explorer is the selected window then `appCommandManager` does not work at all. Explorer is using the media keys in some way, it would appear, which stops Dopamine from knowing the media keys were pressed.

Now, if I have `LowLevel` enabled and `appCommandManager` disabled then the media keys work perfectly for dopamine universally.

And then if both are enabled and Explorer is the active window then `LowLevel` is activated but `appCommandManager` is not and Dopamine is able see the command and fires the event (`LowLevel`).

And if anything else, that does not interfere with the media keys, is active or if Dopamine is active then both `appCommandManager` and `LowLevel` are fired in Dopamine cancelling out one another.

In my case, `appCommandManager` is always fired before `LowLevel`, of course that is only the case when `appCommandManager` actually works.

What I did:

Added the following to both `Settings.xml` and `BaseSettings.xml`
```XML
  <Namespace Name="MediaKeys">
    <Setting Name="LowLevelMediaKeys">
      <Value>True</Value>
    </Setting>
  </Namespace>
```
And in `Dopamine\Dopamine.Services\Win32Input\Win32InputService.cs` @`public Win32InputService(IPlaybackService playbackService)`
```C#
if (SettingsClient.Get<bool>("MediaKeys", "LowLevelMediaKeys"))
{
    LogClient.Info("Using LowLevelManager");
    this.lowLevelManager.MediaKeyPlayPressed += MediaKeyPlayPressedHandler;
    this.lowLevelManager.MediaKeyPreviousPressed += MediaKeyPreviousPressedHandler;
    this.lowLevelManager.MediaKeyNextPressed += MediaKeyNextPressedHandler;
}
else
{
    LogClient.Info("Using AppCommandManager");
    this.appCommandManager.MediaKeyPlayPressed += MediaKeyPlayPressedHandler;
    this.appCommandManager.MediaKeyPreviousPressed += MediaKeyPreviousPressedHandler;
    this.appCommandManager.MediaKeyNextPressed += MediaKeyNextPressedHandler;
}
```
Hopefully I explained this in a way that wasn't confusing. LOL

**Comment by digimezzo** [comment]
@xCONFLiCTiONx Thanks for looking into it further. I didn't get a chance to do it myself yet. Your explanation is very clear. I conclude that both types (lowlevel and appcommand) should not be enabled together. The option that you added it somewhat what I plan to do. I will however also add a toggle button in the settings.

I've added this setting:

![image](https://user-images.githubusercontent.com/11945339/71572577-144f3e80-2ae0-11ea-844a-e1b8ab1302ba.png)

The naming comes from Winamp, where "default multimedia key support" means APPCOMMAND. The setting is disabled by default. So, by default, low level keys are used.
