### ISSUE TITLE
Jump to playing file does not work 

### ISSUE THREAD

**Issue by yoyorast1** [digimezzo/dopamine-windows#784]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10
* Dopamine version: 1.5.14

## Reproduction steps

* Step 1 Right click on a track
* Step 2 Click on "Jump to playing song". 
* Step 3

## Observed behavior
Doesn't jump to the now playing song. Nothing happens when I click on jump to the playing song, the shortcut also does not work.

## Desired behavior
 Should jump to the playing song. 

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2074117/Dopamine.log)

**Comment by digimezzo** [comment]
This is fixed in the version 2.0 Previews.
