### ISSUE TITLE
Sort songs in album by track number

### ISSUE THREAD

**Issue by nsarka** [digimezzo/dopamine-windows#788]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x ] Feature request
</code></pre>

## I'm using these versions

* Windows version:10
* Dopamine version:latest as of this posting

## Reproduction steps

* Step 1
* Step 2
* Step 3

## Desired behavior

Dopamine should have an option to sort by track number instead of only alphabetically

**Comment by digimezzo** [comment]
When you select an album, you have an option "by album" in the track list, which then sorts them by track number.

**Comment by nsarka** [comment]
Coulda swore it only switched between a-z and z-a and 'by rating' earlier, but I guess not. Thanks.

**Comment by digimezzo** [comment]
No problem. I'll try to make that more clear in Dopamine 2.0.
