### ISSUE TITLE
A bug about theme

### ISSUE THREAD

**Issue by PhoenixDream** [digimezzo/dopamine-windows#809]
I am very glad to use this production(version2.0 preview 1), but I find a BUG about interface recently. **The light theme is invalid when the soft start**.<br/>I hope software engineer can slove this problem, and thank you for your efforts. I will support you forever.
P.S:<br/>Operating environment: Windows 10 1803 version
![1](https://user-images.githubusercontent.com/32265276/42155164-3f84a4f6-7e1a-11e8-8d92-257ac6512f5b.jpg)
![2](https://user-images.githubusercontent.com/32265276/42155170-440b7004-7e1a-11e8-8081-9d2b9db95e6c.jpg)

**Comment by digimezzo** [comment]
That's intended for this preview. The light theme is not finished yet. So I am forcing the dark theme at every restart. However, I forgot to hide the theme Toggle button. So now I'm getting many reports about this "issue" :) I'l leave this issue open for now, for other people bumping into this. This will be resolved in Preview 2.

**Comment by digimezzo** [comment]
This has been fixed in Dopamine 2.0 Preview 5
