### ISSUE TITLE
Sort by Track no.

### ISSUE THREAD

**Issue by carboncoffee** [digimezzo/dopamine-windows#823]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[ X] Feature request
</code></pre>

Can you add "Sort by Track No"? It is available in ID3 and I hate naming my songs with the track number just to work around this. Many people enjoy listening to albums cover to cover in sequence.

Thanks.

**Comment by digimezzo** [comment]
When you select an album on 1 of the screens, the songs list allows you to sort "by album", which will sort songs in that album by track number. is that the feature your require?

![image](https://user-images.githubusercontent.com/11945339/43572553-26301542-9640-11e8-88a0-c526c8948568.png)

**Comment by carboncoffee** [comment]
Yesss. Sorry I'm only starting to explore the app and only have 1 album to
try it out with, so it never occurred to me to 'select' the album since the
songs are already displayed on the right. Time to add more songs, I guess.

Thanks so much.

**Comment by digimezzo** [comment]
No problem. The "by album" feature has caused confusion for other users too. In Dopamine 2.0, I've made sure that the "by album" ordering is always available, even when no album is selected.

**Comment by carboncoffee** [comment]
Are you talking about the next release of 2.0? Because in Preview 1 it's
not there unless you select an album.

**Comment by digimezzo** [comment]
You're correct that it is not in preview 1. The source code already contains this change, but it will be made public in Preview 2.
