### ISSUE TITLE
[Feature Request] Support AIFF file format

### ISSUE THREAD

**Issue by HellPie** [digimezzo/dopamine-windows#832]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

I have several albums as .AIFF files, which provide slightly better audio quality than .WAV, I am currently using MusicBee to listen to those because Dopamine doesn't support playback of .AIFF files. I would love to be able to use Dopamine for all of my albums since it looks much more native and modern than MusicBee and is also much simpler to use for what my needs are (open player, click something, click play, profit).
 
Please don't say "just convert those to .WAV" because I know the difference in quality isn't that much even for very good ears, but having roughly 10 hours of music in there it's mostly an issue of time, and it would still be nice to support playback of .AIFF files.

**Comment by digimezzo** [comment]
Support for AIFF has now been added. You'll have to wait for Dopamine 2.0 Preview 2 to have it. I'm finalizing some stuff, it shouldn't take too long to make that preview available.
