### ISSUE TITLE
Can not build on Windows 10 with VS2017

### ISSUE THREAD

**Issue by Buzzroid** [digimezzo/dopamine-windows#836]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Version 1803 Build 17134.165
* Dopamine version: latest

## Reproduction steps

* Open and Build Dopamine.sln with VS2017
* Step 2
* Step 3

## Observed behavior

Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)   Dopamine    D:\Player-projects\C#-Players\Dopamine-projects\Dopamine\Dopamine\Services\Notification\LegacyNotificationService.cs    11  Active

**Comment by digimezzo** [comment]
Please check the compile instructions here: https://github.com/digimezzo/Dopamine

**Comment by Buzzroid** [comment]
I've done what the instruction tells, but I still have the errors:

**'Media'** does not exist in the namespace **'Windows'**,
when compiling LegacyNotificationService.cs 

I'm using Windows 10 (1803) and VS 2017.

**Comment by digimezzo** [comment]
Do you have this file on you computer?

> C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd

If not, please check that you copied it to that location manually (see the compile instructions).

**Comment by Buzzroid** [comment]
Sorry for keep bothering you.

I'm sure that I've done what your instructions tell.
But, the error still exists.

Let me ask your environments:
- Your Windows version
- Your VS version

**Comment by digimezzo** [comment]
No problem. sorry for insisting :) My Windows and VS version are exactly the same as yours. 

Let's check the "Windows" dependency in the main Dopamine project:

![image](https://user-images.githubusercontent.com/11945339/44700805-839bc500-aa8b-11e8-9b24-afb42a2f680d.png)

It is probably broken, like in the picture (I'm getting this error also when the Windows.winmd file is not in the expected location). 
Try to add a new reference to the main project

![image](https://user-images.githubusercontent.com/11945339/44700862-d1183200-aa8b-11e8-8bf3-9b36b57e4dff.png)

and browse to the Windows.winmd file. That should fix the reference

![image](https://user-images.githubusercontent.com/11945339/44700885-eab97980-aa8b-11e8-9a21-c17d0d272ad2.png)

![image](https://user-images.githubusercontent.com/11945339/44700919-218f8f80-aa8c-11e8-926f-0f1980423039.png)

If that works, I'll add it to the compile instructions.

**Comment by Buzzroid** [comment]
It works!!
Thanks a lot.

**Comment by wfs1900** [comment]
The Windows.winmd file shoule be located at 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\', it's the reason, thanks!

**Comment by Wei-Han1108** [comment]
In my computer, Windows.winmd file is in "C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral\Annotated" directory. I should copy it to  “C：\Program Files （x86）\Windows Kits\10\UnionMetadata”. I hope this could help others.

**Comment by fragilebanana16** [comment]
That file may not be in disk C , depends on where your Windows Kits is installed
