### ISSUE TITLE
Cannot move install path

### ISSUE THREAD

**Issue by wildwoodwebdev** [digimezzo/dopamine-windows#847]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro V1803
* Dopamine version: 1.5.14

## Reproduction steps

* Extract all files in arbitrary location (for example "Downloads")
* Run Dopamine.exe 
* After Dopamine application opens correctly and plays music, close application.
* Move Dopamine install directory to different location
* Run Dopamine.exe

## Observed behavior

* Dopamine.exe runs and opens a GUI correctly on first launch.
* Dopamine.exe does not open a GUI when it is ran after moving install directory, but shows almost 15% CPU usage in Windows Task Manager and will keep running until stopped manually.

## Desired behavior

* Dopamine to open a GUI.

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2350698/Dopamine.log)

**Comment by wildwoodwebdev** [comment]
Note - I realized if I run as administration once it's in my C drive, it will open.

**Comment by digimezzo** [comment]
This could be a permissions issue. There C drive has a lot of access permissions. You might have unpacked it in a directory where write access is denied, unless it is accessed by an administrator. Could you verify the permissions on the folder where Dopamine is located, to confirm this?

**Comment by wildwoodwebdev** [comment]
Thank you! It was a permissions issue. I updated the permissions on the Dopamine folder in my Program Files to be set to Full Control/Modify/Write at the user level, and now it works as expected.
