### ISSUE TITLE
Crash caused by SpectrumAnalyzer.GetCurrentBarHeight() System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Bowlsys** [digimezzo/dopamine-windows#848]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro Version 1803
* Dopamine version: Version 2 Preview

## Reproduction steps

* Step 1 Select Track to Play
* Step 2 OR Press play button
* Step 3

## Observed behavior
 Dopamine closes down

## Log file
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2355912/Dopamine.log)

**Comment by digimezzo** [comment]
I changed the title as I found that the cause of the crash is the SpectrumAnalyzer.
This is the relevant log:

> 2018-09-06 08:01:06.952|Info|PlaybackService.TryPlayAsync|1172|Playing the file D:\Music\Haynes Ultimate Guide to 60s (2018)\03-13. The 5Th Dimension - Aquarius  Let The Sunshine In (The Flesh Failures) [Remastered].flac. EventMode=False, ExclusiveMode=True, LoopMode=None, Shuffle=False
> 2018-09-06 08:01:06.977|Error|App.xaml.ExecuteEmergencyStop|538|Unhandled Exception. Exception:
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Dopamine.Controls.SpectrumAnalyzer.GetCurrentBarHeight(Int32 barIndex, Boolean& isZero)
>    at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
>    at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Stack trace:
>    at Dopamine.Controls.SpectrumAnalyzer.GetCurrentBarHeight(Int32 barIndex, Boolean& isZero)
>    at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
>    at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Until the bug is fixed, as a workaround you could disable the spectrum analyzer in the settings:

> Settings > playback > Spectrum analyzer > Show the spectrum analyzer

**Comment by digimezzo** [comment]
@Bowlsys You'll have to help out a bit, as I cannot reproduce this bug. Could you download Dopamine.exe from here (it contains more logging and a possible fix): [https://www.dropbox.com/sh/fqvqotogo2jv7kr/AAC54ENOFA89y78d30bMihRWa?dl=0](https://www.dropbox.com/sh/fqvqotogo2jv7kr/AAC54ENOFA89y78d30bMihRWa?dl=0) and replace your original Dopamine.exe (where your Dopamine is installed)

Then try to  reproduce the problem (by performing the steps you described above). Once you did that, do the following:

1. let me know if Dopamine crashed
2. Send me the new log file

Thank you!

**Comment by Bowlsys** [comment]
Hi,

Solved problem. It appears that it was connected to the speaker I was using. It is a Bose Bluetooth device. When I removed the device and re-introduced it Dopamine worked fine.

Sorry if I caused you problems but please keep up the work with the best audio player I know of.

Thanks

**Comment by digimezzo** [comment]
Hi. It's great that it is solved. However, if it would happen again, or you find a way to reproduce this, I'd love to get the results that I asked in my previous comment. It would help working around this issue if someone else experiences it. Thanks :)
