### ISSUE TITLE
Lyric page refusing to scroll past a certain point

### ISSUE THREAD

**Issue by Hi-ImKyle** [digimezzo/dopamine-windows#849]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10 Pro, 1803
* Dopamine version: 1.5.14 Release

## Reproduction steps

* Step 1 Play a song
* Step 2 Go to the songs lyrics page
* Step 3 Try and scroll

## Observed behavior

Dopamine seems to refuse to scroll past a certain point on any song
## Desired behavior

Should let me scroll as much as I want.
## Log file

No relevant stuff in the log file.
## YouTube Clip
[Link](https://youtu.be/8AJzqHFjnoo)

**Comment by digimezzo** [comment]
I believe this bug was fixed in the Dopamine 2.0 preview. This is the entry in the change log:

> [Fixed] Lyrics scrolling issue when using lyrics which have no timestamps

You can try the preview if you'd like to verify. It is very stable. Also, preview 2 is coming soon.
