### ISSUE TITLE
Library empty after upgrading to 2.0 (preview)

### ISSUE THREAD

**Issue by franktopel** [digimezzo/dopamine-windows#877]
I've been using Dopamine for months, and I love it.

Today Dopamine flashed a message stating that there is a new version 2.0 (preview). Eagerly I did the update, and to my surprise, all the library information seems gone, the only album being "Unknown album" by "Unknown Artist" (instead of the 3k albums I had before).

How to fix?

**Comment by digimezzo** [comment]
If you wait a bit, it should re-populate your library. Please let me know if that works, or if it doesn't.

**Comment by franktopel** [comment]
Indeed, thanks for your quick response!
