### ISSUE TITLE
Dopamine is using 2 Gb of memory & 70% of disk

### ISSUE THREAD

**Issue by HamedWentHam** [digimezzo/dopamine-windows#880]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro Redstone 5 1809 OS Build: 17763.55
* Dopamine version: 2.0 (Preview 2)

## Reproduction steps

* Step 1 Added 193 GB of music folders into the library
* Step 2 Played them all shuffled so I can listen to different artists one after the other
* Step 3 Noticed my PC getting slower when opening chrome, file explorer, etc

**Comment by digimezzo** [comment]
Unfortunately the observed memory usage is to be expected when the whole 193 GB is shuffled. All tracks are loaded in memory, including a small thumbnail (which is displayed in now playing). But that doesn't mean that I won't try to do something about it. I'll brainstorm here about possible solutions.

First of all, could you tell me how much RAM Dopamine is using before you shuffle all tracks? I never tried with such a big collection, and want to know how much memory is used when Dopamine holds so many tracks in the collection.

Second, are thumbnails enabled in the now playing screen? If yes, could you try hiding the thumbnails in the now playing screen, and let me know if RAM usage goes down. Please let me know how much RAM is being used after hiding thumbnails.

![image](https://user-images.githubusercontent.com/11945339/47034442-ad15ca80-d177-11e8-94f8-3972f9f4d7b9.png)



Thanks!

**Comment by HamedWentHam** [comment]
Thanks for your fast reply, I did hide the thumbnails in Cover Player, also played just two songs without shuffle and the result is: 250 to 1GB of my memory & 26 to 30% of my disk being used instantly after what I've changed, I think after one or two minutes after everything settled down, the memory usage is precisely at 343 to 350MB and 0.1% disk usage, the results are the same as above when turning off shuffling & when hiding thumbnails, I'd suggest a small change that maybe can solve my problem if you don't mind ofc, I'd love to see lyrics instead of playlist in Cover Player, I know 193GB is a crazy amount of files to handle.

**Comment by digimezzo** [comment]
This issue is fixed by 3dae77b3140dafd69d8560474bc41f14f894a330
