### ISSUE TITLE
sorted by date missing in songs section?

### ISSUE THREAD

**Issue by iftkharhussain** [digimezzo/dopamine-windows#883]
i have lots of collection of music in my PC but now add some new music files and now i'm unable to find my new music . I'm wondering how a big this application missing some basic feature of sorting please add this feature in next update.

**Comment by digimezzo** [comment]
Thanks for the feature request. I'll add it for the next preview. 

Just a tip for the future. Saying things like  **I'm wondering how a big this application missing some basic feature** irritates and demotivates a developer. I'd like to kindly point out that a lot of free time went into creating Dopamine. Saying such things, makes it look like all this effort was not good enough. So please remember to provide feedback to developers (also other developers than me) in a constructive and non-criticizing way. Thanks.
