### ISSUE TITLE
doesn't install

### ISSUE THREAD

**Issue by adamzugone** [digimezzo/dopamine-windows#890]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: windows 10
* Dopamine version: 1.5.14

## Reproduction steps

* Step 1: open dopamine.exe in zipped folder
* Step 2: go through setup process, upload the songs from my computer etc.
* Step 3: pin it to task bar, when done with it, close it

## Observed behavior

First off, I can't find the Dopamine program when searching on the computer, but that's why I pinned it. So I could get to it later. Next day, want to open Dopamine from task bar, but it says that this program doesn't exist. Thought maybe I'd go back to dopamine.exe in the zipped folder but it just starts a brand new program like I've never opened it. But before I could close it and re-open it just fine and all my music would still be there.
## Desired behavior

Should install as an actual program so I can open it whenever and always have my music on it.

**Comment by digimezzo** [comment]
Where did you download it from? It seems you downloaded the portable version, and that you didn't unzip the zip file. If you download the portable version and the zip file is unzipped, you have a version that is contained into 1 folder. That makes it portable so it can easily be used on other computers.

If you want to have a version that can be installed like any other program, you should download the installable version.

Please go to https://www.digimezzo.com/ and go to the downloads section. There you'll find different versions:

* **Dopamine 1.5.14 (Release) - Portable.zip** -> that is the portable version
* **Dopamine 1.5.14 (Release).msi** -> that is the installable version

You'll also find similar files for the Dopamine 2.0 preview 2 if you'd like to see cool new stuff.

**Comment by adamzugone** [comment]
> Where did you download it from? It seems you downloaded the portable version, and that you didn't unzip the zip file. If you download the portable version and the zip file is unzipped, you have a version that is contained into 1 folder. That makes it portable so it can easily be used on other computers.
> 
> If you want to have a version that can be installed like any other program, you should download the installable version.
> 
> Please go to https://www.digimezzo.com/ and go to the downloads section. There you'll find different versions:
> 
> * **Dopamine 1.5.14 (Release) - Portable.zip** -> that is the portable version
> * **Dopamine 1.5.14 (Release).msi** -> that is the installable version
> 
> You'll also find similar files for the Dopamine 2.0 preview 2 if you'd like to see cool new stuff.

I didn't even think of the fact that I could've downloaded a version that doesn't actually install the full program😅 Thank you! I really like it, by the way. If it wasn't so good I probably wouldn't have even reported my problem and would've just moved on to a different program😄
