### ISSUE TITLE
Crashes when "Enable System Notification" checked

### ISSUE THREAD

**Issue by volsend** [digimezzo/dopamine-windows#892]
## Versions
* Windows version: 10 Enterprise N (Version	10.0.16299 Build 16299)
* Dopamine version: 2.0 (Preview 2)

## Reproduction steps
* Open Dopamine
* Goto **Settings -> Playback**
* Enable **Enable System Notification** setting
* Return to player and try starting any song or, if the song is already playing, switching to another one.

## Observed behavior
Dopamine closes with no any warnings or erros.

## Desired behavior
Showing system notification when some sond started

## Log file
Attaching log file with more datils.

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2512236/Dopamine.log)

**Comment by digimezzo** [comment]
The media system notification is, apparently, not supported in N editions of Windows.

**Note to myself:** check for presence of Media Foundation when deciding which notication service to add to the dependency injector container.
