### ISSUE TITLE
Very low FPS with windowed G-SYNC enabled

### ISSUE THREAD

**Issue by neilunger** [digimezzo/dopamine-windows#895]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows Edition: Windows 10 Enterprise
* Windows Version: 1803
* Windows OS build: 17134.345
* Dopamine version: 1.5.14 (Release)
* NVIDIA Driver version: 416.34
* Graphics Card: GTX 1060
* G-SYNC montior: Dell S2716DG

## Reproduction steps

* Step 1: Enable G-SYNC in the NVIDIA Control Panel for both windowed and full screen mode.
* Step 2: Use Dopamine
* Step 3: Observe very low FPS (~20 frame per second)

## Observed behavior

Dopamine has extremely low FPS when the NVIDIA control panel is set to use G-SYNC for windowed applications.

When set to "Enable G-SYNC for full screen mode", Dopamine runs at 144+ FPS.
When set to "Enable G-SYNC for windowed and full screen mode", Dopamine runs at ~20 FPS.
## Desired behavior

Dopamine should have the same FPS as all other applications when the NVIDIA control panel is set to use G-SYNC for windowed applications.

## Log file
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2531518/Dopamine.log)

**Comment by neilunger** [comment]
For anyone experiencing this issue, here's a temporary fix:
1. Open the NVIDIA Control Panel and navigate to "Manage 3D Settings"
2. Select the "Program Settings" tab
3. Click "Add" to add a program, and select Dopamine
4. Change the "Monitor Technology" from "G-SYNC" to either "ULMB" or "Fixed Refresh" (they seem the same to me, but from what I've read ULMB is supposedly better)

**Comment by digimezzo** [comment]
@neilunger Thank you for the workaround! This could be a problem with WPF. I tried to find information about this, but could only find this reddit thread where someone mentions problems when using G-SYNC with WPF: https://www.reddit.com/r/nvidia/comments/56muxg/what_is_the_difference_between_gsync_for/

**Comment by BradG13542** [comment]
So I noticed that if Dopamine is started with the 'now playing' tab open the audio spectrum behaves as expected but if you then close the 'now playing' tab (showing song collections) then reopen the 'now playing' tab the audio spectrum freezes unless you repeatedly hover over the song time bar. Not sure if this is related or if it's a different bug but worth a mention. (Using a 144hz monitor and applied the temporary fix).

**Comment by Nord-Licht** [comment]
I can't fully comprehend your observation. Yes, it's true that the visualization in "Now Playing" runs more smoothly (although still slightly jerky), but the change back and forth the view doesn't bring anything at all, at least not for me.

Also, this doesn't only affect the visualization, but also the progress bar (which also moves jerky). It would be more than nice if this could be solved somehow, I'm really bothered by it now. By the way, the workarounds suggested here do not work for me (Nvidia settings).

Is there anything I can do to contribute to solving this problem? Other than donating a 144Hz display? ;)

Edit: Btw., disabling GSYNC alone also don't works for me. I have to disable it and have to set the refresh rate to below (!) 120Hz. 120Hz itself is also choppy, I'm using 100Hz for now.
