### ISSUE TITLE
Collection issues when renaming files and folders

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#896]
**Reported by a user:**

I recently did some folder renaming in my music collection, the result was invalid entries in my playlists (which was expected) and in dopamine's library (unexpected).  I thought I had it set up to find new songs on boot, but I'm manually doing that now (going to add songs and hitting refresh).

So after manually updating the library the song can be added back into the playlist, but the invalid entries cannot be removed using dopamine...which is new to this preview i think.  I think the library not updating was in preview 2.

**Comment by Neyht** [comment]
I think this should be two different issues, actually:  
1:Dopamine doesn't recognize subfolder changes in my library until manually updated.

2:Playlist entries with no song cannot be removed from playlist.

It also looks like the subfolder issue isn't new to 2.0?

(I'm the user by the way)

**Comment by Neyht** [comment]
It looks like **folder renaming** doesn't trigger a collection update in dopamine until I actually rename a music file.... Okay, that's it, that's whats happening.

**Comment by Neyht** [comment]
I just rechecked the second issue is happening to a number of my playlists and I don't think it has anything to do with the first issue

**Comment by digimezzo** [comment]
Oops, I seem to have logged this issue twice. It's the same as #909.
