### ISSUE TITLE
Swapping audio source in Windows sometimes opens a 2nd process of Dopamine

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#90]
Reported by a user:

Swapping audio source in Windows sometimes opens a 2nd process of Dopamine and you get sound from both sources and if you close down Dopamine you'll still have one source having sound from the 2nd process and you'll have to close it down from Task Manager. It doesn't happen all the time.

**Comment by accuratecopy** [comment]
I confirm, i had the problem just right now.
I shifted sound with physical button from headphones to speakers on my ASUS Xonar U7 and it passed to the next song, had 2 instances of Dopamine running.
I got sound from both sources.
I attached the log, if you need it.
[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/441058/Dopamine.zip)
