### ISSUE TITLE
Where is the assembly "Windows"？

### ISSUE THREAD

**Issue by tpxxn** [digimezzo/dopamine-windows#900]
I want to learn the writing of WPF programs.
When I download the source code and are ready to press F5 (run), I get some error.
One of them is as follows:
Could not resolve this reference. Could not locate the assembly "Windows". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
![Screenshot](https://user-images.githubusercontent.com/10829204/48097285-700f9600-e254-11e8-9605-fe0ea007b9e5.png)
How can I solve this problem?

**Comment by digimezzo** [comment]
Please check this issue: #836.

**Comment by tpxxn** [comment]
Oh, it's useful! Thank you(｡･∀･)ﾉﾞ

**Comment by digimezzo** [comment]
You're welcome. I wanted to add this info to the Dopamine GitHub page, but didn't get the chance to do so yet.

**Comment by tpxxn** [comment]
> You're welcome. I wanted to add this info to the Dopamine GitHub page, but didn't get the chance to do so yet.
I can help you modify the readme.md and submit the pull request, how do you see it?
