### ISSUE TITLE
abnormal RAM consumption

### ISSUE THREAD

**Issue by Mustafa744** [digimezzo/dopamine-windows#903]
I'm submitting a...

[ ] Regression 
[x ] Bug report  
[ ] Feature request

## I'm using these versions

* Windows version: windows 10 pro version 1803
* Dopamine version:Version 2.0(Preview 3)

## Reproduction steps

* Step 1
![1](https://user-images.githubusercontent.com/24313619/48578773-3eb55b00-e923-11e8-8054-9848aed50451.PNG)

* Step 2
so the program runs perfectly but when i minimize it i noticed an abnormal ram cosumption, the amount of ram consumed increases by the the time tell the program consumes all of ram 
* Step 3
![2](https://user-images.githubusercontent.com/24313619/48578896-98b62080-e923-11e8-8183-d1b34d5c3dd8.PNG)
after i maximize the program the amount of consumed ram decreases again

both pictures were taken in the same conditions(the same song is played ) the time interval between these two pictures is 1 second aprox 

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2586886/Dopamine.log)

**Comment by NotAkitake** [comment]
I second this, when minimized to tray and playing, ram gets eaten up slowly, I end up having to kill the process.

**Comment by digimezzo** [comment]
@Mustafa744 , @AkitakeKun , many thanks for the details you provided to pinpoint this bug. I was able to reproduce and fix it. The fix will be in preview 4. I want to fix some more annoying issue first, but I'll try to release it as soon as possible.

**Comment by Mustafa744** [comment]
kep up the good work ❤❤❤
