### ISSUE TITLE
Empty "Unknown" categories under Artist and Genre views (Dopamine 2.0)

### ISSUE THREAD

**Issue by zombiedonut** [digimezzo/dopamine-windows#904]
## I'm submitting a...
<pre><code>[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions
* Windows 10 (1607)
* Dopamine 2.0 (Preview 3)

## Observed behavior
Under both the **Artists** and **Genres** tabs, an **Unknown artist / Unknown genre** category appears. Both categories are completely empty and show "0" as the number of files. Issue persists even after restart.

***

Not sure what's causing it. All my music is properly tagged. I would also assume if it _was_ an issue with my own tagging then the category would show those "unknown" files rather than simply being empty.

I was using Dopamine 1.5.14 originally and installed the preview over top to try it out. I also did a clean install of 2.0 on a separate computer (same music library, same OS) but had the same problem. I do keep images in my main music folder (cover art) which I thought might be the problem, however the issue remained even after removing these items and re-scanning.

Don't know if it's a bug or something amiss in my library, but thought it was still worth mentioning.

**Comment by digimezzo** [comment]
@zombiedonut This is normal since Preview 3. The unknown categories are reserved for songs which are not properly tagged. So it is normal that they are empty in your case.

Now, it might be better if I just don't show these categories if they are empty. I'll fix this issue as such for the next preview.
