### ISSUE TITLE
Last.fm scrobble broken on Preview 3

### ISSUE THREAD

**Issue by ddasutein** [digimezzo/dopamine-windows#905]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 (1809)
* Dopamine version: Dopamine 2.0 (Preview 3)

## Observed behavior

After updating to Preview 3 from Preview 1, the application would no longer scrobble to Last.fm. I tried reinstalling Preview 3 and re-connecting my Last.fm account and it won't scrobble. Downgrading back to Preview 1 and Last.fm scrobble is functional again.

**Comment by digimezzo** [comment]
@ddasutein Thank you for reporting this. I pinpointed the issue and am fixing it as we speak. The fix will be in preview 4.
