### ISSUE TITLE
Right-click menu on now playing panes

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#908]
There is a right-click menu on the now playing panes. The original idea was to be able to add the currently playing song to a playlist. However the implementation seems buggy. E.g. the text is not visible:

![image](https://user-images.githubusercontent.com/11945339/48803849-5d489700-ed13-11e8-9afd-feb09ad1c96d.png)

**Comment by Trifon1** [comment]
There is also a preview of 4
![2018-11-21 1](https://user-images.githubusercontent.com/44848559/48847350-f9bd7880-eda9-11e8-845b-10372b6dd2d9.png)

**Comment by digimezzo** [comment]
@Trifon1 That's correct. The issue was fixed after releasing preview 4. So the fix will be in preview 5.
