### ISSUE TITLE
Misc. problems when renaming files and folders on computer

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#909]
Things to verify:

- [x] Collection might not refresh automatically after renaming files or folders on disk, even if "Refresh collection automatically" is selected.
- [x] After renaming a file or folder on disk, if that file is in a playlist, when trying to remove that file from the playlist, the wrong file is removed.

The playlist issue can also be reproduced by removing and adding songs to a playlist (.M3U).  It's loosing track of the playlist order and doesn't remove the correct song after that.

**Comment by Neyht** [comment]
The second (what is that, a bullet-point?) needs to be edited.  I misunderstood what was happening initially.  It turned out it **was** removing a file from the playlist, _just not the right one_.  I was grouping two things together that were separate.  That last sentence then is a rather accurate description of the second issue.

**Comment by digimezzo** [comment]
@neyht, I edited the bullet point. I've been working on that issue tonight and indeed saw that behaviour. Dopamine removes files from the playlist by index (the position in the list). When renaming or removing a file on disk, the position in the playlist in Dopamine changes, but it doesn't  change it the playlist file, so there is a mismatch. This causes the wrong line to be removed from the playlist file. Long story short, that piece of code needs to be rewritten. I'll handle this in preview 5.

**Comment by digimezzo** [comment]
The issue concerning deletion of tracks from playlists is fixed in commit f68f6a727ecd7466eeca411b53adcf5f3746a96d

There is indeed also a collection refresh issue. Adding and deleting files from disk does triggered a collection refresh. Renaming of files and folders doesn't. This will also be addressed.

**Comment by digimezzo** [comment]
File or folder renaming is detected by Dopamine. However, no re-scan is performed, because the file count hasn't changed. A fix for this issue will require a major rework of the indexing architecture. It will be handled in #787. I'll close this issue. Further indexing problems will be handled in #787.
