### ISSUE TITLE
Top 1px border is missing in Now playing

### ISSUE THREAD

**Issue by The-Choo-Choo-Shoe** [digimezzo/dopamine-windows#918]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 1809
* Dopamine version: 2.0 Preview 5

## Reproduction steps

* Step 1: Enable 1px border in settings.
* Step 2: Click Now playing button in the bottom left.

## Observed behavior

Top 1px border is missing when 1px border is enabled, works fine with it disabled.
## Desired behavior

It should have a top 1px border.

**Comment by The-Choo-Choo-Shoe** [comment]
![untitled](https://user-images.githubusercontent.com/31801661/49335337-dd141280-f5eb-11e8-9e71-7d92874cffef.png)

**Comment by digimezzo** [comment]
Which zooming level are you using in Windows?

**Comment by The-Choo-Choo-Shoe** [comment]
100%, no scaling at all.

**Comment by digimezzo** [comment]
Ok thanks. I'll check it out.
