### ISSUE TITLE
Wrong albums under artists

### ISSUE THREAD

**Issue by The-Choo-Choo-Shoe** [digimezzo/dopamine-windows#922]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 1809
* Dopamine version: 2.0 Preview 5

## Reproduction steps

* Step 1: You need 2 artists with the same letters in order.
* Step 2: Open the artists tab and scroll down to something like ABBA if you have Black Sabbath music as well.
* Step 3: Check albums under artist tab, Black Sabbath albums will be under ABBA.

## Observed behavior
 Black SABBAth albums are under ABBA.

## Desired behavior
 Black Sabbath albums should not be under ABBA even if ABBA is part of Sabbath.

**Comment by The-Choo-Choo-Shoe** [comment]
![untitled](https://user-images.githubusercontent.com/31801661/49455992-74de5000-f7e8-11e8-91e7-b8abb9458b08.png)

This is all I can think of, that the album is under ABBA because of Sabbath, I've tried to clear metadata and everything with no change.

Sorry if this issue already exist, I tried to search for it first.

**Comment by daedos** [comment]
A more extreme using the band A

![image](https://user-images.githubusercontent.com/15990518/49580046-db2cb500-f945-11e8-848b-6107fcb36729.png)

**Comment by digimezzo** [comment]
Could you send me your Dopamine.db file? You'll find it in folder %appdata%\Dopamine

**Comment by The-Choo-Choo-Shoe** [comment]
Data Base:
[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/2656577/Dopamine.zip)

**Comment by digimezzo** [comment]
@The-Choo-Choo-Shoe The bug is fixed. You'll get the fix in the next preview.
