### ISSUE TITLE
'Enable System Notification' switch function is flipped

### ISSUE THREAD

**Issue by iceberg27** [digimezzo/dopamine-windows#924]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Home v1809 x64
* Dopamine version: 2.0 (Preview 5)

## Reproduction steps

* Dopamine>Open menu
* Settings>Playback>Notification
* Toggle 'Enable System Notification' ON/OFF

## Observed behavior

The "Enable system notification' button in 'Playback' section under settings is flipped. (It does the opposite of what it shows, i.e; it shows notification when button is off and no notifications when it's on)

## Desired behavior

The notifications should be displayed when the switch is ON and hidden when switch is OFF.

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/2656524/Dopamine.log)

**Comment by digimezzo** [comment]
@iceberg27 This works as intended. The "Enable system notification" works as such:

- Switch is ON: Custom Dopamine notification is displayed
- Switch if OFF: Windows 10 (=system) notification is displayed

If you wish to disable notifications completely, make sure that all "Show a notification when..." switches are off.
