### ISSUE TITLE
Memory leak when "close to the notification area"

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine-windows#944]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro insider Build 18317
* Dopamine version: 2.0 Preview 2

## Reproduction steps

* Step 1 Turn on "close to the notification area"
* Step 2 Close Dopamine window

## Observed behavior
The memory of Dopamine keeps increasing by 20MB/s
![image](https://user-images.githubusercontent.com/11793304/51303532-a34e7c80-1a70-11e9-86ac-35ef5635417a.png)

## Log file

I think there're no useful log.

**Comment by digimezzo** [comment]
Please upgrade to the latest preview. This is a memory leak that was fixed since preview 4.
Here's 1 of the memory issues: https://github.com/digimezzo/Dopamine/issues/921

**Comment by Magentaize** [comment]
Oh, I'm sorry for not using the latest version. I thought that it still is preview 2 due to no update notification.

**Comment by Magentaize** [comment]
Great job! I love this new light theme.

**Comment by digimezzo** [comment]
You didn't get an update notification? That might be a bug then :)
