### ISSUE TITLE
Ratings are forgotten unless "Save the rating in audio files (MP3 only)" is active

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#946]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10
* Dopamine version: 2.0p6

## Reproduction steps

* Add songs to Now Playing
* Give songs a rating via rating buttons
* Restart Dopamine

## Observed behavior
Ratings are reset to default (no rating)

## Desired behavior
Rating is remembered from last time

**Comment by digimezzo** [comment]
This issue cannot be reproduced anymore; It was probably fixed between this report and the current Preview.
