### ISSUE TITLE
Songs screen doesn't remember sorting preferences

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#95]
The sorting preferences on the "Songs" screen are not remembered. It always defaults to album sorting.

**Comment by iamkroot** [comment]
Facing this issue now. Could this please be fixed? 😃

**Comment by volodyatrots** [comment]
Hi, it is still not working. I am soring music by date created, so do you have any info when it will be fixed?

**Comment by digimezzo** [comment]
@volodyatrots I kept delaying it, because it is hard to do. But I'll try to fix this soon for the next version (which I want to release in a few days).
Note to myself: https://stackoverflow.com/questions/16956251/sort-a-wpf-datagrid-programmatically
