### ISSUE TITLE
Move notifications

### ISSUE THREAD

**Issue by kukata-81** [digimezzo/dopamine-windows#950]
This notice should pull slightly above the ribbon. Or be able to be moved with the mouse.﻿
![1](https://user-images.githubusercontent.com/47054924/51786095-2d30d080-2168-11e9-9d5a-2d8d21321318.png)

**Comment by kukata-81** [comment]
This happens only when "automatic hide taskbar" is active. When this option is deactivated everything works fine.

**Comment by digimezzo** [comment]
OK, that is not a bug. When the taskbar is hidden, windows reports the available screen space including the space occupied by the task bar. There is nothing we can do about that.
