### ISSUE TITLE
Add windows live tile support

### ISSUE THREAD

**Issue by ryan-seifi** [digimezzo/dopamine-windows#954]
## I'm submitting a...

<pre><code>
 Feature request
</code></pre>

Hi,

I'm using your app as a great alternative to Groove that became so low in it's latest updates. 
But it lacks some minor features, such as Live Tile.
As you are using Windows SDK, which they expose native UWP APIs, you can add live tile support real quick.

Thanks for your great work on this app.

**Comment by ThePharaohArt** [comment]
This doesn't make sense to get anymore since since it seems that Windows is doing away with the tile system on windows in the next few major updates.

**Comment by digimezzo** [comment]
Tiles are not Microsoft's focus anymore, so I'm closing this issue.
