### ISSUE TITLE
Discord Rich Presence integration

### ISSUE THREAD

**Issue by BradG13542** [digimezzo/dopamine-windows#966]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Discord Rich Presence to show the current song, album, artist and elapsed play time (Similar to how Spotify is integrated with Discord although some aspects of it may not be possible to implement).

**Comment by innocenzi** [comment]
Won't be possible to do like Spotify, since it's a special integration. 
It's possible to do something similar to this though: 

![](https://i.imgur.com/6MjOXW2.png)
