### ISSUE TITLE
Preview / Feature missing: option to use Album Artist tag for Artists tab

### ISSUE THREAD

**Issue by neubland** [digimezzo/dopamine-windows#981]
## I'm submitting a...

<pre><code>
[ X ] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10 (1903)
* Dopamine version: 2.0 Preview 7

## Reproduction steps

It is not possible to use Album Artist tag for Artists tab anymore. Previously, one could change the behaviour by clicking "Album" or "Title" next to "Artists", but now the button is gone.

**Comment by digimezzo** [comment]
That feature was removed intentionally. A lot of user mix up artist and album artist and complain their albums shows "unknown artist" when they forget to fill in the album artist. A suggestion was to use the track artist as a album artist when album artist is empty. That was implemented. Because of that, the artist/album artist switch in the artists list wasn't reliable anymore and was thus removed.

**Comment by neubland** [comment]
Wow, I hope that's temporary, because it is actually a dealbreaker - which is a shame, because is great in every other way.

I am well aware that many users don't tag their files correctly, but many others do. Also, many users listen to their music by album. Making it an option to prefer album artist for the artist list would make it possible to see all the albums from an artist (or from "Various Artists"), without having the list cluttered up by many artists that are only featured on single tracks on the albums.

Please consider re-adding this feature. If I should open a separate issue for this, I will do so.

**Comment by RobH99** [comment]
Well that is a pity!  ;-(  

It is a deal breaker for me as well then.  My artist list is now stupidly long. 

People who tag their files properly shouldn't be penalised for those who don't.

Could it at least be and option to turn the album artist feature on and off in the settings?

Until then I will regress to the previous version, and it looks like I will have to stay there unless there is a sensible solution or compromise.  Album artist is definitely the way to do it, and people should learn how to tag their files correctly.

**Comment by digimezzo** [comment]
I've re-added the feature. It'll be available in the next preview.
