### ISSUE TITLE
Tray icon should change to black with light task bar

### ISSUE THREAD

**Issue by neubland** [digimezzo/dopamine-windows#982]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[ X ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10 (1903)
* Dopamine version: 1.5 AND 2.0

## Reproduction steps

* Turn on light taskbar (new Windows feature in 1903 build)

## Observed behavior

* The dopamine tray icon is white, while system tray icons are inverted (they are black)
## Desired behavior

* Dopamine should notice the light taskbar and change it's tray icon color automatically

**Comment by digimezzo** [comment]
Let's have a look at this: https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode
