### ISSUE TITLE
Short Sound on startup

### ISSUE THREAD

**Issue by jcliftonmeek** [digimezzo/dopamine-windows#999]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 1903 (18362.239)
* Dopamine version: 2.0 (Preview 10)

## Reproduction steps

* Step 1: Open Dopamine.
* Step 2
* Step 3

## Observed behavior
When I open Dopamine, a short sound is made that seems to be the first song in the existing playlist. Sound lasts maybe half-second.

## Desired behavior
Should be silent until music is elected to be played.

## Log file

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3378425/Dopamine.log)

**Comment by digimezzo** [comment]
@jcliftonmeek Thank you for reporting this. The issue has been fixed. You'll notice the result in Dopamine 2.0 Preview 11.
